# SPDX-License-Identifier: MPL-2.0
# Stapeln.Codegen - Generates Containerfiles and compose files from stack definitions.
#
# Supports output formats:
#   - Containerfile (Podman/Docker)
#   - docker-compose.yml
#   - selur-compose.toml (hyperpolymath format)
#   - podman-compose.yml

defmodule Stapeln.Codegen do
  @moduledoc """
  Code generation engine for container stack definitions.

  Accepts a stack map (as stored by `Stapeln.StackStore` or `Stapeln.DbStore`) and
  produces deployment artefacts: Containerfiles, docker-compose.yml,
  selur-compose.toml, or podman-compose.yml.
  """

  @type format :: :containerfile | :docker_compose | :selur_compose | :podman_compose
  @type codegen_result :: {:ok, String.t()} | {:error, String.t()}

  @doc """
  Generate deployment artefact(s) for the given stack in the requested format.
  """
  @spec generate(map(), format()) :: codegen_result()
  def generate(stack, format) when is_map(stack) do
    services = normalise_services(stack)
    stack_name = Map.get(stack, :name, Map.get(stack, "name", "unnamed-stack"))

    case format do
      :containerfile -> generate_containerfile(stack_name, services)
      :docker_compose -> generate_docker_compose(stack_name, services)
      :selur_compose -> generate_selur_compose(stack_name, services)
      :podman_compose -> generate_podman_compose(stack_name, services)
    end
  end

  @doc """
  Generate all supported formats at once, returning a map of format => content.
  """
  @spec generate_all(map()) :: {:ok, %{format() => String.t()}} | {:error, String.t()}
  def generate_all(stack) when is_map(stack) do
    results =
      [:containerfile, :docker_compose, :selur_compose, :podman_compose]
      |> Enum.reduce(%{}, fn fmt, acc ->
        {:ok, content} = generate(stack, fmt)
        Map.put(acc, fmt, content)
      end)

    {:ok, results}
  end

  # ---------------------------------------------------------------------------
  # Containerfile generation
  # ---------------------------------------------------------------------------

  defp generate_containerfile(stack_name, services) do
    header = """
    # SPDX-License-Identifier: MPL-2.0
    # Containerfile generated by stapeln codegen engine
    # Stack: #{stack_name}
    # Generated: #{DateTime.utc_now() |> DateTime.to_iso8601()}
    """

    stages =
      services
      |> Enum.with_index()
      |> Enum.map(fn {svc, idx} ->
        image = service_image(svc)
        name = service_name(svc)
        port = service_port(svc)
        env_vars = service_env(svc)
        volumes = service_volumes(svc)
        cmd = service_cmd(svc)

        stage_lines = [
          "# Stage #{idx}: #{name}",
          "FROM #{image} AS #{sanitise_stage_name(name)}"
        ]

        label_lines = [
          "LABEL org.opencontainers.image.title=\"#{stack_name}\"",
          "LABEL com.hyperpolymath.stapeln.service=\"#{name}\""
        ]

        env_lines =
          env_vars
          |> Enum.map(fn {k, v} -> "ENV #{k}=#{inspect(v)}" end)

        port_lines =
          if port && port > 0,
            do: ["EXPOSE #{port}"],
            else: []

        volume_lines =
          volumes
          |> Enum.map(fn v -> "VOLUME #{v}" end)

        workdir_line = ["WORKDIR /app"]

        cmd_line =
          if cmd && cmd != "",
            do: ["CMD #{cmd}"],
            else: []

        (stage_lines ++ [""] ++ label_lines ++ env_lines ++ port_lines ++ volume_lines ++ workdir_line ++ cmd_line)
        |> Enum.join("\n")
      end)
      |> Enum.join("\n\n")

    {:ok, header <> "\n" <> stages <> "\n"}
  end

  # ---------------------------------------------------------------------------
  # docker-compose.yml generation
  # ---------------------------------------------------------------------------

  defp generate_docker_compose(stack_name, services) do
    header = """
    # SPDX-License-Identifier: MPL-2.0
    # docker-compose.yml generated by stapeln codegen engine
    # Stack: #{stack_name}
    # Generated: #{DateTime.utc_now() |> DateTime.to_iso8601()}

    version: '3.8'

    services:
    """

    service_blocks =
      services
      |> Enum.map(fn svc ->
        name = service_name(svc) |> sanitise_stage_name()
        image = service_image(svc)
        port = service_port(svc)
        env_vars = service_env(svc)
        volumes = service_volumes(svc)
        depends = service_depends(svc)
        resources = service_resources(svc)

        lines = ["  #{name}:", "    image: #{image}"]

        lines =
          if port && port > 0 do
            lines ++ ["    ports:", "      - \"#{port}:#{port}\""]
          else
            lines
          end

        lines =
          if env_vars != [] do
            env_block = Enum.map(env_vars, fn {k, v} -> "      #{k}: #{inspect(v)}" end)
            lines ++ ["    environment:"] ++ env_block
          else
            lines
          end

        lines =
          if volumes != [] do
            vol_block = Enum.map(volumes, fn v -> "      - #{v}" end)
            lines ++ ["    volumes:"] ++ vol_block
          else
            lines
          end

        lines =
          if depends != [] do
            dep_block = Enum.map(depends, fn d -> "      - #{d}" end)
            lines ++ ["    depends_on:"] ++ dep_block
          else
            lines
          end

        lines =
          case resources do
            %{cpu: cpu, memory: mem} when cpu > 0 or mem > 0 ->
              res_lines = ["    deploy:", "      resources:", "        limits:"]

              res_lines =
                if cpu > 0,
                  do: res_lines ++ ["          cpus: '#{cpu}'"],
                  else: res_lines

              res_lines =
                if mem > 0,
                  do: res_lines ++ ["          memory: #{mem}M"],
                  else: res_lines

              lines ++ res_lines

            _ ->
              lines
          end

        lines ++ ["    restart: unless-stopped"]
        |> Enum.join("\n")
      end)
      |> Enum.join("\n\n")

    {:ok, header <> service_blocks <> "\n"}
  end

  # ---------------------------------------------------------------------------
  # selur-compose.toml generation
  # ---------------------------------------------------------------------------

  defp generate_selur_compose(stack_name, services) do
    header = """
    # SPDX-License-Identifier: MPL-2.0
    # selur-compose.toml generated by stapeln codegen engine
    # Generated: #{DateTime.utc_now() |> DateTime.to_iso8601()}

    [stack]
    name = "#{stack_name}"
    version = "1.0"
    runtime = "podman"

    """

    service_blocks =
      services
      |> Enum.map(fn svc ->
        name = service_name(svc)
        image = service_image(svc)
        kind = service_kind(svc)
        port = service_port(svc)
        env_vars = service_env(svc)
        volumes = service_volumes(svc)

        lines = [
          "[[services]]",
          "name = \"#{name}\"",
          "type = \"#{kind}\"",
          "image = \"#{image}\""
        ]

        lines =
          if port && port > 0,
            do: lines ++ ["port = #{port}"],
            else: lines

        lines =
          if env_vars != [] do
            env_str = Enum.map_join(env_vars, ", ", fn {k, v} -> "\"#{k}=#{v}\"" end)
            lines ++ ["env = [#{env_str}]"]
          else
            lines
          end

        lines =
          if volumes != [] do
            vol_str = Enum.map_join(volumes, ", ", fn v -> "\"#{v}\"" end)
            lines ++ ["volumes = [#{vol_str}]"]
          else
            lines
          end

        Enum.join(lines, "\n")
      end)
      |> Enum.join("\n\n")

    {:ok, header <> service_blocks <> "\n"}
  end

  # ---------------------------------------------------------------------------
  # podman-compose.yml generation (mostly same as docker-compose)
  # ---------------------------------------------------------------------------

  defp generate_podman_compose(stack_name, services) do
    case generate_docker_compose(stack_name, services) do
      {:ok, content} ->
        # Podman-compose is docker-compose compatible; add podman-specific header
        podman_content =
          content
          |> String.replace(
            "# docker-compose.yml generated by stapeln codegen engine",
            "# podman-compose.yml generated by stapeln codegen engine"
          )

        {:ok, podman_content}

      error ->
        error
    end
  end

  # ---------------------------------------------------------------------------
  # Service field extractors (handles both atom and string keys)
  # ---------------------------------------------------------------------------

  # Public so Stapeln.BundleCodegen can source its tokens from the same place
  # these emitters do, rather than growing a second, drifting copy of the
  # stack-shape knowledge. Not part of the documented API.
  @doc false
  def normalise_services(stack) do
    services =
      Map.get(stack, :services, Map.get(stack, "services", []))

    case services do
      list when is_list(list) -> list
      _ -> []
    end
  end

  @doc false
  def service_name(svc) do
    Map.get(svc, :name, Map.get(svc, "name", "service"))
  end

  defp service_kind(svc) do
    Map.get(svc, :kind, Map.get(svc, "kind", "web"))
  end

  defp service_image(svc) do
    default =
      case service_kind(svc) do
        "web" -> "cgr.dev/chainguard/wolfi-base:latest"
        "worker" -> "cgr.dev/chainguard/wolfi-base:latest"
        "db" -> "cgr.dev/chainguard/postgres:latest"
        "redis" -> "cgr.dev/chainguard/redis:latest"
        "gateway" -> "ghcr.io/hyperpolymath/svalinn:latest"
        _ -> "cgr.dev/chainguard/wolfi-base:latest"
      end

    Map.get(svc, :image, Map.get(svc, "image", default))
  end

  @doc false
  def service_port(svc) do
    case Map.get(svc, :port, Map.get(svc, "port", nil)) do
      p when is_integer(p) and p > 0 -> p
      p when is_binary(p) ->
        case Integer.parse(p) do
          {n, ""} -> n
          _ -> 0
        end
      _ -> nil
    end
  end

  defp service_env(svc) do
    case Map.get(svc, :env, Map.get(svc, "env", [])) do
      env when is_map(env) -> Enum.to_list(env)
      env when is_list(env) ->
        Enum.flat_map(env, fn
          {k, v} -> [{k, v}]
          str when is_binary(str) ->
            case String.split(str, "=", parts: 2) do
              [k, v] -> [{k, v}]
              _ -> []
            end
          _ -> []
        end)
      _ -> []
    end
  end

  defp service_volumes(svc) do
    case Map.get(svc, :volumes, Map.get(svc, "volumes", [])) do
      vols when is_list(vols) -> vols
      _ -> []
    end
  end

  defp service_depends(svc) do
    case Map.get(svc, :depends_on, Map.get(svc, "depends_on", [])) do
      deps when is_list(deps) -> deps
      _ -> []
    end
  end

  defp service_cmd(svc) do
    Map.get(svc, :cmd, Map.get(svc, "cmd", nil))
  end

  defp service_resources(svc) do
    cpu = Map.get(svc, :cpu, Map.get(svc, "cpu", 0))
    memory = Map.get(svc, :memory, Map.get(svc, "memory", 0))

    cpu_val = if is_number(cpu), do: cpu, else: 0
    mem_val = if is_number(memory), do: memory, else: 0

    %{cpu: cpu_val, memory: mem_val}
  end

  defp sanitise_stage_name(name) do
    name
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9_-]/, "-")
    |> String.trim("-")
  end
end
