# SPDX-License-Identifier: MPL-2.0
defmodule Stapeln.ComposeYaml do
  @moduledoc """
  File 10 of the bundle: `compose.yaml`, the file a runner actually runs.

  It is the existing `:podman_compose` output for the design's services, plus
  one service stanza per descriptor-backed part. The generic block is produced
  by `Stapeln.Codegen` rather than re-implemented here, so the stack-shape
  knowledge has one home and cannot drift.

  ## The emitter reads the declaration, never a descriptor

  Every value in a part stanza comes from the record tree `Stapeln.StackDeclaration`
  lowered. If a value is not in the declaration it is not in the bundle. A part
  with an empty `image` is built from `./parts/<name>`; a part with an image is
  pulled at that digest. **The bundle carries no `./parts/<name>` sources** --
  materialising them is the runner's job, and the smoke is where that shows up.

  ## Which stanza wins

  A slot filled by a descriptor-backed part is emitted once, as that part's
  stanza: the part stanza carries the build context, mounts, command,
  environment names and healthcheck that the generic stanza cannot know. Design
  components in every other slot emit generically, unchanged from today.

  ## The one rule that can refuse

  Two services publishing the same host port cannot both bind it, so this
  emitter returns `{:error, reason}` rather than emitting a compose file that
  is guaranteed to fail at run time. v1 has no placement engine (ruling 6) --
  this is the single rule that has teeth, and it fails closed.
  """

  alias Stapeln.{Codegen, Slots, TomlWriter}

  @doc """
  Render `compose.yaml` from the stack and its lowered declaration.
  """
  @spec render(map(), map()) :: {:ok, String.t()} | {:error, String.t()}
  def render(stack, %{parts: parts}) when is_map(stack) do
    descriptor_parts = Enum.filter(parts, &(&1.source == "descriptor"))
    filled = MapSet.new(descriptor_parts, & &1.slot)

    kept =
      stack
      |> Codegen.normalise_services()
      |> Enum.reject(&MapSet.member?(filled, Slots.of_component(service_kind(&1))))

    with :ok <- check_port_conflicts(kept, descriptor_parts),
         {:ok, generic} <- Codegen.generate(with_services(stack, kept), :podman_compose) do
      {:ok, retitle(generic) <> Enum.map_join(descriptor_parts, "", &part_stanza/1)}
    end
  end

  # ---------------------------------------------------------------------------
  # The rule with teeth
  # ---------------------------------------------------------------------------

  defp check_port_conflicts(services, parts) do
    published =
      Enum.map(services, fn svc -> {service_name(svc), Codegen.service_port(svc)} end) ++
        Enum.flat_map(parts, fn part -> Enum.map(part.ports, &{part.name, &1.port}) end)

    conflicts =
      published
      |> Enum.filter(fn {_name, port} -> is_integer(port) and port > 0 end)
      |> Enum.group_by(fn {_name, port} -> port end, fn {name, _port} -> name end)
      |> Enum.filter(fn {_port, names} -> length(Enum.uniq(names)) > 1 end)
      |> Enum.sort_by(fn {port, _names} -> port end)

    case conflicts do
      [] ->
        :ok

      conflicts ->
        detail =
          Enum.map_join(conflicts, "; ", fn {port, names} ->
            "port #{port} is published by #{Enum.join(Enum.sort(Enum.uniq(names)), ", ")}"
          end)

        {:error, "compose.yaml refused: #{detail}. Assign a unique host port to each service."}
    end
  end

  # ---------------------------------------------------------------------------
  # Emission
  # ---------------------------------------------------------------------------

  defp retitle(generic) do
    String.replace(
      generic,
      "# podman-compose.yml generated by stapeln codegen engine",
      "# compose.yaml generated by stapeln codegen engine\n" <>
        "# Design services above; descriptor-backed parts below, from stack.lock."
    )
  end

  defp part_stanza(part) do
    lines =
      ["", "  #{part.name}:"] ++
        source_lines(part) ++
        ports_lines(part) ++
        list_block("volumes", part.mounts) ++
        command_lines(part) ++
        env_lines(part) ++
        healthcheck_lines(part) ++
        ["    restart: unless-stopped"]

    Enum.join(lines, "\n") <> "\n"
  end

  # An empty image means the runner materialises the source and builds it; a
  # non-empty image is a pinned digest and is pulled as-is.
  defp source_lines(%{image: ""} = part) do
    [
      "    build:",
      "      context: ./parts/#{part.name}",
      "      dockerfile: #{part.build.containerfile}"
    ]
  end

  defp source_lines(part), do: ["    image: #{part.image}"]

  defp ports_lines(%{ports: []}), do: []

  defp ports_lines(part) do
    ["    ports:"] ++
      Enum.map(part.ports, fn port ->
        ~s(      - "#{port.port}:#{port.port}/#{port.protocol}") <>
          if(port.transaction == "", do: "", else: "  # #{port.transaction}")
      end)
  end

  defp command_lines(%{command: []}), do: []

  defp command_lines(part) do
    ["    command: [" <> Enum.map_join(part.command, ", ", &TomlWriter.encode_string/1) <> "]"]
  end

  # Names only. A bare name takes the value from the runner's environment, so
  # no secret value is ever written into the bundle.
  defp env_lines(%{env: []}), do: []

  defp env_lines(part) do
    ["    environment:"] ++ Enum.map(part.env, &"      - #{&1}")
  end

  defp healthcheck_lines(%{health: ""}), do: []

  defp healthcheck_lines(part) do
    [
      "    healthcheck:",
      # The probe needs curl in the image; a part whose image has no curl must
      # override this in its own descriptor once v1.1 moves descriptors there.
      ~s(      test: ["CMD-SHELL", "curl -fsS #{part.health} || exit 1"]),
      "      interval: 10s",
      "      timeout: 3s",
      "      retries: 3"
    ]
  end

  defp list_block(_key, []), do: []

  defp list_block(key, values) do
    ["    #{key}:"] ++ Enum.map(values, &"      - #{&1}")
  end

  # A stack may carry its services under either the atom or the string key, and
  # `Codegen.normalise_services/1` reads the atom one FIRST. Putting the filtered
  # list under only the string key therefore leaves the ORIGINAL list in place and
  # the filter is silently discarded -- every descriptor-backed part gets emitted
  # twice, once as a design service and once as a part stanza. Drop both key forms
  # before writing the one that must win.
  defp with_services(stack, services) do
    stack |> Map.delete(:services) |> Map.delete("services") |> Map.put("services", services)
  end

  defp service_kind(service) do
    Map.get(service, :kind, Map.get(service, "kind", "unknown"))
  end

  defp service_name(service), do: Codegen.service_name(service)
end
