# SPDX-License-Identifier: PMPL-1.0-or-later
# Stapeln.PipelineCodegen - Generate container artefacts from assembly pipelines.
#
# Walks the pipeline DAG in topological order and emits deployment artefacts
# in various formats: Containerfile, selur-compose.toml, podman-compose.yml,
# Kubernetes manifests, Helm charts, and OCI bundles.

defmodule Stapeln.PipelineCodegen do
  @moduledoc """
  Generate container artefacts from assembly pipelines.

  Each generator walks the pipeline in topological order, emits the
  appropriate syntax for every node type, and produces valid, runnable
  output. Node IDs are included as comments for traceability.

  Supported output formats:
  - `:containerfile`    — single or multi-stage Containerfile
  - `:selur_compose`    — selur-compose.toml (hyperpolymath format)
  - `:podman_compose`   — podman-compose.yml
  - `:k8s`              — Kubernetes Deployment + Service manifests
  - `:helm`             — Helm chart (Chart.yaml + values.yaml + templates/)
  - `:oci_bundle`       — OCI runtime bundle config.json
  """

  alias Stapeln.PipelineEngine

  @type format ::
          :containerfile
          | :selur_compose
          | :podman_compose
          | :k8s
          | :helm
          | :oci_bundle

  @type codegen_result :: {:ok, String.t() | map()} | {:error, String.t()}

  # ---------------------------------------------------------------------------
  # Public API
  # ---------------------------------------------------------------------------

  @doc "Generate a Containerfile from the pipeline."
  @spec to_containerfile(map()) :: codegen_result()
  def to_containerfile(pipeline) do
    with {:ok, sorted_ids} <- sorted_node_ids(pipeline) do
      nodes = get_nodes(pipeline)
      node_index = index_nodes(nodes)
      metadata = get_metadata(pipeline)
      name = Map.get(metadata, "name", Map.get(metadata, :name, "unnamed-pipeline"))

      header = [
        "# SPDX-License-Identifier: PMPL-1.0-or-later",
        "# Containerfile generated by stapeln pipeline codegen",
        "# Pipeline: #{name}",
        "# Generated: #{DateTime.utc_now() |> DateTime.to_iso8601()}",
        ""
      ]

      body = containerfile_body(sorted_ids, node_index)
      {:ok, Enum.join(header ++ body, "\n") <> "\n"}
    end
  end

  @doc "Generate selur-compose.toml from the pipeline."
  @spec to_selur_compose(map()) :: codegen_result()
  def to_selur_compose(pipeline) do
    with {:ok, sorted_ids} <- sorted_node_ids(pipeline) do
      nodes = get_nodes(pipeline)
      node_index = index_nodes(nodes)
      metadata = get_metadata(pipeline)
      name = Map.get(metadata, "name", Map.get(metadata, :name, "unnamed-pipeline"))

      services = extract_services(sorted_ids, node_index)

      header = [
        "# SPDX-License-Identifier: PMPL-1.0-or-later",
        "# selur-compose.toml generated by stapeln pipeline codegen",
        "# Generated: #{DateTime.utc_now() |> DateTime.to_iso8601()}",
        "",
        "[stack]",
        "name = \"#{name}\"",
        "version = \"1.0\"",
        "runtime = \"podman\"",
        ""
      ]

      service_blocks =
        services
        |> Enum.flat_map(fn svc ->
          lines = [
            "",
            "# Node: #{svc.node_id}",
            "[[services]]",
            "name = \"#{svc.name}\"",
            "type = \"#{svc.type}\"",
            "image = \"#{svc.image}\""
          ]

          lines = if svc.port, do: lines ++ ["port = #{svc.port}"], else: lines

          lines =
            if svc.env != [] do
              env_str = Enum.map_join(svc.env, ", ", fn {k, v} -> "\"#{k}=#{v}\"" end)
              lines ++ ["env = [#{env_str}]"]
            else
              lines
            end

          lines =
            if svc.volumes != [] do
              vol_str = Enum.map_join(svc.volumes, ", ", fn v -> "\"#{v}\"" end)
              lines ++ ["volumes = [#{vol_str}]"]
            else
              lines
            end

          lines
        end)

      {:ok, Enum.join(header ++ service_blocks, "\n") <> "\n"}
    end
  end

  @doc "Generate podman-compose.yml from the pipeline."
  @spec to_podman_compose(map()) :: codegen_result()
  def to_podman_compose(pipeline) do
    with {:ok, sorted_ids} <- sorted_node_ids(pipeline) do
      nodes = get_nodes(pipeline)
      node_index = index_nodes(nodes)
      metadata = get_metadata(pipeline)
      name = Map.get(metadata, "name", Map.get(metadata, :name, "unnamed-pipeline"))

      services = extract_services(sorted_ids, node_index)

      header = [
        "# SPDX-License-Identifier: PMPL-1.0-or-later",
        "# podman-compose.yml generated by stapeln pipeline codegen",
        "# Pipeline: #{name}",
        "# Generated: #{DateTime.utc_now() |> DateTime.to_iso8601()}",
        "",
        "version: '3.8'",
        "",
        "services:"
      ]

      service_blocks =
        services
        |> Enum.flat_map(fn svc ->
          lines = [
            "  # Node: #{svc.node_id}",
            "  #{sanitise_name(svc.name)}:",
            "    image: #{svc.image}"
          ]

          lines = if svc.port, do: lines ++ ["    ports:", "      - \"#{svc.port}:#{svc.port}\""], else: lines

          lines =
            if svc.env != [] do
              env_block = Enum.map(svc.env, fn {k, v} -> "      #{k}: \"#{v}\"" end)
              lines ++ ["    environment:"] ++ env_block
            else
              lines
            end

          lines =
            if svc.volumes != [] do
              vol_block = Enum.map(svc.volumes, fn v -> "      - #{v}" end)
              lines ++ ["    volumes:"] ++ vol_block
            else
              lines
            end

          lines ++ ["    restart: unless-stopped", ""]
        end)

      {:ok, Enum.join(header ++ service_blocks, "\n") <> "\n"}
    end
  end

  @doc "Generate Kubernetes Deployment + Service manifests from the pipeline."
  @spec to_k8s(map()) :: codegen_result()
  def to_k8s(pipeline) do
    with {:ok, sorted_ids} <- sorted_node_ids(pipeline) do
      nodes = get_nodes(pipeline)
      node_index = index_nodes(nodes)
      metadata = get_metadata(pipeline)
      name = Map.get(metadata, "name", Map.get(metadata, :name, "unnamed-pipeline"))

      services = extract_services(sorted_ids, node_index)

      manifests =
        services
        |> Enum.flat_map(fn svc ->
          svc_name = sanitise_name(svc.name)

          deployment = [
            "# Node: #{svc.node_id}",
            "apiVersion: apps/v1",
            "kind: Deployment",
            "metadata:",
            "  name: #{svc_name}",
            "  labels:",
            "    app: #{svc_name}",
            "    pipeline: #{sanitise_name(name)}",
            "spec:",
            "  replicas: 1",
            "  selector:",
            "    matchLabels:",
            "      app: #{svc_name}",
            "  template:",
            "    metadata:",
            "      labels:",
            "        app: #{svc_name}",
            "    spec:",
            "      containers:",
            "        - name: #{svc_name}",
            "          image: #{svc.image}"
          ]

          deployment =
            if svc.port do
              deployment ++ [
                "          ports:",
                "            - containerPort: #{svc.port}"
              ]
            else
              deployment
            end

          deployment =
            if svc.env != [] do
              env_block = Enum.flat_map(svc.env, fn {k, v} ->
                [
                  "            - name: #{k}",
                  "              value: \"#{v}\""
                ]
              end)
              deployment ++ ["          env:"] ++ env_block
            else
              deployment
            end

          # Service manifest (only if port is exposed)
          service_manifest =
            if svc.port do
              [
                "---",
                "apiVersion: v1",
                "kind: Service",
                "metadata:",
                "  name: #{svc_name}",
                "spec:",
                "  selector:",
                "    app: #{svc_name}",
                "  ports:",
                "    - protocol: TCP",
                "      port: #{svc.port}",
                "      targetPort: #{svc.port}",
                "  type: ClusterIP"
              ]
            else
              []
            end

          deployment ++ ["---"] ++ service_manifest ++ [""]
        end)

      header = [
        "# SPDX-License-Identifier: PMPL-1.0-or-later",
        "# Kubernetes manifests generated by stapeln pipeline codegen",
        "# Pipeline: #{name}",
        "# Generated: #{DateTime.utc_now() |> DateTime.to_iso8601()}",
        "---"
      ]

      {:ok, Enum.join(header ++ manifests, "\n") <> "\n"}
    end
  end

  @doc "Generate a Helm chart from the pipeline."
  @spec to_helm(map()) :: codegen_result()
  def to_helm(pipeline) do
    with {:ok, sorted_ids} <- sorted_node_ids(pipeline) do
      nodes = get_nodes(pipeline)
      node_index = index_nodes(nodes)
      metadata = get_metadata(pipeline)
      name = Map.get(metadata, "name", Map.get(metadata, :name, "unnamed-pipeline"))
      chart_name = sanitise_name(name)

      services = extract_services(sorted_ids, node_index)

      chart_yaml = [
        "# SPDX-License-Identifier: PMPL-1.0-or-later",
        "# Generated by stapeln pipeline codegen",
        "apiVersion: v2",
        "name: #{chart_name}",
        "description: Helm chart for #{name} pipeline",
        "type: application",
        "version: 0.1.0",
        "appVersion: \"1.0.0\""
      ] |> Enum.join("\n")

      values_yaml =
        services
        |> Enum.map(fn svc ->
          svc_key = sanitise_name(svc.name)
          lines = [
            "#{svc_key}:",
            "  image: #{svc.image}",
            "  replicas: 1"
          ]

          lines = if svc.port, do: lines ++ ["  port: #{svc.port}"], else: lines

          lines =
            if svc.env != [] do
              env_lines = Enum.map(svc.env, fn {k, v} -> "    #{k}: \"#{v}\"" end)
              lines ++ ["  env:"] ++ env_lines
            else
              lines
            end

          Enum.join(lines, "\n")
        end)
        |> Enum.join("\n\n")

      values_yaml = "# SPDX-License-Identifier: PMPL-1.0-or-later\n# Generated by stapeln pipeline codegen\n\n" <> values_yaml

      # Deployment template (one per service, using values)
      deployment_tpl =
        services
        |> Enum.map(fn svc ->
          svc_key = sanitise_name(svc.name)

          lines = [
            "# Node: #{svc.node_id}",
            "apiVersion: apps/v1",
            "kind: Deployment",
            "metadata:",
            "  name: #{svc_key}",
            "spec:",
            "  replicas: {{ .Values.#{svc_key}.replicas }}",
            "  selector:",
            "    matchLabels:",
            "      app: #{svc_key}",
            "  template:",
            "    metadata:",
            "      labels:",
            "        app: #{svc_key}",
            "    spec:",
            "      containers:",
            "        - name: #{svc_key}",
            "          image: {{ .Values.#{svc_key}.image }}"
          ]

          lines =
            if svc.port do
              lines ++ [
                "          ports:",
                "            - containerPort: {{ .Values.#{svc_key}.port }}"
              ]
            else
              lines
            end

          Enum.join(lines, "\n")
        end)
        |> Enum.join("\n---\n")

      deployment_tpl = "# SPDX-License-Identifier: PMPL-1.0-or-later\n---\n" <> deployment_tpl

      {:ok, %{
        "Chart.yaml" => chart_yaml,
        "values.yaml" => values_yaml,
        "templates/deployment.yaml" => deployment_tpl
      }}
    end
  end

  @doc "Generate an OCI runtime bundle config.json from the pipeline."
  @spec to_oci_bundle(map()) :: codegen_result()
  def to_oci_bundle(pipeline) do
    with {:ok, sorted_ids} <- sorted_node_ids(pipeline) do
      nodes = get_nodes(pipeline)
      node_index = index_nodes(nodes)
      metadata = get_metadata(pipeline)

      # Collect environment, exposed ports, working directory
      env_vars = collect_env_vars(sorted_ids, node_index)
      exposed_ports = collect_exposed_ports(sorted_ids, node_index)
      workdir = find_workdir(sorted_ids, node_index)
      entrypoint = find_entrypoint(sorted_ids, node_index)

      config = %{
        "ociVersion" => "1.0.2",
        "process" => %{
          "terminal" => false,
          "user" => %{"uid" => 65534, "gid" => 65534},
          "args" => entrypoint,
          "env" => Enum.map(env_vars, fn {k, v} -> "#{k}=#{v}" end),
          "cwd" => workdir
        },
        "root" => %{
          "path" => "rootfs",
          "readonly" => false
        },
        "hostname" => Map.get(metadata, "name", Map.get(metadata, :name, "stapeln-container")),
        "mounts" => [
          %{"destination" => "/proc", "type" => "proc", "source" => "proc"},
          %{"destination" => "/dev", "type" => "tmpfs", "source" => "tmpfs",
            "options" => ["nosuid", "strictatime", "mode=755", "size=65536k"]},
          %{"destination" => "/sys", "type" => "sysfs", "source" => "sysfs",
            "options" => ["nosuid", "noexec", "nodev", "ro"]}
        ],
        "linux" => %{
          "namespaces" => [
            %{"type" => "pid"},
            %{"type" => "network"},
            %{"type" => "ipc"},
            %{"type" => "uts"},
            %{"type" => "mount"}
          ]
        },
        "annotations" => Map.merge(%{
          "com.hyperpolymath.stapeln.generated" => DateTime.utc_now() |> DateTime.to_iso8601(),
          "com.hyperpolymath.stapeln.pipeline" => Map.get(metadata, "name", Map.get(metadata, :name, ""))
        }, if(exposed_ports != [], do: %{
          "com.hyperpolymath.stapeln.ports" => Enum.join(exposed_ports, ",")
        }, else: %{}))
      }

      {:ok, Jason.encode!(config, pretty: true)}
    end
  end

  # ---------------------------------------------------------------------------
  # Containerfile body generation
  # ---------------------------------------------------------------------------

  defp containerfile_body(sorted_ids, node_index) do
    sorted_ids
    |> Enum.flat_map(fn id ->
      node = Map.fetch!(node_index, id)
      containerfile_node(id, node)
    end)
  end

  defp containerfile_node(id, node) do
    config = node_config(node)

    case node_type(node) do
      "source" ->
        image = config_value(config, "image") || "cgr.dev/chainguard/wolfi-base:latest"
        alias_name = config_value(config, "alias") || config_value(config, "as") || sanitise_name(id)
        [
          "# [#{id}] Source stage",
          "FROM #{image} AS #{alias_name}",
          ""
        ]

      "run" ->
        commands = config_value(config, "commands") || config_value(config, "command") || []
        commands = if is_list(commands), do: commands, else: [commands]

        if commands == [] do
          []
        else
          merged = Enum.join(commands, " && \\\n    ")
          [
            "# [#{id}] Run commands",
            "RUN #{merged}",
            ""
          ]
        end

      "copy" ->
        src = config_value(config, "src") || config_value(config, "source") || "."
        dst = config_value(config, "dst") || config_value(config, "dest") || config_value(config, "destination") || "."
        from_stage = config_value(config, "from")
        chown = config_value(config, "chown")

        flags = []
        flags = if from_stage, do: flags ++ ["--from=#{from_stage}"], else: flags
        flags = if chown, do: flags ++ ["--chown=#{chown}"], else: flags
        flag_str = if flags != [], do: " " <> Enum.join(flags, " "), else: ""

        [
          "# [#{id}] Copy files",
          "COPY#{flag_str} #{src} #{dst}",
          ""
        ]

      "env" ->
        key = config_value(config, "key") || config_value(config, "name") || "UNKNOWN"
        value = config_value(config, "value") || ""
        [
          "# [#{id}] Environment variable",
          "ENV #{key}=#{inspect(value)}",
          ""
        ]

      "expose" ->
        port = config_value(config, "port") || 8080
        protocol = config_value(config, "protocol") || "tcp"
        [
          "# [#{id}] Expose port",
          "EXPOSE #{port}/#{protocol}",
          ""
        ]

      "workdir" ->
        path = config_value(config, "path") || "/app"
        [
          "# [#{id}] Working directory",
          "WORKDIR #{path}",
          ""
        ]

      "label" ->
        key = config_value(config, "key") || config_value(config, "name") || ""
        value = config_value(config, "value") || ""
        [
          "# [#{id}] Label",
          "LABEL #{key}=\"#{value}\"",
          ""
        ]

      "volume" ->
        path = config_value(config, "path") || config_value(config, "mount") || "/data"
        [
          "# [#{id}] Volume",
          "VOLUME #{path}",
          ""
        ]

      "security_gate" ->
        scan_tool = config_value(config, "tool") || "trivy"
        severity = config_value(config, "severity") || "HIGH,CRITICAL"
        [
          "# [#{id}] Security gate (#{scan_tool}, threshold: #{severity})",
          "# Pipeline will halt here if scan fails",
          ""
        ]

      "push" ->
        registry = config_value(config, "registry") || config_value(config, "target") || ""
        tag = config_value(config, "tag") || "latest"
        [
          "# [#{id}] Push target: #{registry}:#{tag}",
          "# podman push $IMAGE #{registry}:#{tag}",
          ""
        ]

      _ ->
        ["# [#{id}] Unknown node type: #{node_type(node)}", ""]
    end
  end

  # ---------------------------------------------------------------------------
  # Service extraction (for compose/k8s/helm formats)
  # ---------------------------------------------------------------------------

  defp extract_services(sorted_ids, node_index) do
    # Group nodes by their source stage. Each source node starts a service.
    # If there are no source nodes, synthesise one service from all nodes.
    source_ids = sorted_ids |> Enum.filter(fn id ->
      node = Map.get(node_index, id)
      node_type(node) == "source"
    end)

    if source_ids == [] do
      # Fallback: one service from all nodes
      [build_service_from_nodes("service", sorted_ids, node_index)]
    else
      source_ids
      |> Enum.map(fn source_id ->
        source_node = Map.fetch!(node_index, source_id)
        config = node_config(source_node)
        svc_name = config_value(config, "alias") || config_value(config, "as") || sanitise_name(source_id)
        image = config_value(config, "image") || "cgr.dev/chainguard/wolfi-base:latest"

        # Collect downstream nodes that belong to this source's stage
        downstream = collect_downstream(source_id, sorted_ids, node_index)
        all_ids = [source_id | downstream]

        svc = build_service_from_nodes(svc_name, all_ids, node_index)
        %{svc | image: image, node_id: source_id}
      end)
    end
  end

  defp build_service_from_nodes(name, node_ids, node_index) do
    env_vars = collect_env_vars(node_ids, node_index)
    ports = collect_exposed_ports(node_ids, node_index)
    volumes = collect_volumes(node_ids, node_index)

    %{
      name: name,
      node_id: List.first(node_ids) || "unknown",
      type: "web",
      image: "cgr.dev/chainguard/wolfi-base:latest",
      port: List.first(ports),
      env: env_vars,
      volumes: volumes
    }
  end

  defp collect_downstream(source_id, sorted_ids, node_index) do
    # Simple heuristic: collect all non-source nodes that come after this source
    # in topological order, until the next source node.
    sorted_ids
    |> Enum.drop_while(fn id -> id != source_id end)
    |> Enum.drop(1)
    |> Enum.take_while(fn id ->
      node = Map.get(node_index, id)
      node_type(node) != "source"
    end)
  end

  # ---------------------------------------------------------------------------
  # Collectors for OCI bundle and service extraction
  # ---------------------------------------------------------------------------

  defp collect_env_vars(node_ids, node_index) do
    node_ids
    |> Enum.flat_map(fn id ->
      node = Map.get(node_index, id)
      if node && node_type(node) == "env" do
        config = node_config(node)
        key = config_value(config, "key") || config_value(config, "name")
        value = config_value(config, "value") || ""
        if key, do: [{key, value}], else: []
      else
        []
      end
    end)
  end

  defp collect_exposed_ports(node_ids, node_index) do
    node_ids
    |> Enum.flat_map(fn id ->
      node = Map.get(node_index, id)
      if node && node_type(node) == "expose" do
        config = node_config(node)
        port = config_value(config, "port")
        if port, do: [port], else: []
      else
        []
      end
    end)
  end

  defp collect_volumes(node_ids, node_index) do
    node_ids
    |> Enum.flat_map(fn id ->
      node = Map.get(node_index, id)
      if node && node_type(node) == "volume" do
        config = node_config(node)
        path = config_value(config, "path") || config_value(config, "mount")
        if path, do: [path], else: []
      else
        []
      end
    end)
  end

  defp find_workdir(node_ids, node_index) do
    # Last WORKDIR wins
    node_ids
    |> Enum.reverse()
    |> Enum.find_value("/app", fn id ->
      node = Map.get(node_index, id)
      if node && node_type(node) == "workdir" do
        config_value(node_config(node), "path")
      else
        nil
      end
    end)
  end

  defp find_entrypoint(node_ids, node_index) do
    # Look for a run node with an "entrypoint" config, otherwise default
    node_ids
    |> Enum.reverse()
    |> Enum.find_value(["/bin/sh"], fn id ->
      node = Map.get(node_index, id)
      if node do
        config = node_config(node)
        ep = config_value(config, "entrypoint")
        if ep do
          if is_list(ep), do: ep, else: [ep]
        else
          nil
        end
      else
        nil
      end
    end)
  end

  # ---------------------------------------------------------------------------
  # Shared helpers
  # ---------------------------------------------------------------------------

  defp sorted_node_ids(pipeline) do
    nodes = get_nodes(pipeline)
    connections = get_connections(pipeline)

    if nodes == [] do
      {:error, "pipeline has no nodes"}
    else
      PipelineEngine.topological_sort(nodes, connections)
    end
  end

  defp get_nodes(pipeline) do
    case Map.get(pipeline, "nodes", Map.get(pipeline, :nodes, [])) do
      list when is_list(list) -> list
      _ -> []
    end
  end

  defp get_connections(pipeline) do
    case Map.get(pipeline, "connections", Map.get(pipeline, :connections, [])) do
      list when is_list(list) -> list
      _ -> []
    end
  end

  defp get_metadata(pipeline) do
    Map.get(pipeline, "metadata", Map.get(pipeline, :metadata, %{}))
  end

  defp index_nodes(nodes) do
    Map.new(nodes, fn n -> {node_id(n), n} end)
  end

  defp node_id(node), do: Map.get(node, "id", Map.get(node, :id, ""))
  defp node_type(node), do: Map.get(node, "type", Map.get(node, :type, ""))
  defp node_config(node), do: Map.get(node, "config", Map.get(node, :config, %{}))

  defp config_value(config, key) when is_map(config) do
    Map.get(config, key, Map.get(config, String.to_atom(key), nil))
  end

  defp config_value(_, _), do: nil

  defp sanitise_name(name) do
    name
    |> to_string()
    |> String.downcase()
    |> String.replace(~r/[^a-z0-9_-]/, "-")
    |> String.trim("-")
    |> case do
      "" -> "service"
      n -> n
    end
  end
end
