# SPDX-License-Identifier: MPL-2.0
defmodule Stapeln.StackLockCheck do
  @moduledoc """
  The structural assertions that carry `stack.lock`.

  These live in one module because the spec requires the same assertions to run
  in two places: stapeln's contract test (`stack_declaration_test.exs`) and the
  smoke, as `mix stapeln.bundle --check out/bundle/stack.lock`. Two copies would
  drift, and the copy that drifts is always the one the gate runs.

  **This is the only thing carrying slot completeness in v1**, and it stays when
  the deed grammar lands. It claims no estate validator gate: `validate-a2ml.sh`
  without `INPUT_STRICT=true` reports identity as a warning and exits 0, and
  this file is not its input in any case.

  The file is decoded with a real TOML decoder, not with a stapeln parser, so a
  malformed emission fails here rather than round-tripping through a bug shared
  by emitter and reader.
  """

  alias Stapeln.Slots

  @sha_re ~r/\A[0-9a-f]{40}\z/
  @design_sha_re ~r/\A sha256:[0-9a-f]{64}\z/x

  @doc """
  Check `contents`. Pass `design_bytes` to also verify `design_sha256` against
  the design that shipped beside it.
  """
  @spec check(binary(), binary() | nil) :: :ok | {:error, String.t()}
  def check(contents, design_bytes \\ nil) when is_binary(contents) do
    with :ok <- check_header(contents),
         {:ok, doc} <- decode(contents),
         :ok <- check_tables(doc),
         :ok <- check_slots(doc),
         :ok <- check_parts(doc),
         :ok <- check_design_sha(doc, design_bytes) do
      :ok
    end
  end

  # The header is a load-bearing claim, not a comment: it is where the file says
  # it is stapeln's own and not an estate document.
  defp check_header(contents) do
    head = contents |> String.split("\n") |> Enum.take(6) |> Enum.join("\n")

    cond do
      not String.contains?(head, "generated by stapeln") ->
        {:error, "header must say the file is generated by stapeln"}

      not String.contains?(head, "Not an A2ML or .deed document") ->
        {:error, "header must state the file is not an A2ML or .deed document"}

      String.contains?(contents, "@profile") ->
        {:error, "stack.lock carries no @profile line and claims no conformance class"}

      true ->
        :ok
    end
  end

  defp decode(contents) do
    case Toml.decode(contents) do
      {:ok, doc} -> {:ok, doc}
      {:error, reason} -> {:error, "does not decode as TOML: #{inspect(reason)}"}
    end
  end

  defp check_tables(doc) do
    missing = Enum.reject(~w(stack slots part), &Map.has_key?(doc, &1))

    case missing do
      [] -> :ok
      missing -> {:error, "missing table(s): #{Enum.join(missing, ", ")}"}
    end
  end

  defp check_slots(doc) do
    slots = Map.fetch!(doc, "slots")
    expected = Slots.keys()

    missing = expected -- Map.keys(slots)
    extra = Map.keys(slots) -- expected

    cond do
      missing != [] ->
        {:error, "[slots] is missing #{length(missing)} key(s): #{Enum.join(Enum.sort(missing), ", ")}"}

      extra != [] ->
        {:error, "[slots] has unknown key(s): #{Enum.join(Enum.sort(extra), ", ")}"}

      not Enum.all?(Map.values(slots), &is_binary/1) ->
        {:error, "[slots] values must all be strings"}

      true ->
        :ok
    end
  end

  defp check_parts(doc) do
    doc
    |> Map.fetch!("part")
    |> List.wrap()
    |> Enum.reduce_while(:ok, fn part, :ok ->
      name = Map.get(part, "name", "<unnamed>")

      cond do
        not Slots.slot?(Map.get(part, "slot")) ->
          {:halt, {:error, "part #{name}: slot #{inspect(Map.get(part, "slot"))} is not in the slot table"}}

        not (is_binary(Map.get(part, "sha")) and Regex.match?(@sha_re, Map.get(part, "sha"))) ->
          {:halt, {:error, "part #{name}: sha must be 40 lowercase hex characters"}}

        Map.get(part, "verified") != false ->
          {:halt, {:error, "part #{name}: verified must be false in v1 -- nothing verifies parts yet"}}

        true ->
          {:cont, :ok}
      end
    end)
  end

  defp check_design_sha(doc, design_bytes) do
    actual = doc |> Map.fetch!("stack") |> Map.get("design_sha256")

    cond do
      not (is_binary(actual) and Regex.match?(@design_sha_re, actual)) ->
        {:error, "stack.design_sha256 must be sha256:<64 hex>, got #{inspect(actual)}"}

      is_nil(design_bytes) ->
        :ok

      true ->
        expected = "sha256:" <> Base.encode16(:crypto.hash(:sha256, design_bytes), case: :lower)

        if actual == expected do
          :ok
        else
          {:error, "stack.design_sha256 #{actual} does not match the design beside it (#{expected})"}
        end
    end
  end
end
