# SPDX-License-Identifier: MPL-2.0
defmodule Stapeln.StackDeclaration do
  @moduledoc """
  File 11 of the bundle: `stack.lock`, the stapeln-owned stack declaration.

  `stack.lock` is the generated, pinned lock file named by ruling 2, in the
  role `Cargo.lock` plays for a crate: a TOML lock file nobody mistakes for a
  manifest. **It is not an A2ML document and not a `.deed`**, it carries no
  `@profile`, claims no conformance class, and no `a2ml validate` step checks
  it. Its own header says so. When the `.deed` grammar lands, the same record
  tree is emitted in the head form that grammar defines; `stack.lock` stays the
  pin record for as long as a consumer reads it. stapeln invents no grammar.

  ## Two stages, and why the split matters

  `lower/3` takes the design and the descriptor catalogue and produces a plain
  record tree. `encode/1` takes that tree and produces bytes. No emitter reads
  a descriptor: **if a value is not in the declaration, it is not in the
  bundle.** That is what makes the record tree, rather than this module, the
  thing that migrates to the deed form.

  ## Naming, and what happens when a slot is over-filled

  A part backed by a descriptor takes the descriptor's name. A part the
  catalogue does not know is recorded `source = "design-only"` and takes its
  component type downcased, which is what the slot table calls it -- so a
  placed Podman is the part `podman` in slot `runtime`.

  Design-only parts are deduplicated by `{slot, name}`: two identical Podman
  components on one canvas are one runtime part, not two identical records.
  Two *different* parts in a max-1 slot both emit -- v1 has no placement engine
  (ruling 6) -- and `[slots]`, which is single-valued, names the first in
  canvas order while `[[part]]` carries both. The port-conflict rule in
  `Stapeln.ComposeYaml` is what refuses the run.
  """

  alias Stapeln.{Codegen, Parts, Slots, TomlWriter}

  @schema 1
  @compose_format "compose-v3.8"

  @header """
  # SPDX-License-Identifier: MPL-2.0
  # stack.lock: generated by stapeln; do not edit.
  # Not an A2ML or .deed document: stapeln's own lock file. The stack declaration
  # migrates to the estate .deed form when that grammar lands.
  """

  @doc "The header every `stack.lock` carries, naming the file as stapeln's own."
  @spec header() :: String.t()
  def header, do: @header

  @doc """
  Lower a design plus the descriptor catalogue into the record tree.

  `design_bytes` are the exact bytes of the emitted `stapeln.design.json`, so
  `design_sha256` pins the design that actually shipped in this bundle rather
  than a re-serialisation of it.
  """
  @spec lower(map(), binary(), keyword()) :: map()
  def lower(stack, design_bytes, opts \\ []) when is_map(stack) and is_binary(design_bytes) do
    catalogue = Keyword.get_lazy(opts, :catalogue, &Parts.load!/0)
    by_component = index_by_component(catalogue)

    parts =
      stack
      |> Codegen.normalise_services()
      |> Enum.map(&part_record(&1, by_component))
      |> dedupe_design_only()

    %{
      stack: %{
        schema: @schema,
        name: stack_name(stack),
        generator: generator(),
        generated: Keyword.get_lazy(opts, :generated, &now/0),
        design_sha256: "sha256:" <> Base.encode16(:crypto.hash(:sha256, design_bytes), case: :lower),
        compose_format: @compose_format
      },
      slots: slot_table(parts),
      parts: parts
    }
  end

  @doc """
  Serialise a record tree to `stack.lock` bytes.
  """
  @spec encode(map()) :: String.t()
  def encode(%{stack: stack, slots: slots, parts: parts}) do
    [
      @header,
      "\n[stack]\n",
      ordered_pairs(stack, [:schema, :name, :generator, :generated, :design_sha256, :compose_format]),
      "\n# every slot, always; \"\" = empty\n[slots]\n",
      Enum.map_join(Slots.keys(), "\n", fn key ->
        TomlWriter.encode_pair(key, Map.fetch!(slots, key))
      end),
      "\n",
      Enum.map_join(parts, "", &encode_part/1)
    ]
    |> IO.iodata_to_binary()
  end

  @doc """
  Lower and encode in one step.
  """
  @spec render(map(), binary(), keyword()) :: String.t()
  def render(stack, design_bytes, opts \\ []) do
    stack |> lower(design_bytes, opts) |> encode()
  end

  # ---------------------------------------------------------------------------
  # Lowering
  # ---------------------------------------------------------------------------

  defp index_by_component(catalogue) do
    catalogue
    |> Map.values()
    |> Enum.reject(&(&1.model_component == ""))
    |> Map.new(&{&1.model_component, &1})
  end

  defp part_record(service, by_component) do
    component = service_kind(service)

    case Map.get(by_component, component) do
      nil -> design_only_part(component)
      descriptor -> descriptor_part(descriptor)
    end
  end

  defp design_only_part(component) do
    %{
      slot: Slots.of_component(component),
      name: String.downcase(component),
      source: "design-only",
      interface: "oci",
      repo: "",
      sha: String.duplicate("0", 40),
      image: "",
      build: %{containerfile: "Containerfile", context: "."},
      ports: [],
      mounts: [],
      command: [],
      env: [],
      consumes: [],
      health: "",
      manifest_url: "",
      verified: false
    }
  end

  defp descriptor_part(descriptor) do
    %{
      slot: descriptor.slot,
      name: descriptor.name,
      source: "descriptor",
      interface: descriptor.interface,
      repo: descriptor.repo,
      sha: descriptor.sha,
      image: descriptor.image,
      build: %{
        containerfile: descriptor.build.containerfile,
        context: descriptor.build.context
      },
      ports: Enum.map(descriptor.ports, &Map.take(&1, [:port, :protocol, :transaction])),
      mounts: descriptor.mounts,
      command: descriptor.command,
      env: descriptor.env,
      consumes: descriptor.consumes,
      health: health_url(descriptor),
      manifest_url: descriptor.manifest_url,
      # Always false in v1: nothing verifies parts until vordr or cerro-torre
      # consume the declaration (v1.1+). A gate that cannot fail is not a gate,
      # so this records the absence rather than asserting a verification.
      verified: false
    }
  end

  # The descriptor carries `health = { path, port }`; the declaration carries
  # the URL a runner can probe. Composing it is a lowering step, which is why
  # the emitters never need the descriptor.
  defp health_url(%{health: nil}), do: ""

  defp health_url(%{health: %{path: path, port: port}, name: name}) do
    "http://#{name}:#{port}#{path}"
  end

  defp dedupe_design_only(parts) do
    {kept, _seen} =
      Enum.reduce(parts, {[], MapSet.new()}, fn part, {kept, seen} ->
        key = {part.slot, part.name}

        cond do
          part.source == "descriptor" -> {[part | kept], seen}
          MapSet.member?(seen, key) -> {kept, seen}
          true -> {[part | kept], MapSet.put(seen, key)}
        end
      end)

    Enum.reverse(kept)
  end

  # Every slot key is present even when empty, so a consumer reading the table
  # sees a missing part as `""` rather than as an absent key. This is what the
  # designer shows as a missing part -- the firewall slot in v1, for instance.
  defp slot_table(parts) do
    occupied =
      Enum.reduce(parts, %{}, fn part, acc ->
        Map.put_new(acc, part.slot, part.name)
      end)

    Map.new(Slots.keys(), fn key -> {key, Map.get(occupied, key, "")} end)
  end

  # ---------------------------------------------------------------------------
  # Encoding
  # ---------------------------------------------------------------------------

  defp encode_part(part) do
    keys = [
      :slot,
      :name,
      :source,
      :interface,
      :repo,
      :sha,
      :image,
      :build,
      :ports,
      :mounts,
      :command,
      :env,
      :consumes,
      :health,
      :manifest_url,
      :verified
    ]

    "\n[[part]]\n" <> ordered_pairs(part, keys)
  end

  defp ordered_pairs(map, keys) do
    Enum.map_join(keys, "", fn key ->
      TomlWriter.encode_pair(key, Map.fetch!(map, key)) <> "\n"
    end)
  end

  # ---------------------------------------------------------------------------
  # Small helpers
  # ---------------------------------------------------------------------------

  defp service_kind(service) do
    Map.get(service, :kind, Map.get(service, "kind", "unknown"))
  end

  defp stack_name(stack) do
    Map.get(stack, :name, Map.get(stack, "name", "stack"))
  end

  defp generator do
    version =
      case Application.spec(:stapeln, :vsn) do
        nil -> "unknown"
        vsn -> List.to_string(vsn)
      end

    "stapeln #{version}"
  end

  defp now do
    DateTime.utc_now() |> DateTime.truncate(:second) |> DateTime.to_iso8601()
  end
end
