# SPDX-License-Identifier: MPL-2.0
# OLS listeners — HTTP redirect + HTTPS with HTTP/3

listener HTTP {
  address                 *:80
  secure                  0
  map                     svalinn *
}

listener HTTPS {
  address                 *:443
  secure                  1
  map                     svalinn *
  keyFile                 /etc/letsencrypt/live/svalinn/privkey.pem
  certFile                /etc/letsencrypt/live/svalinn/fullchain.pem
  certChain               1
  sslProtocol             24
  enableSpdy              15
  enableQuic              1
}
