# SPDX-License-Identifier: MPL-2.0

defmodule Stapeln.StackDeclarationTest do
  @moduledoc """
  The contract test named by the ecosystem spec.

  It decodes `stack.lock` with a real TOML decoder -- not with a stapeln parser
  -- so the gate is not stapeln checking its own emitter with its own reader.
  This test is the only thing carrying slot completeness in v1.
  """

  use ExUnit.Case, async: true

  import ExUnit.CaptureIO

  alias Stapeln.{BundleCodegen, ComposeYaml, Parts, Slots, StackDeclaration, StackLockCheck}

  @required [author: "A. Author", email: "a@example.org", license: "MPL-2.0", owner: "acme"]

  # A canvas carrying both v1 consumers plus a runtime and a part the catalogue
  # does not know, so the fixture exercises the descriptor path, the
  # design-only path and an empty slot at once.
  @stack %{
    name: "demo",
    design: %{"components" => [], "connections" => []},
    services: [
      %{"name" => "gate-1", "kind" => "Rokur", "port" => 0},
      %{"name" => "edge-1", "kind" => "Svalinn", "port" => 0},
      %{"name" => "rt-1", "kind" => "Podman", "port" => 0},
      %{"name" => "mystery-1", "kind" => "SomethingElse", "port" => 0}
    ]
  }

  defp bundle, do: elem(BundleCodegen.generate(@stack, @required), 1)

  defp decoded do
    Toml.decode!(bundle()["stack.lock"])
  end

  describe "stack.lock structure (the spec's contract test)" do
    test "decodes with a real TOML decoder" do
      assert {:ok, doc} = Toml.decode(bundle()["stack.lock"])
      assert is_map(doc)
    end

    test "the three tables are present" do
      doc = decoded()

      assert is_map(doc["stack"])
      assert is_map(doc["slots"])
      assert is_list(doc["part"])
    end

    test "all twelve slot keys are present, even when empty" do
      slots = decoded()["slots"]

      assert length(Slots.keys()) == 12
      assert Enum.sort(Map.keys(slots)) == Enum.sort(Slots.keys())

      # The firewall slot has no part in v1; the designer shows it as missing,
      # which is an empty string rather than an absent key.
      assert slots["firewall"] == ""
      assert slots["secrets-gate"] == "rokur"
      assert slots["edge-gateway"] == "svalinn"
      assert slots["runtime"] == "podman"
    end

    test "every part's slot is in the slot table" do
      for part <- decoded()["part"] do
        assert Slots.slot?(part["slot"]), "#{part["name"]} has slot #{inspect(part["slot"])}"
      end
    end

    test "every sha is 40 hex" do
      for part <- decoded()["part"] do
        assert part["sha"] =~ ~r/\A[0-9a-f]{40}\z/, "#{part["name"]} sha #{inspect(part["sha"])}"
      end
    end

    test "design_sha256 is the hash of the design that shipped in the same bundle" do
      files = bundle()

      expected =
        "sha256:" <>
          Base.encode16(:crypto.hash(:sha256, files["stapeln.design.json"]), case: :lower)

      assert Toml.decode!(files["stack.lock"])["stack"]["design_sha256"] == expected
    end

    test "the header names the file as stapeln's own, and not A2ML or deed" do
      lock = bundle()["stack.lock"]

      assert lock =~ "generated by stapeln"
      assert lock =~ "Not an A2ML or .deed document"
      refute lock =~ "@profile"
    end

    test "verified is false on every part in v1" do
      for part <- decoded()["part"] do
        assert part["verified"] == false
      end
    end

    test "StackLockCheck agrees, and is what --check runs" do
      files = bundle()
      assert :ok = StackLockCheck.check(files["stack.lock"], files["stapeln.design.json"])
    end
  end

  describe "StackLockCheck rejects what it must" do
    test "a missing slot key" do
      broken = String.replace(bundle()["stack.lock"], ~s(firewall = ""\n), "")
      assert {:error, reason} = StackLockCheck.check(broken)
      assert reason =~ "missing 1 key(s): firewall"
    end

    test "a sha that is not 40 hex" do
      broken =
        String.replace(bundle()["stack.lock"], String.duplicate("0", 40), "not-a-sha", global: false)

      assert {:error, reason} = StackLockCheck.check(broken)
      assert reason =~ "40 lowercase hex"
    end

    test "a header that drops the not-A2ML claim" do
      broken = String.replace(bundle()["stack.lock"], "Not an A2ML or .deed document", "A2ML v1")
      assert {:error, reason} = StackLockCheck.check(broken)
      assert reason =~ "not an A2ML or .deed document"
    end

    test "a @profile line, which this file never carries" do
      broken = bundle()["stack.lock"] <> "\n@profile = \"stapeln/stack\"\n"
      assert {:error, reason} = StackLockCheck.check(broken)
      assert reason =~ "@profile"
    end

    test "a design_sha256 that does not match the design beside it" do
      files = bundle()
      assert {:error, reason} = StackLockCheck.check(files["stack.lock"], "different bytes")
      assert reason =~ "does not match the design beside it"
    end

    test "the check can fail -- a gate that cannot fail is not a gate" do
      assert {:error, _} = StackLockCheck.check("not toml at all {{")
    end
  end

  describe "lowering" do
    test "a descriptor-backed part carries the descriptor's pinned values" do
      rokur = Enum.find(decoded()["part"], &(&1["name"] == "rokur"))

      assert rokur["source"] == "descriptor"
      assert rokur["interface"] == "oci"
      assert rokur["repo"] == "https://github.com/metadatastician/rokur"
      assert rokur["consumes"] == ["rokur.toml"]
      assert rokur["command"] == ["--config", "/app/rokur.toml"]
      assert rokur["env"] == ["ROKUR_API_TOKEN", "ROKUR_REQUIRED_SECRETS"]
      assert [%{"port" => 9090, "protocol" => "tcp"}] = rokur["ports"]
      assert rokur["build"] == %{"containerfile" => "Containerfile", "context" => "."}
    end

    test "the descriptor's health table lowers to a URL the runner can probe" do
      rokur = Enum.find(decoded()["part"], &(&1["name"] == "rokur"))
      assert rokur["health"] == "http://rokur:9090/health"
    end

    test "a part the catalogue does not know is recorded design-only, not dropped" do
      mystery = Enum.find(decoded()["part"], &(&1["name"] == "somethingelse"))

      assert mystery["source"] == "design-only"
      assert mystery["slot"] == Slots.custom()
      assert mystery["repo"] == ""
    end

    test "identical design-only components collapse to one part record" do
      stack = put_in(@stack.services, [
        %{"name" => "rt-1", "kind" => "Podman", "port" => 0},
        %{"name" => "rt-2", "kind" => "Podman", "port" => 0}
      ])

      {:ok, files} = BundleCodegen.generate(stack, @required)
      parts = Toml.decode!(files["stack.lock"])["part"]

      assert length(Enum.filter(parts, &(&1["name"] == "podman"))) == 1
    end

    test "two different parts in a max-1 slot both emit; [slots] names the first" do
      stack = put_in(@stack.services, [
        %{"name" => "rt-1", "kind" => "Podman", "port" => 0},
        %{"name" => "rt-2", "kind" => "Docker", "port" => 0}
      ])

      {:ok, files} = BundleCodegen.generate(stack, @required)
      doc = Toml.decode!(files["stack.lock"])

      runtime_parts = Enum.filter(doc["part"], &(&1["slot"] == "runtime"))
      assert length(runtime_parts) == 2
      assert doc["slots"]["runtime"] == "podman"
    end

    test "a stack name that would inject TOML is rejected, not escaped" do
      hostile = put_in(@stack.name, ~s(demo"\ninjected = true))

      assert_raise ArgumentError, ~r/cannot be emitted into TOML/, fn ->
        BundleCodegen.generate(hostile, @required)
      end
    end
  end

  describe "compose.yaml" do
    # Every other assertion in this block is a substring match, which is the same
    # circular gate `stack.lock` avoids by decoding with a real TOML decoder --
    # a substring cannot see indentation drift, a duplicate key, or a value YAML
    # reads as a bool. There is no YAML decoder in this app's deps and adding one
    # to pin a single test is not worth the supply-chain surface, so the emitted
    # file was parsed once out-of-band with a real reader (`ruby -ryaml`) and this
    # test pins the SET of service keys that reader saw.
    #
    # The set is also the durable regression test for the atom-vs-string services
    # key bug: `refute compose =~ "  gate-1:"` only catches the double emission
    # while that component happens to be called `gate-1`, whereas the set is
    # wrong for any name.
    test "the service key set is exactly the kept design services plus the parts" do
      # gate-1 and edge-1 lower to descriptor-backed parts and must NOT also
      # appear under their design names; rt-1 and mystery-1 have no descriptor
      # and stay as design services.
      assert compose_service_keys() == ["mystery-1", "rokur", "rt-1", "svalinn"]
    end

    test "a part with no image is built from ./parts/<name>" do
      compose = bundle()["compose.yaml"]

      assert compose =~ "  rokur:"
      assert compose =~ "      context: ./parts/rokur"
      assert compose =~ "      dockerfile: Containerfile"
    end

    test "a part with an image is pulled at that digest, not built" do
      declaration = StackDeclaration.lower(@stack, "design-bytes")

      pinned =
        update_in(declaration.parts, fn parts ->
          Enum.map(parts, fn
            %{name: "rokur"} = p -> %{p | image: "ghcr.io/metadatastician/rokur@sha256:" <> String.duplicate("a", 64)}
            p -> p
          end)
        end)

      {:ok, compose} = ComposeYaml.render(@stack, pinned)

      assert compose =~ "    image: ghcr.io/metadatastician/rokur@sha256:"
      refute compose =~ "context: ./parts/rokur"
    end

    test "environment carries names only -- no secret value reaches the bundle" do
      compose = bundle()["compose.yaml"]

      assert compose =~ "      - ROKUR_API_TOKEN"
      refute compose =~ "ROKUR_API_TOKEN="
      refute compose =~ "ROKUR_API_TOKEN:"
    end

    test "the healthcheck comes from the declaration's health URL" do
      assert bundle()["compose.yaml"] =~ "curl -fsS http://rokur:9090/health"
    end

    test "the consumed file is mounted read-only" do
      assert bundle()["compose.yaml"] =~ "      - ./rokur.toml:/app/rokur.toml:ro,Z"
    end

    test "a slot filled by a descriptor part is emitted once, not twice" do
      compose = bundle()["compose.yaml"]

      assert length(String.split(compose, "  rokur:")) == 2
      refute compose =~ "  gate-1:"
    end

    test "two services publishing the same host port refuse the file" do
      stack = put_in(@stack.services, [
        %{"name" => "gate-1", "kind" => "Rokur", "port" => 0},
        %{"name" => "clash", "kind" => "SomethingElse", "port" => 9090}
      ])

      declaration = StackDeclaration.lower(stack, "design-bytes")

      assert {:error, reason} = ComposeYaml.render(stack, declaration)
      assert reason =~ "port 9090 is published by"
      assert reason =~ "clash"
      assert reason =~ "rokur"
    end

    test "the refusal propagates -- the bundle fails closed rather than emitting" do
      stack = put_in(@stack.services, [
        %{"name" => "gate-1", "kind" => "Rokur", "port" => 0},
        %{"name" => "clash", "kind" => "SomethingElse", "port" => 9090}
      ])

      assert {:error, reason} = BundleCodegen.generate(stack, @required)
      assert reason =~ "compose.yaml refused"
    end
  end

  describe "the slot table" do
    test "thirteen ids, twelve keys, and custom is the excluded one" do
      assert length(Slots.ids()) == 13
      assert length(Slots.keys()) == 12
      assert Slots.ids() -- Slots.keys() == ["custom"]
    end

    test "UnknownType maps to custom" do
      assert Slots.of_component("NoSuchComponent") == "custom"
      assert Slots.of_component(nil) == "custom"
    end

    test "the designer mapping matches the spec's table" do
      assert Slots.of_component("Podman") == "runtime"
      assert Slots.of_component("Docker") == "runtime"
      assert Slots.of_component("Nerdctl") == "runtime"
      assert Slots.of_component("LagoGrey") == "base-image"
      assert Slots.of_component("Rokur") == "secrets-gate"
      assert Slots.of_component("Svalinn") == "edge-gateway"
      assert Slots.of_component("Selur") == "seam-sealant"
      assert Slots.of_component("Vordr") == "orchestration-verification"
      assert Slots.of_component("CerroTorre") == "packer-signer"
      assert Slots.of_component("Volume") == "storage"
      assert Slots.of_component("Network") == "network"
    end
  end

  describe "the descriptor catalogue" do
    test "v1 ships exactly two descriptors, the two consumers" do
      catalogue = Parts.load!()
      assert Enum.sort(Map.keys(catalogue)) == ["rokur", "svalinn"]
    end

    test "every descriptor pins a 40-hex sha and a slot in the table" do
      for {_name, part} <- Parts.load!() do
        assert part.sha =~ ~r/\A[0-9a-f]{40}\z/
        assert Slots.slot?(part.slot)
      end
    end

    test "a descriptor with an unknown key is rejected, not ignored" do
      in_tmp(fn dir ->
        File.write!(Path.join(dir, "bad.toml"), """
        [part]
        name = "bad"
        slot = "custom"
        interface = "oci"
        repo = "https://example.org/bad"
        sha = "#{String.duplicate("0", 40)}"
        surprise = "this key does not exist"
        """)

        assert_raise ArgumentError, ~r/unknown key\(s\) in \[part\]: surprise/, fn ->
          Parts.load!(dir)
        end
      end)
    end

    test "a descriptor with a short sha is rejected" do
      in_tmp(fn dir ->
        File.write!(Path.join(dir, "bad.toml"), """
        [part]
        name = "bad"
        slot = "custom"
        interface = "oci"
        repo = "https://example.org/bad"
        sha = "abc123"
        """)

        assert_raise ArgumentError, ~r/40 lowercase hex/, fn -> Parts.load!(dir) end
      end)
    end

    test "a descriptor whose slot is outside the table is rejected" do
      in_tmp(fn dir ->
        File.write!(Path.join(dir, "bad.toml"), """
        [part]
        name = "bad"
        slot = "not-a-slot"
        interface = "oci"
        repo = "https://example.org/bad"
        sha = "#{String.duplicate("0", 40)}"
        """)

        assert_raise ArgumentError, ~r/is not in the slot table/, fn -> Parts.load!(dir) end
      end)
    end
  end

  # ---------------------------------------------------------------------------
  # The mix task. The spec names `mix stapeln.bundle --check` as the gate the
  # v1 smoke runs against a bundle it did not generate in the same process, so
  # the task has to be EXERCISED, not merely present. Everything above calls the
  # modules directly and would pass unchanged against a task that cannot run at
  # all -- a path-join slip or an OptionParser mismatch would ship a gate that
  # silently no-ops.
  # ---------------------------------------------------------------------------

  describe "mix stapeln.bundle" do
    @design %{
      "version" => "1",
      "metadata" => %{"name" => "demo"},
      "canvas" => %{
        "components" => [
          %{"id" => "gate-1", "type" => "Rokur"},
          %{"id" => "edge-1", "type" => "Svalinn"},
          %{"id" => "rt-1", "type" => "Podman"},
          %{"id" => "mystery-1", "type" => "SomethingElse"}
        ],
        "connections" => []
      }
    }

    test "emits the eleven files, then --check passes, then --check can fail" do
      in_tmp(fn dir ->
        design = Path.join(dir, "d.json")
        out = Path.join(dir, "bundle")
        File.write!(design, Jason.encode!(@design))

        emit = fn ->
          Mix.Task.rerun("stapeln.bundle", [
            "--design",
            design,
            "--out",
            out,
            "--author",
            "A. Author",
            "--email",
            "a@example.org",
            "--license",
            "MPL-2.0",
            "--owner",
            "acme"
          ])
        end

        assert capture_io(emit) =~ "wrote 11 files"
        assert length(File.ls!(out)) == 11

        lock = Path.join(out, "stack.lock")
        check = fn -> Mix.Task.rerun("stapeln.bundle", ["--check", lock]) end

        assert capture_io(check) =~ "ok (12 slot keys"

        # The half that matters. Emit-then-check-passes proves nothing on its own,
        # because a --check that returns :ok unconditionally would also pass it.
        File.write!(lock, String.replace(File.read!(lock), ~s(firewall = ""\n), ""))

        assert_raise Mix.Error, ~r/missing 1 key\(s\): firewall/, fn ->
          capture_io(check)
        end
      end)
    end

    test "an unrecognised option is refused rather than silently ignored" do
      assert_raise Mix.Error, ~r/unrecognised option/, fn ->
        Mix.Task.rerun("stapeln.bundle", ["--design", "x.json", "--surprise", "1"])
      end
    end
  end

  # The top-level keys under `services:`. They are the only two-space-indented
  # bare keys the emitter produces; anything nested sits at four or more. If that
  # ever stops being true this fails loudly, which is the right outcome.
  defp compose_service_keys do
    bundle()["compose.yaml"]
    |> String.split("\n")
    |> Enum.flat_map(fn line ->
      case Regex.run(~r/^  ([A-Za-z0-9][A-Za-z0-9_.-]*):$/, line) do
        [_, key] -> [key]
        nil -> []
      end
    end)
    |> Enum.sort()
  end

  defp in_tmp(fun) do
    dir = Path.join(System.tmp_dir!(), "stapeln-parts-#{System.unique_integer([:positive])}")
    File.mkdir_p!(dir)

    try do
      fun.(dir)
    after
      File.rm_rf!(dir)
    end
  end
end
