// SPDX-License-Identifier: PMPL-1.0-or-later
// LagoGreyExport.res - Export Lago Grey images

// Direct JS binding for Array.join (avoids deprecated Js.Array2.joinWith)
@send external joinWith: (array<string>, string) => string = "join"

// Lago Grey designer state (simplified from LagoGreyImageDesigner)
type baseImage =
  | Distroless
  | Alpine
  | Scratch

type iceFormation =
  | Floe(string, int)
  | Iceberg(string, int)
  | Glacier(string, int)

type lagoGreyState = {
  baseImage: baseImage,
  formations: array<iceFormation>,
  totalSize: int,
}

let formationName = (formation: iceFormation): string => {
  switch formation {
  | Floe(name, _) => name
  | Iceberg(name, _) => name
  | Glacier(name, _) => name
  }
}

let formationSize = (formation: iceFormation): int => {
  switch formation {
  | Floe(_, size) => size
  | Iceberg(_, size) => size
  | Glacier(_, size) => size
  }
}

// Generate Dockerfile from Lago Grey state
let generateDockerfile = (state: lagoGreyState): string => {
  let baseImageStr = switch state.baseImage {
  | Distroless => "gcr.io/distroless/static-debian12:nonroot"
  | Alpine => "alpine:3.19"
  | Scratch => "scratch"
  }

  let header =
    "# SPDX-License-Identifier: PMPL-1.0-or-later\n" ++
    "# Generated by stapeln Lago Grey Designer\n" ++
    "# Generated at: " ++
    Date.make()->Date.toISOString ++ "\n\n"

  let from = "FROM " ++ baseImageStr ++ " AS base\n\n"

  // Add formations as layers
  let formations =
    state.formations
    ->Array.map(formation => {
      let name = formationName(formation)
      let size = formationSize(formation)

      // Generate appropriate RUN commands based on formation type
      switch formation {
      | Floe("hello", _) =>
        "# Add hello (29 KB)\n" ++ "RUN apk add --no-cache hello || echo 'hello binary'\n\n"

      | Floe("libsodium", _) =>
        "# Add libsodium (506 KB) - Classical crypto\n" ++ "RUN apk add --no-cache libsodium libsodium-dev\n\n"

      | Floe("libargon2", _) =>
        "# Add libargon2 (42 KB) - Password hashing\n" ++ "RUN apk add --no-cache argon2-libs\n\n"

      | Floe("obli-pkg", _) =>
        "# Add obli-pkg (56 KB) - Package manager\n" ++ "COPY --from=oblibeny-builder /usr/local/bin/obli-pkg /usr/local/bin/\n\n"

      | Iceberg("liboqs", _) =>
        "# Add liboqs (11 MB) - Post-quantum cryptography\n" ++ "RUN apk add --no-cache liboqs liboqs-dev\n\n"

      | _ =>
        "# Add " ++
        name ++
        " (" ++
        Int.toString(size) ++
        " bytes)\n" ++
        "# TODO: Implement installation for " ++
        name ++ "\n\n"
      }
    })
    ->joinWith("")

  let metadata =
    "# Image metadata\n" ++
    "LABEL org.opencontainers.image.title=\"Lago Grey Minimal Image\"\n" ++
    "LABEL org.opencontainers.image.description=\"Minimal Linux distribution built with stapeln\"\n" ++
    "LABEL org.opencontainers.image.vendor=\"hyperpolymath\"\n" ++
    "LABEL org.opencontainers.image.licenses=\"PMPL-1.0-or-later\"\n" ++
    "LABEL com.hyperpolymath.lago-grey.base=\"" ++
    baseImageStr ++
    "\"\n" ++
    "LABEL com.hyperpolymath.lago-grey.size=\"" ++
    Int.toString(state.totalSize) ++ "\"\n\n"

  let entrypoint = "# Default entrypoint\n" ++ "ENTRYPOINT [\"/bin/sh\"]\n"

  header ++ from ++ formations ++ metadata ++ entrypoint
}

// Generate manifest.json
let generateManifest = (state: lagoGreyState): string => {
  let formations =
    state.formations
    ->Array.map(formation => {
      "    {\n" ++
      "      \"name\": \"" ++
      formationName(formation) ++
      "\",\n" ++
      "      \"size\": " ++
      Int.toString(formationSize(formation)) ++
      "\n" ++ "    }"
    })
    ->joinWith(",\n")

  let baseStr = switch state.baseImage {
  | Distroless => "distroless"
  | Alpine => "alpine"
  | Scratch => "scratch"
  }

  "{\n" ++
  "  \"version\": \"1.0\",\n" ++
  "  \"created\": \"" ++
  Date.make()->Date.toISOString ++
  "\",\n" ++
  "  \"author\": \"Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>\",\n" ++
  "  \"base\": \"" ++
  baseStr ++
  "\",\n" ++
  "  \"totalSize\": " ++
  Int.toString(state.totalSize) ++
  ",\n" ++
  "  \"formations\": [\n" ++
  formations ++
  "\n" ++
  "  ],\n" ++
  "  \"security\": {\n" ++
  "    \"postQuantum\": " ++
  (Array.some(state.formations, f => formationName(f) == "liboqs") ? "true" : "false") ++
  ",\n" ++
  "    \"classical\": " ++
  (Array.some(state.formations, f => formationName(f) == "libsodium") ? "true" : "false") ++
  "\n" ++
  "  },\n" ++
  "  \"signatures\": {\n" ++
  "    \"dilithium5\": \"TODO\",\n" ++
  "    \"ed448\": \"TODO\",\n" ++
  "    \"sphincs\": \"TODO\"\n" ++
  "  }\n" ++ "}\n"
}

// Generate build instructions (since we can't directly call podman from browser)
let generateBuildInstructions = (): string => {
  "# Build Instructions\n\n" ++
  "1. Save the Dockerfile to a directory\n" ++
  "2. Run: podman build -t lago-grey:custom .\n" ++
  "3. Verify: podman images | grep lago-grey\n" ++
  "4. Sign with triple crypto:\n" ++
  "   - podman sign dilithium5 ...\n" ++
  "   - podman sign ed448 ...\n" ++
  "   - podman sign sphincs+ ...\n" ++
  "5. Export: podman save lago-grey:custom -o lago-grey-custom.tar\n" ++
  "6. Compress: gzip lago-grey-custom.tar\n\n" ++ "For automated builds, see: https://github.com/hyperpolymath/oblibeny\n"
}

// Download Dockerfile
let exportDockerfile = (state: lagoGreyState) => {
  let dockerfile = generateDockerfile(state)
  let timestamp = Date.now()->Float.toString->String.slice(~start=0, ~end=10)
  let filename = "Dockerfile.lago-grey-" ++ timestamp

  Export.downloadFile(filename, dockerfile, "text/plain")
  Console.log("Exported Dockerfile: " ++ filename)
}

// Download manifest
let exportManifest = (state: lagoGreyState) => {
  let manifest = generateManifest(state)
  let timestamp = Date.now()->Float.toString->String.slice(~start=0, ~end=10)
  let filename = "manifest-" ++ timestamp ++ ".json"

  Export.downloadFile(filename, manifest, "application/json")
  Console.log("Exported manifest: " ++ filename)
}

// Download build instructions
let exportBuildInstructions = () => {
  let instructions = generateBuildInstructions()
  Export.downloadFile("BUILD-INSTRUCTIONS.md", instructions, "text/markdown")
  Console.log("Exported build instructions")
}

// Export complete package (Dockerfile + manifest + instructions)
let exportCompletePackage = (state: lagoGreyState) => {
  exportDockerfile(state)
  exportManifest(state)
  exportBuildInstructions()

  Console.log("Exported complete Lago Grey package")
  Console.log("Next: Run 'podman build' to create the image")
}
