// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Export from "./Export.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function formationName(formation) {
  return formation._0;
}

function formationSize(formation) {
  return formation._1;
}

function generateDockerfile(state) {
  let match = state.baseImage;
  let baseImageStr;
  switch (match) {
    case "Distroless" :
      baseImageStr = "gcr.io/distroless/static-debian12:nonroot";
      break;
    case "Alpine" :
      baseImageStr = "alpine:3.19";
      break;
    case "Scratch" :
      baseImageStr = "scratch";
      break;
  }
  let header = "# SPDX-License-Identifier: PMPL-1.0-or-later\n# Generated by stapeln Lago Grey Designer\n# Generated at: " + new Date().toISOString() + "\n\n";
  let from = "FROM " + baseImageStr + " AS base\n\n";
  let formations = Belt_Array.map(state.formations, formation => {
    let name = formationName(formation);
    let size = formationSize(formation);
    switch (formation.TAG) {
      case "Floe" :
        switch (formation._0) {
          case "hello" :
            return "# Add hello (29 KB)\nRUN apk add --no-cache hello || echo 'hello binary'\n\n";
          case "libargon2" :
            return "# Add libargon2 (42 KB) - Password hashing\nRUN apk add --no-cache argon2-libs\n\n";
          case "libsodium" :
            return "# Add libsodium (506 KB) - Classical crypto\nRUN apk add --no-cache libsodium libsodium-dev\n\n";
          case "obli-pkg" :
            return "# Add obli-pkg (56 KB) - Package manager\nCOPY --from=oblibeny-builder /usr/local/bin/obli-pkg /usr/local/bin/\n\n";
        }
        break;
      case "Iceberg" :
        if (formation._0 === "liboqs") {
          return "# Add liboqs (11 MB) - Post-quantum cryptography\nRUN apk add --no-cache liboqs liboqs-dev\n\n";
        }
        break;
      case "Glacier" :
        break;
    }
    return "# Add " + name + " (" + String(size) + " bytes)\n# TODO: Implement installation for " + name + "\n\n";
  }).join("");
  let metadata = "# Image metadata\nLABEL org.opencontainers.image.title=\"Lago Grey Minimal Image\"\nLABEL org.opencontainers.image.description=\"Minimal Linux distribution built with stapeln\"\nLABEL org.opencontainers.image.vendor=\"hyperpolymath\"\nLABEL org.opencontainers.image.licenses=\"PMPL-1.0-or-later\"\nLABEL com.hyperpolymath.lago-grey.base=\"" + baseImageStr + "\"\nLABEL com.hyperpolymath.lago-grey.size=\"" + String(state.totalSize) + "\"\n\n";
  let entrypoint = "# Default entrypoint\nENTRYPOINT [\"/bin/sh\"]\n";
  return header + from + formations + metadata + entrypoint;
}

function generateManifest(state) {
  let formations = Belt_Array.map(state.formations, formation => "    {\n      \"name\": \"" + formationName(formation) + "\",\n      \"size\": " + String(formationSize(formation)) + "\n    }").join(",\n");
  let match = state.baseImage;
  let baseStr;
  switch (match) {
    case "Distroless" :
      baseStr = "distroless";
      break;
    case "Alpine" :
      baseStr = "alpine";
      break;
    case "Scratch" :
      baseStr = "scratch";
      break;
  }
  return "{\n  \"version\": \"1.0\",\n  \"created\": \"" + new Date().toISOString() + "\",\n  \"author\": \"Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>\",\n  \"base\": \"" + baseStr + "\",\n  \"totalSize\": " + String(state.totalSize) + ",\n  \"formations\": [\n" + formations + "\n  ],\n  \"security\": {\n    \"postQuantum\": " + (
    Belt_Array.some(state.formations, f => formationName(f) === "liboqs") ? "true" : "false"
  ) + ",\n    \"classical\": " + (
    Belt_Array.some(state.formations, f => formationName(f) === "libsodium") ? "true" : "false"
  ) + "\n  },\n  \"signatures\": {\n    \"dilithium5\": \"TODO\",\n    \"ed448\": \"TODO\",\n    \"sphincs\": \"TODO\"\n  }\n}\n";
}

function generateBuildInstructions() {
  return "# Build Instructions\n\n1. Save the Dockerfile to a directory\n2. Run: podman build -t lago-grey:custom .\n3. Verify: podman images | grep lago-grey\n4. Sign with triple crypto:\n   - podman sign dilithium5 ...\n   - podman sign ed448 ...\n   - podman sign sphincs+ ...\n5. Export: podman save lago-grey:custom -o lago-grey-custom.tar\n6. Compress: gzip lago-grey-custom.tar\n\nFor automated builds, see: https://github.com/hyperpolymath/oblibeny\n";
}

function exportDockerfile(state) {
  let dockerfile = generateDockerfile(state);
  let timestamp = String(Date.now()).slice(0, 10);
  let filename = "Dockerfile.lago-grey-" + timestamp;
  Export.downloadFile(filename, dockerfile, "text/plain");
  console.log("Exported Dockerfile: " + filename);
}

function exportManifest(state) {
  let manifest = generateManifest(state);
  let timestamp = String(Date.now()).slice(0, 10);
  let filename = "manifest-" + timestamp + ".json";
  Export.downloadFile(filename, manifest, "application/json");
  console.log("Exported manifest: " + filename);
}

function exportBuildInstructions() {
  let instructions = generateBuildInstructions();
  Export.downloadFile("BUILD-INSTRUCTIONS.md", instructions, "text/markdown");
  console.log("Exported build instructions");
}

function exportCompletePackage(state) {
  exportDockerfile(state);
  exportManifest(state);
  exportBuildInstructions();
  console.log("Exported complete Lago Grey package");
  console.log("Next: Run 'podman build' to create the image");
}

export {
  formationName,
  formationSize,
  generateDockerfile,
  generateManifest,
  generateBuildInstructions,
  exportDockerfile,
  exportManifest,
  exportBuildInstructions,
  exportCompletePackage,
}
/* Export Not a pure module */
