// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Model from "./Model.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

let lightBg = "#FFFFFF";

let lightText = "#000000";

let lightBorder = "#333333";

let lightPrimary = "#0052CC";

let lightSecondary = "#666666";

let darkBg = "#000000";

let darkText = "#FFFFFF";

let darkBorder = "#CCCCCC";

let darkPrimary = "#66B2FF";

let darkSecondary = "#AAAAAA";

let cerroTorre = "#1B5E20";

let lagoGrey = "#546E7A";

let svalinn = "#0D47A1";

let selur = "#4A148C";

let vordr = "#B71C1C";

let rokur = "#004D40";

let podman = "#6A1B9A";

let docker = "#1565C0";

let nerdctl = "#2E7D32";

let unknown = "#455A64";

let Colors = {
  lightBg: lightBg,
  lightText: lightText,
  lightBorder: lightBorder,
  lightPrimary: lightPrimary,
  lightSecondary: lightSecondary,
  darkBg: darkBg,
  darkText: darkText,
  darkBorder: darkBorder,
  darkPrimary: darkPrimary,
  darkSecondary: darkSecondary,
  cerroTorre: cerroTorre,
  lagoGrey: lagoGrey,
  svalinn: svalinn,
  selur: selur,
  vordr: vordr,
  rokur: rokur,
  podman: podman,
  docker: docker,
  nerdctl: nerdctl,
  unknown: unknown
};

function ariaLabel(text) {
  return "aria-label=\"" + text + "\"";
}

function ariaDescribedBy(id) {
  return "aria-describedby=\"" + id + "\"";
}

function ariaRole(role) {
  return "role=\"" + role + "\"";
}

function ariaBraille(text) {
  return "data-braille=\"" + text + "\"";
}

function renderStackBlock(component, isDark) {
  let match = component.componentType;
  let bgColor;
  if (typeof match !== "object") {
    switch (match) {
      case "CerroTorre" :
        bgColor = cerroTorre;
        break;
      case "LagoGrey" :
        bgColor = lagoGrey;
        break;
      case "Svalinn" :
        bgColor = svalinn;
        break;
      case "Selur" :
        bgColor = selur;
        break;
      case "Vordr" :
        bgColor = vordr;
        break;
      case "Rokur" :
        bgColor = rokur;
        break;
      case "Podman" :
        bgColor = podman;
        break;
      case "Docker" :
        bgColor = docker;
        break;
      case "Nerdctl" :
        bgColor = nerdctl;
        break;
      case "Volume" :
        bgColor = "#757575";
        break;
      case "Network" :
        bgColor = "#9E9E9E";
        break;
    }
  } else {
    bgColor = unknown;
  }
  let componentName = Model.componentTypeToString(component.componentType);
  return JsxRuntime.jsxs("section", {
    children: [
      JsxRuntime.jsx("h3", {
        children: componentName,
        id: component.id + "-title",
        style: {
          fontSize: "1.2rem",
          fontWeight: "600",
          margin: "0"
        }
      }),
      JsxRuntime.jsx("p", {
        children: "Position: " + String(component.position.x) + ", " + String(component.position.y),
        "aria-describedby": component.id + "-title",
        id: component.id + "-desc",
        style: {
          fontSize: "0.9rem",
          margin: "0.5rem 0 0 0",
          opacity: "0.9"
        }
      })
    ],
    "aria-label": componentName + " component",
    className: "stack-block",
    role: "region",
    style: {
      backgroundColor: bgColor,
      border: isDark ? "2px solid " + darkBorder : "2px solid " + lightBorder,
      borderRadius: "8px",
      boxShadow: "0 2px 4px rgba(0,0,0,0.3)",
      color: "white",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      margin: "0.5rem",
      minHeight: "80px",
      padding: "1.5rem"
    }
  });
}

function renderParagonStack(model, isDark) {
  let result = model.validationResult;
  let components = [
    [
      "CerroTorre",
      "Cerro Torre",
      "Build verified container bundles"
    ],
    [
      "Svalinn",
      "Svalinn",
      "Edge gateway with authentication"
    ],
    [
      "Selur",
      "selur",
      "Zero-copy IPC bridge"
    ],
    [
      "Vordr",
      "Vörðr",
      "Container orchestrator"
    ],
    [
      "Rokur",
      "Rokur",
      "Secrets gate — fails closed if secrets are missing"
    ],
    [
      "Podman",
      "Podman",
      "OCI runtime"
    ],
    [
      "Docker",
      "Docker",
      "Docker Engine runtime"
    ],
    [
      "Nerdctl",
      "nerdctl",
      "containerd CLI"
    ]
  ];
  return JsxRuntime.jsxs("main", {
    children: [
      JsxRuntime.jsx("div", {
        children: result !== undefined ? (
            result.valid ? "Stack validation passed" : "Stack validation failed with " + String(result.errors.length) + " errors"
          ) : null,
        "aria-atomic": true,
        "aria-live": "polite",
        role: "status",
        style: {
          height: "1px",
          left: "-10000px",
          overflow: "hidden",
          position: "absolute",
          width: "1px"
        }
      }),
      JsxRuntime.jsxs("header", {
        children: [
          JsxRuntime.jsxs("h1", {
            children: [
              "stackur",
              JsxRuntime.jsx("span", {
                children: "Container Stack Designer",
                style: {
                  fontSize: "0.9rem",
                  fontWeight: "400",
                  marginLeft: "0.5rem",
                  opacity: "0.8"
                }
              })
            ],
            id: "main-title",
            style: {
              fontSize: "2rem",
              fontWeight: "700",
              margin: "0"
            }
          }),
          JsxRuntime.jsx("button", {
            children: isDark ? "🌙 Dark" : "☀️ Light",
            "aria-label": "Toggle dark/light theme",
            "aria-checked": isDark ? "true" : "false",
            role: "switch",
            style: {
              backgroundColor: isDark ? darkPrimary : lightPrimary,
              border: "none",
              borderRadius: "6px",
              color: "white",
              cursor: "pointer",
              fontSize: "1rem",
              fontWeight: "600",
              padding: "0.75rem 1.5rem",
              transition: "background-color 0.2s ease"
            }
          })
        ],
        role: "banner",
        style: {
          alignItems: "center",
          borderBottom: isDark ? "2px solid " + darkBorder : "2px solid " + lightBorder,
          display: "flex",
          justifyContent: "space-between",
          paddingBottom: "1.5rem"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("aside", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Components",
                id: "palette-title",
                style: {
                  fontSize: "1.3rem",
                  fontWeight: "600",
                  marginBottom: "1rem"
                }
              }),
              JsxRuntime.jsx("nav", {
                children: JsxRuntime.jsx("ul", {
                  children: Belt_Array.map(components, param => {
                    let desc = param[2];
                    let name = param[1];
                    return JsxRuntime.jsx("li", {
                      children: JsxRuntime.jsxs("button", {
                        children: [
                          JsxRuntime.jsx("div", {
                            children: name,
                            style: {
                              fontWeight: "600"
                            }
                          }),
                          JsxRuntime.jsx("div", {
                            children: desc,
                            style: {
                              fontSize: "0.8rem",
                              marginTop: "0.25rem",
                              opacity: "0.8"
                            }
                          })
                        ],
                        "aria-label": "Add " + name + " to stack. " + desc,
                        style: {
                          backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                          border: isDark ? "2px solid " + darkBorder : "2px solid " + lightBorder,
                          borderRadius: "6px",
                          color: isDark ? darkText : lightText,
                          cursor: "pointer",
                          fontSize: "0.95rem",
                          fontWeight: "500",
                          padding: "1rem",
                          textAlign: "left",
                          transition: "all 0.2s ease",
                          width: "100%"
                        }
                      }),
                      role: "listitem",
                      style: {
                        marginBottom: "0.75rem"
                      }
                    });
                  }),
                  role: "list",
                  style: {
                    listStyle: "none",
                    margin: "0",
                    padding: "0"
                  }
                }),
                "aria-labelledby": "palette-title"
              })
            ],
            "aria-label": "Component palette",
            role: "complementary",
            style: {
              borderRight: isDark ? "2px solid " + darkBorder : "2px solid " + lightBorder,
              paddingRight: "2rem",
              width: "250px"
            }
          }),
          JsxRuntime.jsxs("article", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Stack Configuration",
                id: "stack-title",
                style: {
                  fontSize: "1.3rem",
                  fontWeight: "600",
                  marginBottom: "1rem"
                }
              }),
              model.components.length === 0 ? JsxRuntime.jsx("div", {
                  children: JsxRuntime.jsx("p", {
                    children: "Drag components from the palette to build your stack",
                    style: {
                      fontSize: "1.1rem",
                      margin: "0"
                    }
                  }),
                  "aria-label": "Empty stack",
                  role: "status",
                  style: {
                    border: isDark ? "2px dashed " + darkBorder : "2px dashed " + lightBorder,
                    borderRadius: "8px",
                    color: isDark ? darkSecondary : lightSecondary,
                    padding: "3rem",
                    textAlign: "center"
                  }
                }) : JsxRuntime.jsx("div", {
                  children: Belt_Array.map(model.components, comp => renderStackBlock(comp, isDark)),
                  "aria-label": "Stack components",
                  "aria-describedby": "stack-title",
                  role: "region"
                })
            ],
            "aria-label": "Current stack configuration",
            role: "article",
            style: {
              flex: "1",
              paddingLeft: "2rem"
            }
          })
        ],
        style: {
          display: "flex",
          marginTop: "2rem"
        }
      })
    ],
    "aria-label": "Container Stack Designer",
    className: "paragon-stack-view",
    role: "main",
    style: {
      backgroundColor: isDark ? darkBg : lightBg,
      color: isDark ? darkText : lightText,
      display: "flex",
      flexDirection: "column",
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      minHeight: "100vh",
      padding: "2rem"
    }
  });
}

let view = renderParagonStack;

export {
  Colors,
  ariaLabel,
  ariaDescribedBy,
  ariaRole,
  ariaBraille,
  renderStackBlock,
  renderParagonStack,
  view,
}
/* Model Not a pure module */
