// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

let initialState_toasts = [];

let initialState = {
  toasts: initialState_toasts,
  nextId: 0
};

function update(msg, state) {
  switch (msg.TAG) {
    case "ShowToast" :
      let id = "toast-" + String(state.nextId);
      let newToast_message = msg._0;
      let newToast_toastType = msg._1;
      let newToast_duration = msg._2;
      let newToast_timestamp = Date.now();
      let newToast = {
        id: id,
        message: newToast_message,
        toastType: newToast_toastType,
        duration: newToast_duration,
        timestamp: newToast_timestamp
      };
      return {
        toasts: Belt_Array.concat(state.toasts, [newToast]),
        nextId: state.nextId + 1 | 0
      };
    case "DismissToast" :
      let id$1 = msg._0;
      return {
        toasts: Belt_Array.keep(state.toasts, t => t.id !== id$1),
        nextId: state.nextId
      };
    case "AutoDismissToast" :
      let id$2 = msg._0;
      return {
        toasts: Belt_Array.keep(state.toasts, t => t.id !== id$2),
        nextId: state.nextId
      };
  }
}

function toastColor(toastType) {
  switch (toastType) {
    case "Success" :
      return "#4caf50";
    case "Error" :
      return "#f44336";
    case "Warning" :
      return "#ff9800";
    case "Info" :
      return "#4a9eff";
  }
}

function toastIcon(toastType) {
  switch (toastType) {
    case "Success" :
      return "✓";
    case "Error" :
      return "✗";
    case "Warning" :
      return "⚠";
    case "Info" :
      return "ℹ";
  }
}

function toastLabel(toastType) {
  switch (toastType) {
    case "Success" :
      return "Success";
    case "Error" :
      return "Error";
    case "Warning" :
      return "Warning";
    case "Info" :
      return "Info";
  }
}

function viewToast(toast, dispatch) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: toastIcon(toast.toastType),
        style: {
          color: toastColor(toast.toastType),
          fontSize: "24px",
          lineHeight: "1"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: toastLabel(toast.toastType),
            style: {
              color: toastColor(toast.toastType),
              fontSize: "12px",
              fontWeight: "600",
              letterSpacing: "0.5px",
              marginBottom: "4px",
              textTransform: "uppercase"
            }
          }),
          JsxRuntime.jsx("div", {
            children: toast.message,
            style: {
              color: "#e0e6ed",
              fontSize: "14px",
              lineHeight: "1.4"
            }
          })
        ],
        style: {
          flex: "1"
        }
      }),
      JsxRuntime.jsx("button", {
        children: "×",
        "aria-label": "Dismiss " + toastLabel(toast.toastType) + " notification",
        style: {
          background: "transparent",
          border: "none",
          color: "#8892a6",
          cursor: "pointer",
          fontSize: "20px",
          lineHeight: "1",
          padding: "4px",
          transition: "color 0.2s"
        },
        onClick: param => dispatch({
          TAG: "DismissToast",
          _0: toast.id
        })
      })
    ],
    "aria-atomic": true,
    "aria-live": "polite",
    className: "toast",
    role: "status",
    style: {
      alignItems: "center",
      animation: "slideIn 0.3s ease-out",
      background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
      border: "2px solid " + toastColor(toast.toastType),
      borderRadius: "12px",
      boxShadow: "0 8px 24px rgba(0, 0, 0, 0.4)",
      display: "flex",
      gap: "12px",
      marginBottom: "12px",
      maxWidth: "500px",
      minWidth: "300px",
      padding: "16px 20px",
      position: "relative"
    }
  }, toast.id);
}

function Toast(props) {
  let dispatch = props.dispatch;
  let toasts = props.toasts;
  React.useEffect(() => {
    let timeoutIds = Belt_Array.map(toasts, toast => setTimeout(() => dispatch({
      TAG: "AutoDismissToast",
      _0: toast.id
    }), toast.duration));
    return () => Belt_Array.forEach(timeoutIds, prim => {
      clearTimeout(prim);
    });
  }, [toasts]);
  return JsxRuntime.jsx("div", {
    children: Belt_Array.map(toasts, toast => viewToast(toast, dispatch)),
    className: "toast-container",
    style: {
      alignItems: "flex-end",
      display: "flex",
      flexDirection: "column",
      position: "fixed",
      right: "24px",
      top: "24px",
      zIndex: "10000"
    }
  });
}

function success(message) {
  return [
    message,
    "Success",
    3000
  ];
}

function error(message) {
  return [
    message,
    "Error",
    5000
  ];
}

function warning(message) {
  return [
    message,
    "Warning",
    4000
  ];
}

function info(message) {
  return [
    message,
    "Info",
    3000
  ];
}

let make = Toast;

export {
  initialState,
  update,
  toastColor,
  toastIcon,
  toastLabel,
  viewToast,
  make,
  success,
  error,
  warning,
  info,
}
/* react Not a pure module */
