# SPDX-License-Identifier: MPL-2.0
[package]
name = "fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.selur]
path = ".."

[[bin]]
name = "fuzz_main"
path = "fuzz_targets/fuzz_main.rs"
test = false
doc = false
