// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let baseUrl = "/api";

function getToken() {
  return Primitive_option.fromNullable(window.localStorage.getItem("stapeln_auth_token"));
}

function setToken(token) {
  window.localStorage.setItem("stapeln_auth_token", token);
}

function clearToken() {
  window.localStorage.removeItem("stapeln_auth_token");
}

function authHeaders() {
  let headers = Object.fromEntries([[
      "content-type",
      "application/json"
    ]]);
  let token = Primitive_option.fromNullable(window.localStorage.getItem("stapeln_auth_token"));
  if (token !== undefined) {
    headers["authorization"] = "Bearer " + token;
  }
  return headers;
}

function fetchText(url, init) {
  return Stdlib_Promise.$$catch(fetch(url, init).then(res => {
    if (res.ok) {
      return res.text().then(text => Promise.resolve({
        TAG: "Ok",
        _0: text
      }));
    }
    let status = res.status;
    return Promise.resolve({
      TAG: "Error",
      _0: "HTTP " + String(status)
    });
  }), exn => {
    let msg = exn.RE_EXN_ID === "JsExn" ? Belt_Option.getWithDefault(Stdlib_JsExn.message(exn._1), "Network error") : "Network error";
    return Promise.resolve({
      TAG: "Error",
      _0: msg
    });
  });
}

function fetchJson(url, init) {
  return Stdlib_Promise.$$catch(fetch(url, init).then(res => {
    if (res.ok) {
      return res.json().then(json => Promise.resolve({
        TAG: "Ok",
        _0: json
      }));
    }
    let status = res.status;
    return Promise.resolve({
      TAG: "Error",
      _0: "HTTP " + String(status)
    });
  }), exn => {
    let msg = exn.RE_EXN_ID === "JsExn" ? Belt_Option.getWithDefault(Stdlib_JsExn.message(exn._1), "Network error") : "Network error";
    return Promise.resolve({
      TAG: "Error",
      _0: msg
    });
  });
}

function saveStack(body) {
  return fetchText(baseUrl + "/stacks", {
    method: "POST",
    headers: authHeaders(),
    body: body
  });
}

function loadStack(id) {
  return fetchText(baseUrl + "/stacks/" + id, {
    method: "GET",
    headers: authHeaders()
  });
}

function validateStack(stackId) {
  return fetchJson(baseUrl + "/stacks/" + String(stackId) + "/validate", {
    method: "POST",
    headers: authHeaders()
  });
}

function runSecurityScan(stackId) {
  return fetchJson(baseUrl + "/stacks/" + String(stackId) + "/security-scan", {
    method: "POST",
    headers: authHeaders()
  });
}

function runGapAnalysis(stackId) {
  return fetchJson(baseUrl + "/stacks/" + String(stackId) + "/gap-analysis", {
    method: "POST",
    headers: authHeaders()
  });
}

function loadSettings() {
  return fetchJson(baseUrl + "/settings", {
    method: "GET",
    headers: authHeaders()
  });
}

function saveSettings(settings) {
  let body = JSON.stringify(settings);
  return Stdlib_Promise.$$catch(fetch(baseUrl + "/settings", {
    method: "PUT",
    headers: authHeaders(),
    body: body
  }).then(res => {
    if (res.ok) {
      return Promise.resolve({
        TAG: "Ok",
        _0: undefined
      });
    }
    let status = res.status;
    return Promise.resolve({
      TAG: "Error",
      _0: "HTTP " + String(status)
    });
  }), exn => {
    let msg = exn.RE_EXN_ID === "JsExn" ? Belt_Option.getWithDefault(Stdlib_JsExn.message(exn._1), "Network error") : "Network error";
    return Promise.resolve({
      TAG: "Error",
      _0: msg
    });
  });
}

function createPinhole(source, destination, port, ttlSeconds, reason, protocolOpt) {
  let protocol = protocolOpt !== undefined ? protocolOpt : "tcp";
  let body = JSON.stringify(Object.fromEntries([
    [
      "source",
      source
    ],
    [
      "destination",
      destination
    ],
    [
      "port",
      port
    ],
    [
      "ttl_seconds",
      ttlSeconds
    ],
    [
      "reason",
      reason
    ],
    [
      "protocol",
      protocol
    ]
  ]));
  return fetchJson(baseUrl + "/firewall/pinholes", {
    method: "POST",
    headers: authHeaders(),
    body: body
  });
}

function listPinholes() {
  return fetchJson(baseUrl + "/firewall/pinholes", {
    method: "GET",
    headers: authHeaders()
  });
}

function revokePinhole(id) {
  return fetchJson(baseUrl + "/firewall/pinholes/" + id, {
    method: "DELETE",
    headers: authHeaders()
  });
}

function checkFirewall(source, destination, port) {
  let body = JSON.stringify(Object.fromEntries([
    [
      "source",
      source
    ],
    [
      "destination",
      destination
    ],
    [
      "port",
      port
    ]
  ]));
  return fetchJson(baseUrl + "/firewall/check", {
    method: "POST",
    headers: authHeaders(),
    body: body
  });
}

function login(email, password) {
  let body = JSON.stringify(Object.fromEntries([
    [
      "email",
      email
    ],
    [
      "password",
      password
    ]
  ]));
  return fetchText(baseUrl + "/auth/login", {
    method: "POST",
    headers: Object.fromEntries([[
        "content-type",
        "application/json"
      ]]),
    body: body
  });
}

function register(email, password) {
  let body = JSON.stringify(Object.fromEntries([
    [
      "email",
      email
    ],
    [
      "password",
      password
    ]
  ]));
  return fetchText(baseUrl + "/auth/register", {
    method: "POST",
    headers: Object.fromEntries([[
        "content-type",
        "application/json"
      ]]),
    body: body
  });
}

export {
  baseUrl,
  getToken,
  setToken,
  clearToken,
  authHeaders,
  fetchText,
  fetchJson,
  saveStack,
  loadStack,
  validateStack,
  runSecurityScan,
  runGapAnalysis,
  loadSettings,
  saveSettings,
  createPinhole,
  listPinholes,
  revokePinhole,
  checkFirewall,
  login,
  register,
}
/* Stdlib_JsExn Not a pure module */
