// Generated by ReScript, PLEASE EDIT WITH CARE


function decodeSaveResponse(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return {
      TAG: "Error",
      _0: "missing stack id in response"
    };
  }
  let match = json["data"];
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: "missing stack id in response"
    };
  }
  if (typeof match !== "object" || match === null || Array.isArray(match)) {
    return {
      TAG: "Error",
      _0: "missing stack id in response"
    };
  }
  let match$1 = match["id"];
  if (typeof match$1 === "number") {
    return {
      TAG: "Ok",
      _0: match$1 | 0
    };
  } else {
    return {
      TAG: "Error",
      _0: "missing stack id in response"
    };
  }
}

export {
  decodeSaveResponse,
}
/* No side effect */
