// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Model from "./Model.res.js";
import * as React from "react";
import * as Import from "./Import.res.js";
import * as Socket from "./Socket.res.js";
import * as Update from "./Update.res.js";
import * as Belt_Int from "@rescript/runtime/lib/es6/Belt_Int.js";
import * as ApiClient from "./ApiClient.res.js";
import * as AppRouter from "./AppRouter.res.js";
import * as StackView from "./StackView.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as IdrisBadge from "./IdrisBadge.res.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as GapAnalysis from "./GapAnalysis.res.js";
import * as SettingsPage from "./SettingsPage.res.js";
import * as TopologyView from "./TopologyView.res.js";
import * as ErrorBoundary from "./ErrorBoundary.res.js";
import * as PipelineModel from "./PipelineModel.res.js";
import * as PipelineUpdate from "./PipelineUpdate.res.js";
import * as SimulationMode from "./SimulationMode.res.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as PortConfigPanel from "./PortConfigPanel.res.js";
import * as PipelineDesigner from "./PipelineDesigner.res.js";
import * as SecurityInspector from "./SecurityInspector.res.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as LagoGreyImageDesigner from "./LagoGreyImageDesigner.res.js";

let initialAppState_currentPage = AppRouter.getCurrentRoute();

let initialAppState_pipelineDesigner = PipelineModel.initialState();

let initialAppState = {
  currentPage: initialAppState_currentPage,
  model: Model.initialModel,
  pipelineDesigner: initialAppState_pipelineDesigner,
  isDark: true
};

function serializeStack(model) {
  let services = Belt_Array.map(model.components, comp => {
    let port = Belt_Option.mapWithDefault(comp.config["port"], "0", p => p);
    return "{\"name\":\"" + comp.id + "\",\"kind\":\"" + Model.componentTypeToString(comp.componentType) + "\",\"port\":" + port + "}";
  }).join(",");
  return "{\"name\":\"stapeln-stack\",\"services\":[" + services + "]}";
}

let socketConn = Socket.make();

let stackChannel = {
  contents: undefined
};

function App(props) {
  let match = React.useState(() => initialAppState);
  let setState = match[1];
  let state = match[0];
  let dispatch = msg => {
    let newModel = Update.update(state.model, msg);
    setState(prev => ({
      currentPage: prev.currentPage,
      model: newModel,
      pipelineDesigner: prev.pipelineDesigner,
      isDark: prev.isDark
    }));
    if (typeof msg !== "object") {
      switch (msg) {
        case "TriggerImportDesign" :
          return Import.triggerImport(importedModel => dispatch({
            TAG: "ImportDesignSuccess",
            _0: importedModel
          }), error => dispatch({
            TAG: "ImportDesignError",
            _0: error
          }));
        case "SaveStack" :
          let body = serializeStack(newModel);
          ApiClient.saveStack(body).then(result => {
            dispatch({
              TAG: "StackSaved",
              _0: result
            });
            return Promise.resolve();
          });
          return;
        case "RunSecurityScan" :
          let body$1 = serializeStack(newModel);
          Stdlib_Promise.$$catch(ApiClient.saveStack(body$1).then(saveResult => {
            if (saveResult.TAG === "Ok") {
              let id = Belt_Int.fromString(saveResult._0);
              let stackId = id !== undefined ? id : 0;
              return ApiClient.runSecurityScan(stackId).then(scanResult => {
                dispatch({
                  TAG: "SecurityScanResult",
                  _0: scanResult
                });
                return Promise.resolve();
              });
            }
            dispatch({
              TAG: "SecurityScanResult",
              _0: {
                TAG: "Error",
                _0: saveResult._0
              }
            });
            return Promise.resolve();
          }), param => {
            dispatch({
              TAG: "SecurityScanResult",
              _0: {
                TAG: "Error",
                _0: "Network error"
              }
            });
            return Promise.resolve();
          });
          return;
        case "RunGapAnalysis" :
          let body$2 = serializeStack(newModel);
          Stdlib_Promise.$$catch(ApiClient.saveStack(body$2).then(saveResult => {
            if (saveResult.TAG === "Ok") {
              let id = Belt_Int.fromString(saveResult._0);
              let stackId = id !== undefined ? id : 0;
              return ApiClient.runGapAnalysis(stackId).then(gapResult => {
                dispatch({
                  TAG: "GapAnalysisResult",
                  _0: gapResult
                });
                return Promise.resolve();
              });
            }
            dispatch({
              TAG: "GapAnalysisResult",
              _0: {
                TAG: "Error",
                _0: saveResult._0
              }
            });
            return Promise.resolve();
          }), param => {
            dispatch({
              TAG: "GapAnalysisResult",
              _0: {
                TAG: "Error",
                _0: "Network error"
              }
            });
            return Promise.resolve();
          });
          return;
        case "SaveSettings" :
          let settingsJson = Object.fromEntries([
            [
              "theme",
              newModel.settings.theme
            ],
            [
              "defaultRuntime",
              newModel.settings.defaultRuntime
            ],
            [
              "autoSave",
              newModel.settings.autoSave
            ],
            [
              "backendUrl",
              newModel.settings.backendUrl
            ]
          ]);
          ApiClient.saveSettings(settingsJson).then(result => {
            dispatch({
              TAG: "SettingsSaved",
              _0: result
            });
            return Promise.resolve();
          });
          return;
        case "LoadSettings" :
          ApiClient.loadSettings().then(result => {
            dispatch({
              TAG: "SettingsLoaded",
              _0: result
            });
            return Promise.resolve();
          });
          return;
        case "WsConnect" :
          Socket.onStateChange(socketConn, connState => dispatch({
            TAG: "WsConnectionStateChanged",
            _0: connState
          }));
          let ch = Socket.channel(socketConn, "stack:lobby");
          stackChannel.contents = ch;
          Socket.on(ch, "validation_result", payload => dispatch({
            TAG: "WsValidationResult",
            _0: payload
          }));
          Socket.on(ch, "security_result", payload => dispatch({
            TAG: "WsSecurityResult",
            _0: payload
          }));
          Socket.on(ch, "gap_result", payload => dispatch({
            TAG: "WsGapResult",
            _0: payload
          }));
          Socket.connect(socketConn, Socket.defaultUrl());
          return Socket.joinChannel(socketConn, ch);
        case "WsDisconnect" :
          let ch$1 = stackChannel.contents;
          if (ch$1 !== undefined) {
            Socket.leaveChannel(socketConn, ch$1);
          }
          stackChannel.contents = undefined;
          return Socket.disconnect(socketConn);
        case "WsValidate" :
          let ch$2 = stackChannel.contents;
          if (ch$2 !== undefined) {
            let stackJson = serializeStack(newModel);
            let payload = Object.fromEntries([[
                "stack",
                stackJson
              ]]);
            return Socket.push(socketConn, ch$2, "validate", payload);
          }
          console.warn("WebSocket not connected, cannot validate via WS");
          return;
        case "WsSecurityScan" :
          let ch$3 = stackChannel.contents;
          if (ch$3 !== undefined) {
            let stackJson$1 = serializeStack(newModel);
            let payload$1 = Object.fromEntries([[
                "stack",
                stackJson$1
              ]]);
            return Socket.push(socketConn, ch$3, "security_scan", payload$1);
          }
          console.warn("WebSocket not connected, cannot security scan via WS");
          return;
        case "WsGapAnalysis" :
          let ch$4 = stackChannel.contents;
          if (ch$4 !== undefined) {
            let stackJson$2 = serializeStack(newModel);
            let payload$2 = Object.fromEntries([[
                "stack",
                stackJson$2
              ]]);
            return Socket.push(socketConn, ch$4, "gap_analysis", payload$2);
          }
          console.warn("WebSocket not connected, cannot gap analysis via WS");
          return;
        default:
          return;
      }
    } else {
      if (msg.TAG !== "Pipeline") {
        return;
      }
      let pipelineMsg = msg._0;
      return setState(prev => {
        let newPState = PipelineUpdate.update(prev.pipelineDesigner, pipelineMsg);
        return {
          currentPage: prev.currentPage,
          model: prev.model,
          pipelineDesigner: newPState,
          isDark: prev.isDark
        };
      });
    }
  };
  let switchPage = page => {
    AppRouter.navigateTo(page);
    setState(prev => ({
      currentPage: page,
      model: prev.model,
      pipelineDesigner: prev.pipelineDesigner,
      isDark: prev.isDark
    }));
  };
  React.useEffect(() => {
    AppRouter.onRouteChange(route => setState(prev => ({
      currentPage: route,
      model: prev.model,
      pipelineDesigner: prev.pipelineDesigner,
      isDark: prev.isDark
    })));
  }, []);
  let match$1 = state.currentPage;
  let tmp;
  switch (match$1) {
    case "NetworkView" :
      tmp = TopologyView.view(state.model, state.isDark, dispatch);
      break;
    case "StackView" :
      tmp = StackView.view(state.model, state.isDark);
      break;
    case "PipelineView" :
      tmp = JsxRuntime.jsx(PipelineDesigner.make, {
        state: state.pipelineDesigner,
        dispatch: pMsg => dispatch({
          TAG: "Pipeline",
          _0: pMsg
        })
      });
      break;
    case "LagoGreyView" :
      tmp = JsxRuntime.jsx(LagoGreyImageDesigner.make, {});
      break;
    case "PortConfigView" :
      tmp = JsxRuntime.jsx(PortConfigPanel.make, {});
      break;
    case "SecurityView" :
      tmp = JsxRuntime.jsx(SecurityInspector.make, {
        initialState: state.model.securityState
      });
      break;
    case "GapAnalysisView" :
      tmp = JsxRuntime.jsx(GapAnalysis.make, {
        initialState: state.model.gapState
      });
      break;
    case "SimulationView" :
      tmp = JsxRuntime.jsx(SimulationMode.make, {});
      break;
    case "SettingsView" :
      tmp = JsxRuntime.jsx(SettingsPage.make, {
        settings: state.model.settings,
        isDark: state.isDark,
        onSave: () => dispatch("SaveSettings"),
        onSettingsChange: newSettings => setState(prev => {
          let init = prev.model;
          return {
            currentPage: prev.currentPage,
            model: {
              components: init.components,
              connections: init.connections,
              selectedComponent: init.selectedComponent,
              dragState: init.dragState,
              canvasOffset: init.canvasOffset,
              zoomLevel: init.zoomLevel,
              validationResult: init.validationResult,
              securityState: init.securityState,
              gapState: init.gapState,
              securityLoading: init.securityLoading,
              gapLoading: init.gapLoading,
              currentStackId: init.currentStackId,
              settings: newSettings,
              wsState: init.wsState
            },
            pipelineDesigner: prev.pipelineDesigner,
            isDark: newSettings.theme === "dark"
          };
        })
      });
      break;
    case "NotFound" :
      tmp = JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h1", {
            children: "404",
            style: {
              color: "#64b5f6",
              fontSize: "3rem",
              marginBottom: "1rem"
            }
          }),
          JsxRuntime.jsx("p", {
            children: "Page not found",
            style: {
              color: "#8892a6",
              marginBottom: "2rem"
            }
          }),
          JsxRuntime.jsx("button", {
            children: "Go to Network View",
            className: "action-btn",
            onClick: param => switchPage("NetworkView")
          })
        ],
        className: "page",
        style: {
          paddingTop: "4rem",
          textAlign: "center"
        }
      });
      break;
  }
  return JsxRuntime.jsx(ErrorBoundary.make, {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsxs("nav", {
          children: [
            JsxRuntime.jsx("button", {
              children: "🌐 Network",
              className: state.currentPage === "NetworkView" ? "tab active" : "tab",
              onClick: param => switchPage("NetworkView")
            }),
            JsxRuntime.jsx("button", {
              children: "📚 Stack",
              className: state.currentPage === "StackView" ? "tab active" : "tab",
              onClick: param => switchPage("StackView")
            }),
            JsxRuntime.jsx("button", {
              children: "🔧 Pipeline",
              className: state.currentPage === "PipelineView" ? "tab active" : "tab",
              onClick: param => switchPage("PipelineView")
            }),
            JsxRuntime.jsx("button", {
              children: "🏔️ Lago Grey",
              className: state.currentPage === "LagoGreyView" ? "tab active" : "tab",
              onClick: param => switchPage("LagoGreyView")
            }),
            JsxRuntime.jsx("button", {
              children: "🔌 Ports",
              className: state.currentPage === "PortConfigView" ? "tab active" : "tab",
              onClick: param => switchPage("PortConfigView")
            }),
            JsxRuntime.jsx("button", {
              children: "🛡️ Security",
              className: state.currentPage === "SecurityView" ? "tab active" : "tab",
              onClick: param => switchPage("SecurityView")
            }),
            JsxRuntime.jsx("button", {
              children: "🔍 Gaps",
              className: state.currentPage === "GapAnalysisView" ? "tab active" : "tab",
              onClick: param => switchPage("GapAnalysisView")
            }),
            JsxRuntime.jsx("button", {
              children: "🎮 Simulation",
              className: state.currentPage === "SimulationView" ? "tab active" : "tab",
              onClick: param => switchPage("SimulationView")
            }),
            JsxRuntime.jsx("button", {
              children: "⚙️ Settings",
              className: state.currentPage === "SettingsView" ? "tab active" : "tab",
              onClick: param => switchPage("SettingsView")
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                  children: "📂 Import",
                  className: "action-btn",
                  title: "Import design from JSON file",
                  onClick: param => dispatch("TriggerImportDesign")
                }),
                JsxRuntime.jsx("button", {
                  children: "💾 Export",
                  className: "action-btn",
                  title: "Export design to JSON file",
                  onClick: param => dispatch({
                    TAG: "ExportDesignToJson",
                    _0: "Stack design"
                  })
                })
              ],
              className: "nav-actions"
            })
          ],
          className: "nav-tabs"
        }),
        JsxRuntime.jsx("div", {
          children: tmp,
          className: "content"
        }),
        JsxRuntime.jsx("div", {
          children: JsxRuntime.jsx(IdrisBadge.make, {
            style: "Compact"
          }),
          style: {
            bottom: "16px",
            position: "fixed",
            right: "16px",
            zIndex: "1000"
          }
        })
      ],
      className: "app"
    })
  });
}

let make = App;

export {
  initialAppState,
  serializeStack,
  socketConn,
  stackChannel,
  make,
}
/* initialAppState Not a pure module */
