// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";

function routeToPath(route) {
  switch (route) {
    case "LoginView" :
      return "/login";
    case "RegisterView" :
      return "/register";
    case "NetworkView" :
      return "/";
    case "StackView" :
      return "/stack";
    case "PipelineView" :
      return "/pipeline";
    case "LagoGreyView" :
      return "/lago-grey";
    case "PortConfigView" :
      return "/ports";
    case "SecurityView" :
      return "/security";
    case "GapAnalysisView" :
      return "/gaps";
    case "SimulationView" :
      return "/simulation";
    case "SettingsView" :
      return "/settings";
    case "NotFound" :
      return "/404";
  }
}

function pathToRoute(path) {
  switch (path) {
    case "/" :
      return "NetworkView";
    case "/gaps" :
      return "GapAnalysisView";
    case "/lago-grey" :
      return "LagoGreyView";
    case "/login" :
      return "LoginView";
    case "/pipeline" :
      return "PipelineView";
    case "/ports" :
      return "PortConfigView";
    case "/register" :
      return "RegisterView";
    case "/security" :
      return "SecurityView";
    case "/settings" :
      return "SettingsView";
    case "/simulation" :
      return "SimulationView";
    case "/stack" :
      return "StackView";
    default:
      return "NotFound";
  }
}

function getCurrentRoute() {
  return pathToRoute(window.location.pathname);
}

function navigateTo(route) {
  routeToPath(route);
  ((window.history.pushState(null, "", _path)));
  ((window.dispatchEvent(new PopStateEvent('popstate'))));
}

function replaceRoute(route) {
  routeToPath(route);
  ((window.history.replaceState(null, "", _path)));
}

function goBack() {
  ((window.history.back()));
}

function goForward() {
  ((window.history.forward()));
}

function onRouteChange(callback) {
  ((window.addEventListener('popstate', _handler)));
}

let navigationItems = [
  {
    route: "NetworkView",
    label: "Network",
    icon: "🌐",
    description: "Network topology view"
  },
  {
    route: "StackView",
    label: "Stack",
    icon: "📦",
    description: "Vertical stack view"
  },
  {
    route: "PipelineView",
    label: "Pipeline",
    icon: "🔧",
    description: "Assembly pipeline designer"
  },
  {
    route: "LagoGreyView",
    label: "Lago Grey",
    icon: "🏔️",
    description: "Base image designer"
  },
  {
    route: "PortConfigView",
    label: "Ports",
    icon: "🔌",
    description: "Port configuration"
  },
  {
    route: "SecurityView",
    label: "Security",
    icon: "🔐",
    description: "Security inspector"
  },
  {
    route: "GapAnalysisView",
    label: "Gaps",
    icon: "📊",
    description: "Gap analysis"
  },
  {
    route: "SimulationView",
    label: "Simulation",
    icon: "🎮",
    description: "Network simulation"
  },
  {
    route: "SettingsView",
    label: "Settings",
    icon: "⚙️",
    description: "Application settings"
  }
];

function getRouteMeta(route) {
  return Belt_Array.getBy(navigationItems, item => item.route === route);
}

function getRouteLabel(route) {
  let meta = getRouteMeta(route);
  if (meta !== undefined) {
    return meta.label;
  } else {
    return "Unknown";
  }
}

function getRouteIcon(route) {
  let meta = getRouteMeta(route);
  if (meta !== undefined) {
    return meta.icon;
  } else {
    return "❓";
  }
}

export {
  routeToPath,
  pathToRoute,
  getCurrentRoute,
  navigateTo,
  replaceRoute,
  goBack,
  goForward,
  onRouteChange,
  navigationItems,
  getRouteMeta,
  getRouteLabel,
  getRouteIcon,
}
/* No side effect */
