// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_SortArray from "@rescript/runtime/lib/es6/Belt_SortArray.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as JsxRuntime from "react/jsx-runtime";

let emptySummary = {
  totalEntries: 0,
  criticalCount: 0,
  highCount: 0,
  mediumCount: 0,
  lowCount: 0,
  publiclyExposed: 0
};

let init_entries = [];

let init = {
  entries: init_entries,
  summary: emptySummary,
  selectedEntry: undefined,
  filterRisk: undefined,
  filterCategory: undefined,
  searchQuery: "",
  loading: false,
  error: undefined
};

function riskLabel(risk) {
  switch (risk) {
    case "Critical" :
      return "Critical";
    case "High" :
      return "High";
    case "Medium" :
      return "Medium";
    case "Low" :
      return "Low";
    case "Info" :
      return "Info";
  }
}

function riskColor(risk) {
  switch (risk) {
    case "Critical" :
      return "#d32f2f";
    case "High" :
      return "#f57c00";
    case "Medium" :
      return "#fbc02d";
    case "Low" :
      return "#388e3c";
    case "Info" :
      return "#1976d2";
  }
}

function riskRank(risk) {
  switch (risk) {
    case "Critical" :
      return 5;
    case "High" :
      return 4;
    case "Medium" :
      return 3;
    case "Low" :
      return 2;
    case "Info" :
      return 1;
  }
}

function categoryIcon(category) {
  switch (category) {
    case "boundary" :
      return "📦";
    case "endpoint" :
      return "🌐";
    case "interface" :
      return "🔗";
    case "port" :
      return "🔌";
    default:
      return "🔍";
  }
}

function categoryLabel(category) {
  switch (category) {
    case "boundary" :
      return "Container Boundary";
    case "endpoint" :
      return "Service Endpoint";
    case "interface" :
      return "Network Interface";
    case "port" :
      return "Exposed Port";
    default:
      return "Unknown";
  }
}

function entryFromExposedPort(ep, idx) {
  let match = ep.risk;
  let risk;
  switch (match) {
    case "Critical" :
    case "critical" :
      risk = "Critical";
      break;
    case "High" :
    case "high" :
      risk = "High";
      break;
    case "Medium" :
    case "medium" :
      risk = "Medium";
      break;
    default:
      risk = "Low";
  }
  return {
    id: "port-" + String(idx),
    category: "port",
    name: "Port " + String(ep.port) + " (" + ep.protocol + ")",
    description: "Service '" + ep.service + "' exposes port " + String(ep.port) + " via " + ep.protocol + ".",
    risk: risk,
    component: ep.service,
    protocol: ep.protocol,
    port: ep.port,
    publiclyExposed: ep.publiclyAccessible,
    mitigations: ep.publiclyAccessible ? [
        "Remove public binding if internal-only",
        "Add firewall rules to restrict source IPs",
        "Route through Svalinn edge gateway"
      ] : ["Monitor for unexpected connections"]
  };
}

function entryFromVulnerability(vuln, idx) {
  let match = vuln.severity;
  let risk;
  switch (match) {
    case "Critical" :
      risk = "Critical";
      break;
    case "High" :
      risk = "High";
      break;
    case "Medium" :
      risk = "Medium";
      break;
    case "Low" :
      risk = "Low";
      break;
    case "Info" :
      risk = "Info";
      break;
  }
  let desc = vuln.fixDescription;
  let mitigations = desc !== undefined ? [desc] : ["Manual review required"];
  return {
    id: "vuln-" + String(idx),
    category: "endpoint",
    name: vuln.title,
    description: vuln.description,
    risk: risk,
    component: vuln.affectedComponent,
    protocol: undefined,
    port: undefined,
    publiclyExposed: risk === "Critical",
    mitigations: mitigations
  };
}

function entryFromFailedCheck(check, idx) {
  let match = check.result;
  switch (match) {
    case "Fail" :
      return {
        id: "boundary-" + String(idx),
        category: "boundary",
        name: check.name + " (Failed)",
        description: check.description + " — " + check.details,
        risk: "High",
        component: "stack",
        protocol: undefined,
        port: undefined,
        publiclyExposed: false,
        mitigations: ["Address the failing check to reduce attack surface"]
      };
    case "Warning" :
      return {
        id: "boundary-" + String(idx),
        category: "boundary",
        name: check.name + " (Warning)",
        description: check.description + " — " + check.details,
        risk: "Medium",
        component: "stack",
        protocol: undefined,
        port: undefined,
        publiclyExposed: false,
        mitigations: ["Review and improve configuration"]
      };
    case "Pass" :
    case "Unknown" :
      return;
  }
}

function fromSecurityState(secState) {
  let portEntries = Belt_Array.mapWithIndex(secState.exposedPorts, (idx, ep) => entryFromExposedPort(ep, idx));
  let vulnEntries = Belt_Array.mapWithIndex(secState.vulnerabilities, (idx, vuln) => entryFromVulnerability(vuln, idx));
  let boundaryEntries = Belt_Array.reduce(Belt_Array.mapWithIndex(secState.checks, (idx, check) => entryFromFailedCheck(check, idx)), [], (acc, opt) => {
    if (opt !== undefined) {
      return Belt_Array.concat(acc, [opt]);
    } else {
      return acc;
    }
  });
  let allEntries = Belt_Array.concatMany([
    portEntries,
    vulnEntries,
    boundaryEntries
  ]);
  let sorted = Belt_SortArray.stableSortBy(allEntries, (a, b) => riskRank(b.risk) - riskRank(a.risk) | 0);
  let summary_totalEntries = sorted.length;
  let summary_criticalCount = Belt_Array.reduce(sorted, 0, (acc, e) => {
    if (e.risk === "Critical") {
      return acc + 1 | 0;
    } else {
      return acc;
    }
  });
  let summary_highCount = Belt_Array.reduce(sorted, 0, (acc, e) => {
    if (e.risk === "High") {
      return acc + 1 | 0;
    } else {
      return acc;
    }
  });
  let summary_mediumCount = Belt_Array.reduce(sorted, 0, (acc, e) => {
    if (e.risk === "Medium") {
      return acc + 1 | 0;
    } else {
      return acc;
    }
  });
  let summary_lowCount = Belt_Array.reduce(sorted, 0, (acc, e) => {
    if (e.risk === "Low" || e.risk === "Info") {
      return acc + 1 | 0;
    } else {
      return acc;
    }
  });
  let summary_publiclyExposed = Belt_Array.reduce(sorted, 0, (acc, e) => {
    if (e.publiclyExposed) {
      return acc + 1 | 0;
    } else {
      return acc;
    }
  });
  let summary = {
    totalEntries: summary_totalEntries,
    criticalCount: summary_criticalCount,
    highCount: summary_highCount,
    mediumCount: summary_mediumCount,
    lowCount: summary_lowCount,
    publiclyExposed: summary_publiclyExposed
  };
  return {
    entries: sorted,
    summary: summary,
    selectedEntry: undefined,
    filterRisk: undefined,
    filterCategory: undefined,
    searchQuery: "",
    loading: false,
    error: undefined
  };
}

function update(msg, state) {
  if (typeof msg !== "object") {
    if (msg === "ClearSelection") {
      return {
        entries: state.entries,
        summary: state.summary,
        selectedEntry: undefined,
        filterRisk: state.filterRisk,
        filterCategory: state.filterCategory,
        searchQuery: state.searchQuery,
        loading: state.loading,
        error: state.error
      };
    } else {
      return state;
    }
  }
  switch (msg.TAG) {
    case "SelectEntry" :
      return {
        entries: state.entries,
        summary: state.summary,
        selectedEntry: msg._0,
        filterRisk: state.filterRisk,
        filterCategory: state.filterCategory,
        searchQuery: state.searchQuery,
        loading: state.loading,
        error: state.error
      };
    case "FilterByRisk" :
      return {
        entries: state.entries,
        summary: state.summary,
        selectedEntry: state.selectedEntry,
        filterRisk: msg._0,
        filterCategory: state.filterCategory,
        searchQuery: state.searchQuery,
        loading: state.loading,
        error: state.error
      };
    case "FilterByCategory" :
      return {
        entries: state.entries,
        summary: state.summary,
        selectedEntry: state.selectedEntry,
        filterRisk: state.filterRisk,
        filterCategory: msg._0,
        searchQuery: state.searchQuery,
        loading: state.loading,
        error: state.error
      };
    case "SetSearchQuery" :
      return {
        entries: state.entries,
        summary: state.summary,
        selectedEntry: state.selectedEntry,
        filterRisk: state.filterRisk,
        filterCategory: state.filterCategory,
        searchQuery: msg._0,
        loading: state.loading,
        error: state.error
      };
  }
}

function viewSummaryCard(label, count, color) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: String(count),
        style: {
          color: color,
          fontSize: "36px",
          fontWeight: "700",
          marginBottom: "8px"
        }
      }),
      JsxRuntime.jsx("div", {
        children: label,
        style: {
          color: "#8892a6",
          fontSize: "13px"
        }
      })
    ],
    style: {
      background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
      border: "2px solid #2a3142",
      borderRadius: "12px",
      padding: "20px",
      textAlign: "center"
    }
  }, label);
}

function viewRiskFilter(label, value, current, color, dispatch) {
  let isActive = Primitive_object.equal(current, value);
  return JsxRuntime.jsx("button", {
    children: label,
    style: {
      background: isActive ? color : "transparent",
      border: "1px solid " + color,
      borderRadius: "6px",
      color: isActive ? "white" : color,
      cursor: "pointer",
      fontSize: "12px",
      fontWeight: "600",
      padding: "8px 16px",
      transition: "all 0.2s"
    },
    onClick: param => dispatch({
      TAG: "FilterByRisk",
      _0: value
    })
  }, label);
}

function viewCategoryFilter(label, icon, value, current, dispatch) {
  let isActive = Primitive_object.equal(current, value);
  return JsxRuntime.jsx("button", {
    children: icon + " " + label,
    style: {
      background: isActive ? "linear-gradient(135deg, #4a9eff, #7b6cff)" : "transparent",
      border: isActive ? "1px solid #4a9eff" : "1px solid #2a3142",
      borderRadius: "6px",
      color: isActive ? "white" : "#8892a6",
      cursor: "pointer",
      fontSize: "12px",
      fontWeight: "600",
      padding: "8px 16px",
      transition: "all 0.2s"
    },
    onClick: param => dispatch({
      TAG: "FilterByCategory",
      _0: value
    })
  }, label);
}

function viewEntry(entry, isSelected, dispatch) {
  let match = entry.protocol;
  let match$1 = entry.port;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: categoryIcon(entry.category) + " " + categoryLabel(entry.category),
            style: {
              background: "#2a3142",
              borderRadius: "6px",
              color: "#8892a6",
              fontSize: "11px",
              fontWeight: "600",
              padding: "4px 10px"
            }
          }),
          JsxRuntime.jsx("span", {
            children: riskLabel(entry.risk),
            style: {
              background: riskColor(entry.risk),
              borderRadius: "6px",
              color: "white",
              fontSize: "11px",
              fontWeight: "700",
              padding: "4px 12px",
              textTransform: "uppercase"
            }
          }),
          entry.publiclyExposed ? JsxRuntime.jsx("span", {
              children: "PUBLIC",
              style: {
                background: "rgba(244, 67, 54, 0.2)",
                border: "1px solid #f44336",
                borderRadius: "4px",
                color: "#f44336",
                fontSize: "10px",
                fontWeight: "600",
                padding: "4px 8px"
              }
            }) : null,
          match !== undefined ? (
              match$1 !== undefined ? JsxRuntime.jsx("span", {
                  children: match + ":" + String(match$1),
                  style: {
                    color: "#6b7a90",
                    fontSize: "11px"
                  }
                }) : JsxRuntime.jsx("span", {
                  children: match,
                  style: {
                    color: "#6b7a90",
                    fontSize: "11px"
                  }
                })
            ) : null
        ],
        style: {
          alignItems: "center",
          display: "flex",
          flexWrap: "wrap",
          gap: "8px",
          marginBottom: "10px"
        }
      }),
      JsxRuntime.jsx("div", {
        children: entry.name,
        style: {
          color: "#e0e6ed",
          fontSize: "15px",
          fontWeight: "700",
          marginBottom: "6px"
        }
      }),
      JsxRuntime.jsx("div", {
        children: entry.description,
        style: {
          color: "#8892a6",
          fontSize: "13px",
          lineHeight: "1.5",
          marginBottom: "10px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          "Component: ",
          JsxRuntime.jsx("strong", {
            children: entry.component,
            style: {
              color: "#4a9eff"
            }
          })
        ],
        style: {
          color: "#6b7a90",
          fontSize: "12px",
          marginBottom: "10px"
        }
      }),
      isSelected && entry.mitigations.length !== 0 ? JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: "Recommended Mitigations:",
              style: {
                color: "#4caf50",
                fontSize: "12px",
                fontWeight: "700",
                marginBottom: "8px"
              }
            }),
            JsxRuntime.jsx("ul", {
              children: Belt_Array.map(entry.mitigations, m => JsxRuntime.jsx("li", {
                children: m
              }, m)),
              style: {
                color: "#b0b8c4",
                fontSize: "12px",
                lineHeight: "1.8",
                listStyle: "disc",
                paddingLeft: "20px"
              }
            })
          ],
          style: {
            background: "rgba(76, 175, 80, 0.1)",
            border: "1px solid #4caf50",
            borderRadius: "8px",
            marginTop: "8px",
            padding: "12px"
          }
        }) : null
    ],
    style: {
      background: isSelected ? "linear-gradient(135deg, #1e2c40 0%, #253550 100%)" : "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
      border: isSelected ? "2px solid #4a9eff" : "2px solid #2a3142",
      borderRadius: "12px",
      cursor: "pointer",
      marginBottom: "12px",
      padding: "16px 20px",
      transition: "all 0.2s"
    },
    onClick: param => dispatch({
      TAG: "SelectEntry",
      _0: entry.id
    })
  }, entry.id);
}

function AttackSurfacePage(props) {
  let securityState = props.securityState;
  let match = React.useState(() => {
    if (securityState !== undefined) {
      return fromSecurityState(securityState);
    } else {
      return init;
    }
  });
  let setState = match[1];
  let state = match[0];
  React.useEffect(() => {
    if (securityState !== undefined) {
      setState(param => fromSecurityState(securityState));
    }
  }, [securityState]);
  let dispatch = msg => setState(prev => update(msg, prev));
  let filteredEntries = Belt_Array.reduce(state.entries, [], (acc, entry) => {
    let r = state.filterRisk;
    let matchesRisk = r !== undefined ? entry.risk === r : true;
    let c = state.filterCategory;
    let matchesCategory = c !== undefined ? entry.category === c : true;
    let matchesSearch = state.searchQuery === "" || entry.name.toLowerCase().includes(state.searchQuery.toLowerCase()) || entry.description.toLowerCase().includes(state.searchQuery.toLowerCase()) || entry.component.toLowerCase().includes(state.searchQuery.toLowerCase());
    if (matchesRisk && matchesCategory && matchesSearch) {
      return Belt_Array.concat(acc, [entry]);
    } else {
      return acc;
    }
  });
  let isEmpty = state.entries.length === 0;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h1", {
            children: "🎯 Attack Surface Analyzer",
            style: {
              background: "linear-gradient(135deg, #ff5722, #ff9800)",
              fontSize: "32px",
              fontWeight: "700",
              marginBottom: "8px"
            }
          }),
          JsxRuntime.jsx("p", {
            children: "Comprehensive view of exposed ports, service endpoints, network interfaces, and container boundaries",
            style: {
              color: "#8892a6",
              fontSize: "16px"
            }
          })
        ],
        style: {
          marginBottom: "32px"
        }
      }),
      isEmpty ? JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: "🎯",
              style: {
                fontSize: "48px",
                marginBottom: "16px"
              }
            }),
            JsxRuntime.jsx("h2", {
              children: "No attack surface data yet",
              style: {
                color: "#e0e6ed",
                fontSize: "20px",
                fontWeight: "700",
                marginBottom: "12px"
              }
            }),
            JsxRuntime.jsx("p", {
              children: "Run a security scan first to populate the attack surface analysis. The analyzer will map exposed ports, service endpoints, network interfaces, and container boundaries across your entire stack.",
              style: {
                color: "#8892a6",
                fontSize: "14px",
                lineHeight: "1.6",
                marginBottom: "24px"
              }
            })
          ],
          style: {
            background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
            border: "2px dashed #2a3f5f",
            borderRadius: "16px",
            padding: "60px 40px",
            textAlign: "center"
          }
        }) : null,
      isEmpty ? null : JsxRuntime.jsxs(JsxRuntime.Fragment, {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                viewSummaryCard("Total Surface", state.summary.totalEntries, "#4a9eff"),
                viewSummaryCard("Critical", state.summary.criticalCount, "#d32f2f"),
                viewSummaryCard("High Risk", state.summary.highCount, "#f57c00"),
                viewSummaryCard("Publicly Exposed", state.summary.publiclyExposed, "#f44336")
              ],
              style: {
                display: "grid",
                gap: "16px",
                gridTemplateColumns: "repeat(4, 1fr)",
                marginBottom: "32px"
              }
            }),
            JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("input", {
                style: {
                  background: "#1e2431",
                  border: "2px solid #2a3142",
                  borderRadius: "8px",
                  color: "#e0e6ed",
                  fontSize: "14px",
                  padding: "12px 16px",
                  width: "100%"
                },
                placeholder: "Search by name, description, or component...",
                type: "text",
                value: state.searchQuery,
                onChange: e => {
                  let value = e.target.value;
                  let msg = {
                    TAG: "SetSearchQuery",
                    _0: value
                  };
                  setState(prev => update(msg, prev));
                }
              }),
              style: {
                marginBottom: "16px"
              }
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                  children: [
                    viewRiskFilter("All", undefined, state.filterRisk, "#4a9eff", dispatch),
                    viewRiskFilter("Critical", "Critical", state.filterRisk, "#d32f2f", dispatch),
                    viewRiskFilter("High", "High", state.filterRisk, "#f57c00", dispatch),
                    viewRiskFilter("Medium", "Medium", state.filterRisk, "#fbc02d", dispatch),
                    viewRiskFilter("Low", "Low", state.filterRisk, "#388e3c", dispatch)
                  ],
                  style: {
                    display: "flex",
                    flexWrap: "wrap",
                    gap: "8px"
                  }
                }),
                JsxRuntime.jsxs("div", {
                  children: [
                    viewCategoryFilter("All", "🔍", undefined, state.filterCategory, dispatch),
                    viewCategoryFilter("Ports", "🔌", "port", state.filterCategory, dispatch),
                    viewCategoryFilter("Endpoints", "🌐", "endpoint", state.filterCategory, dispatch),
                    viewCategoryFilter("Boundaries", "📦", "boundary", state.filterCategory, dispatch)
                  ],
                  style: {
                    display: "flex",
                    flexWrap: "wrap",
                    gap: "8px"
                  }
                })
              ],
              style: {
                alignItems: "center",
                background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
                border: "2px solid #2a3142",
                borderRadius: "12px",
                display: "flex",
                flexWrap: "wrap",
                gap: "12px",
                justifyContent: "space-between",
                marginBottom: "24px",
                padding: "16px"
              }
            }),
            JsxRuntime.jsxs("div", {
              children: [
                "Showing ",
                JsxRuntime.jsx("strong", {
                  children: String(filteredEntries.length),
                  style: {
                    color: "#e0e6ed"
                  }
                }),
                " of ",
                JsxRuntime.jsx("strong", {
                  children: String(state.summary.totalEntries),
                  style: {
                    color: "#e0e6ed"
                  }
                }),
                " attack surface entries"
              ],
              style: {
                color: "#6b7a90",
                fontSize: "13px",
                marginBottom: "16px"
              }
            }),
            JsxRuntime.jsx("div", {
              children: filteredEntries.length !== 0 ? Belt_Array.map(filteredEntries, entry => viewEntry(entry, Primitive_object.equal(state.selectedEntry, entry.id), dispatch)) : JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("div", {
                      children: "🔎",
                      style: {
                        fontSize: "32px",
                        marginBottom: "12px"
                      }
                    }),
                    JsxRuntime.jsx("div", {
                      children: "No entries match the current filters",
                      style: {
                        color: "#8892a6",
                        fontSize: "16px",
                        fontWeight: "600"
                      }
                    })
                  ],
                  style: {
                    background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
                    border: "2px solid #2a3142",
                    borderRadius: "12px",
                    padding: "40px",
                    textAlign: "center"
                  }
                })
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h4", {
                  children: "🎯 Attack Surface Intelligence",
                  style: {
                    color: "#ff5722",
                    fontSize: "16px",
                    fontWeight: "700",
                    marginBottom: "12px"
                  }
                }),
                JsxRuntime.jsx("p", {
                  children: "Attack surface data aggregated from the security scanner, miniKanren reasoning engine, and container boundary analysis. Each entry includes risk categorization and actionable mitigations. Publicly exposed surfaces are flagged for immediate review. All findings logged to VeriSimDB for compliance audit.",
                  style: {
                    color: "#b0b8c4",
                    fontSize: "13px",
                    lineHeight: "1.8"
                  }
                })
              ],
              style: {
                background: "rgba(255, 87, 34, 0.1)",
                border: "2px solid #ff5722",
                borderRadius: "12px",
                marginTop: "32px",
                padding: "20px"
              }
            })
          ]
        })
    ],
    className: "attack-surface-page",
    style: {
      background: "#0a0e1a",
      minHeight: "100vh",
      padding: "32px"
    }
  });
}

let make = AttackSurfacePage;

export {
  emptySummary,
  init,
  riskLabel,
  riskColor,
  riskRank,
  categoryIcon,
  categoryLabel,
  entryFromExposedPort,
  entryFromVulnerability,
  entryFromFailedCheck,
  fromSecurityState,
  update,
  viewSummaryCard,
  viewRiskFilter,
  viewCategoryFilter,
  viewEntry,
  make,
}
/* react Not a pure module */
