// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function primaryFix(label, action) {
  return {
    label: label,
    action: action,
    isPrimary: true
  };
}

function secondaryFix(label, action) {
  return {
    label: label,
    action: action,
    isPrimary: false
  };
}

function severityIcon(s) {
  switch (s) {
    case "Critical" :
      return "!";
    case "Warning" :
      return "~";
    case "Info" :
      return "i";
  }
}

function severityColor(s) {
  switch (s) {
    case "Critical" :
      return "#ef5350";
    case "Warning" :
      return "#ffa726";
    case "Info" :
      return "#42a5f5";
  }
}

function severityBg(s) {
  switch (s) {
    case "Critical" :
      return "rgba(239, 83, 80, 0.08)";
    case "Warning" :
      return "rgba(255, 167, 38, 0.08)";
    case "Info" :
      return "rgba(66, 165, 245, 0.08)";
  }
}

function ConversationalError(props) {
  let onDismiss = props.onDismiss;
  let __severity = props.severity;
  let __fixes = props.fixes;
  let reason = props.reason;
  let __fixes_value = __fixes !== undefined ? __fixes : [];
  let __severity_value = __severity !== undefined ? __severity : "Warning";
  let color = severityColor(__severity_value);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: severityIcon(__severity_value),
            style: {
              background: color,
              borderRadius: "50%",
              color: "white",
              display: "flex",
              fontSize: "16px",
              fontWeight: "700",
              height: "28px",
              justifyContent: "center",
              lineHeight: "28px",
              textAlign: "center",
              width: "28px"
            }
          }),
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("div", {
              children: props.title,
              style: {
                color: "#e0e6ed",
                fontSize: "15px",
                fontWeight: "600",
                lineHeight: "1.4"
              }
            }),
            style: {
              flex: "1"
            }
          }),
          onDismiss !== undefined ? JsxRuntime.jsx("button", {
              children: "x",
              "aria-label": "Dismiss error",
              style: {
                background: "transparent",
                border: "none",
                color: "#8892a6",
                cursor: "pointer",
                fontSize: "18px",
                lineHeight: "1",
                padding: "0"
              },
              onClick: param => onDismiss()
            }) : null
        ],
        style: {
          alignItems: "flex-start",
          display: "flex",
          gap: "12px",
          marginBottom: reason !== undefined ? "12px" : (
              __fixes_value.length !== 0 ? "16px" : "0"
            )
        }
      }),
      reason !== undefined ? JsxRuntime.jsx("p", {
          children: reason,
          style: {
            color: "#8892a6",
            fontSize: "13px",
            lineHeight: "1.5",
            margin: "0",
            marginBottom: __fixes_value.length !== 0 ? "16px" : "0",
            paddingLeft: "40px"
          }
        }) : null,
      __fixes_value.length !== 0 ? JsxRuntime.jsx("div", {
          children: Belt_Array.mapWithIndex(Belt_Array.slice(__fixes_value, 0, 3), (idx, fix) => JsxRuntime.jsx("button", {
            children: fix.label,
            "aria-label": fix.label,
            style: {
              background: fix.isPrimary ? color : "transparent",
              border: fix.isPrimary ? "none" : "1px solid " + color,
              borderRadius: "8px",
              color: fix.isPrimary ? "white" : color,
              cursor: "pointer",
              fontSize: "13px",
              fontWeight: "600",
              padding: "8px 16px",
              transition: "all 0.2s"
            },
            onClick: param => fix.action()
          }, String(idx))),
          style: {
            display: "flex",
            flexWrap: "wrap",
            gap: "8px",
            paddingLeft: "40px"
          }
        }) : null
    ],
    "aria-live": "assertive",
    role: "alert",
    style: {
      background: severityBg(__severity_value),
      border: "2px solid " + color,
      borderRadius: "12px",
      marginBottom: "16px",
      padding: "20px"
    }
  });
}

let make = ConversationalError;

export {
  primaryFix,
  secondaryFix,
  severityIcon,
  severityColor,
  severityBg,
  make,
}
/* react/jsx-runtime Not a pure module */
