// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Model from "./Model.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

function componentToJson(comp) {
  let configJson = Object.fromEntries(Belt_Array.map(Object.entries(comp.config), param => [
    param[0],
    param[1]
  ]));
  return Object.fromEntries([
    [
      "id",
      comp.id
    ],
    [
      "type",
      Model.componentTypeToString(comp.componentType)
    ],
    [
      "position",
      Object.fromEntries([
        [
          "x",
          comp.position.x
        ],
        [
          "y",
          comp.position.y
        ]
      ])
    ],
    [
      "config",
      configJson
    ]
  ]);
}

function componentFromJson(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return;
  }
  let id = Belt_Option.flatMap(json["id"], Stdlib_JSON.Decode.string);
  let typeStr = Belt_Option.flatMap(json["type"], Stdlib_JSON.Decode.string);
  let position = Belt_Option.flatMap(json["position"], posJson => {
    if (typeof posJson !== "object" || posJson === null || Array.isArray(posJson)) {
      return;
    }
    let x = Belt_Option.flatMap(posJson["x"], Stdlib_JSON.Decode.float);
    let y = Belt_Option.flatMap(posJson["y"], Stdlib_JSON.Decode.float);
    if (x !== undefined && y !== undefined) {
      return {
        x: x,
        y: y
      };
    }
  });
  let config = Belt_Option.flatMap(json["config"], cfg => {
    if (typeof cfg !== "object" || cfg === null || Array.isArray(cfg)) {
      return;
    }
    let stringDict = {};
    Belt_Array.forEach(Object.entries(cfg), param => {
      let str = Stdlib_JSON.Decode.string(param[1]);
      if (str !== undefined) {
        stringDict[param[0]] = str;
        return;
      }
    });
    return stringDict;
  });
  let componentType;
  if (typeStr !== undefined) {
    switch (typeStr) {
      case "Cerro Torre" :
        componentType = "CerroTorre";
        break;
      case "Docker" :
        componentType = "Docker";
        break;
      case "Lago Grey" :
        componentType = "LagoGrey";
        break;
      case "Network" :
        componentType = "Network";
        break;
      case "Podman" :
        componentType = "Podman";
        break;
      case "Svalinn" :
        componentType = "Svalinn";
        break;
      case "Volume" :
        componentType = "Volume";
        break;
      case "Vörðr" :
        componentType = "Vordr";
        break;
      case "nerdctl" :
        componentType = "Nerdctl";
        break;
      case "selur" :
        componentType = "Selur";
        break;
      default:
        componentType = undefined;
    }
  } else {
    componentType = undefined;
  }
  if (id !== undefined && componentType !== undefined && position !== undefined && config !== undefined) {
    return {
      id: id,
      componentType: componentType,
      position: position,
      config: config
    };
  }
}

function connectionToJson(conn) {
  return Object.fromEntries([
    [
      "id",
      conn.id
    ],
    [
      "from",
      conn.from
    ],
    [
      "to",
      conn.to
    ]
  ]);
}

function connectionFromJson(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return;
  }
  let id = Belt_Option.flatMap(json["id"], Stdlib_JSON.Decode.string);
  let from = Belt_Option.flatMap(json["from"], Stdlib_JSON.Decode.string);
  let to = Belt_Option.flatMap(json["to"], Stdlib_JSON.Decode.string);
  if (id !== undefined && from !== undefined && to !== undefined) {
    return {
      id: id,
      from: from,
      to: to
    };
  }
}

function modelToJson(model) {
  return Object.fromEntries([
    [
      "components",
      Belt_Array.map(model.components, componentToJson)
    ],
    [
      "connections",
      Belt_Array.map(model.connections, connectionToJson)
    ]
  ]);
}

function modelFromJson(json) {
  if (typeof json !== "object" || json === null || Array.isArray(json)) {
    return;
  }
  let components = Belt_Option.flatMap(json["components"], arr => {
    if (Array.isArray(arr)) {
      return Belt_Array.keepMap(Belt_Array.map(arr, componentFromJson), x => x);
    }
  });
  let connections = Belt_Option.flatMap(json["connections"], arr => {
    if (Array.isArray(arr)) {
      return Belt_Array.keepMap(Belt_Array.map(arr, connectionFromJson), x => x);
    }
  });
  if (components !== undefined && connections !== undefined) {
    return {
      components: components,
      connections: connections,
      selectedComponent: Model.initialModel.selectedComponent,
      dragState: Model.initialModel.dragState,
      canvasOffset: Model.initialModel.canvasOffset,
      zoomLevel: Model.initialModel.zoomLevel,
      validationResult: Model.initialModel.validationResult,
      securityState: Model.initialModel.securityState,
      gapState: Model.initialModel.gapState,
      securityLoading: Model.initialModel.securityLoading,
      gapLoading: Model.initialModel.gapLoading,
      currentStackId: Model.initialModel.currentStackId,
      settings: Model.initialModel.settings,
      wsState: Model.initialModel.wsState,
      undoStack: Model.initialModel.undoStack,
      redoStack: Model.initialModel.redoStack,
      isDirty: Model.initialModel.isDirty,
      lastSavedAt: Model.initialModel.lastSavedAt,
      activeErrors: Model.initialModel.activeErrors
    };
  }
}

function serializeDesign(model, metadata) {
  let design = Object.fromEntries([
    [
      "version",
      metadata.version
    ],
    [
      "metadata",
      Object.fromEntries([
        [
          "created",
          metadata.created
        ],
        [
          "author",
          metadata.author
        ],
        [
          "description",
          metadata.description
        ]
      ])
    ],
    [
      "canvas",
      modelToJson(model)
    ]
  ]);
  return JSON.stringify(design);
}

function deserializeDesign(jsonStr) {
  try {
    let json = JSON.parse(jsonStr);
    if (typeof json !== "object" || json === null || Array.isArray(json)) {
      return {
        TAG: "Error",
        _0: "Design file must be a JSON object"
      };
    }
    let version = Belt_Option.flatMap(json["version"], Stdlib_JSON.Decode.string);
    let metadata = Belt_Option.flatMap(json["metadata"], metaJson => {
      if (typeof metaJson !== "object" || metaJson === null || Array.isArray(metaJson)) {
        return;
      }
      let created = Belt_Option.flatMap(metaJson["created"], Stdlib_JSON.Decode.string);
      let author = Belt_Option.flatMap(metaJson["author"], Stdlib_JSON.Decode.string);
      let description = Belt_Option.flatMap(metaJson["description"], Stdlib_JSON.Decode.string);
      if (created !== undefined && author !== undefined && description !== undefined) {
        return {
          version: Belt_Option.getWithDefault(version, "1.0"),
          created: created,
          author: author,
          description: description
        };
      }
    });
    let canvas = Belt_Option.flatMap(json["canvas"], modelFromJson);
    if (metadata !== undefined && canvas !== undefined) {
      return {
        TAG: "Ok",
        _0: [
          metadata,
          canvas
        ]
      };
    } else {
      return {
        TAG: "Error",
        _0: "Invalid design file structure"
      };
    }
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    if (e.RE_EXN_ID === "JsExn") {
      return {
        TAG: "Error",
        _0: "JSON parse error: " + Belt_Option.getWithDefault(Stdlib_JsExn.message(e._1), "Unknown error")
      };
    }
    throw e;
  }
}

let currentVersion = "1.0";

export {
  currentVersion,
  componentToJson,
  componentFromJson,
  connectionToJson,
  connectionFromJson,
  modelToJson,
  modelFromJson,
  serializeDesign,
  deserializeDesign,
}
/* Stdlib_JsExn Not a pure module */
