// SPDX-License-Identifier: MPL-2.0
// Export.res - Export designs to multiple formats
// Supports: JSON design, selur-compose.toml, docker-compose.yml,
//           podman-compose.yml, Kubernetes YAML, Helm chart

open Model
open DesignFormat

// Direct JS binding for Array.join (avoids deprecated Js.Array2.joinWith)
@send external joinWith: (array<string>, string) => string = "join"

// Get current ISO timestamp
let getCurrentTimestamp = (): string => {
  let date = Date.make()
  Date.toISOString(date)
}

// Download a string as a file
let downloadFile = (filename: string, content: string, mimeType: string) => {
  // Create blob
  let blob = WebAPI.makeBlob([content], {"type": mimeType})

  // Create download link
  let url = WebAPI.createObjectURL(blob)
  let link = WebAPI.createElement("a")

  link->WebAPI.setAttribute("href", url)
  link->WebAPI.setAttribute("download", filename)
  link
  ->WebAPI.elementToHtml
  ->Belt.Option.forEach(htmlElement => {
    // Trigger download
    htmlElement->WebAPI.click
  })

  // Cleanup
  WebAPI.revokeObjectURL(url)
}

// Export design to JSON file
let exportDesignToJson = (model: model, description: string) => {
  let metadata: designMetadata = {
    version: currentVersion,
    created: getCurrentTimestamp(),
    author: "Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>",
    description,
  }

  let jsonString = serializeDesign(model, metadata)
  let timestamp = Date.now()->Float.toString
  let filename = "stapeln-design-" ++ timestamp ++ ".json"

  downloadFile(filename, jsonString, "application/json")
  Console.log("Exported design to " ++ filename)
}

// Map component type to a container image
let componentTypeToImage = (ct: componentType): string => {
  switch ct {
  | CerroTorre => "cgr.dev/chainguard/wolfi-base:latest"
  | LagoGrey => "ghcr.io/hyperpolymath/lago-grey:latest"
  | Svalinn => "ghcr.io/hyperpolymath/svalinn:latest"
  | Selur => "ghcr.io/hyperpolymath/selur:latest"
  | Vordr => "ghcr.io/hyperpolymath/vordr:latest"
  | Rokur => "ghcr.io/hyperpolymath/rokur:latest"
  | Podman => "cgr.dev/chainguard/wolfi-base:latest"
  | Docker => "cgr.dev/chainguard/wolfi-base:latest"
  | Nerdctl => "cgr.dev/chainguard/wolfi-base:latest"
  | Volume => "busybox:latest"
  | Network => "busybox:latest"
  // No image is guessed for a type this build does not understand. A
  // plausible-looking default here would export a manifest that pulls the
  // WRONG container, which is worse than an export that plainly cannot be
  // completed. The scratch image is empty and inert, and the name says why.
  | UnknownType(name) => "scratch # unrecognised component type: " ++ name
  }
}

// Sanitise identifier for Kubernetes (lowercase, alphanumeric, hyphens only)
let sanitiseK8sName = (name: string): string => {
  name
  ->String.toLowerCase
  ->String.replaceRegExp(%re("/[^a-z0-9-]/g"), "-")
  ->String.replaceRegExp(%re("/^-+|-+$/g"), "")
}

// ---------------------------------------------------------------------------
// selur-compose.toml export
// ---------------------------------------------------------------------------

let exportToSelurCompose = (model: model) => {
  let toml = "# SPDX-License-Identifier: MPL-2.0\n# Generated by stapeln (selur-compose format)\n\n" ++ "[stack]\n" ++ "name = \"my-stack\"\n" ++ "version = \"1.0\"\n\n"

  let services =
    model.components
    ->Array.map(comp => {
      let image = componentTypeToImage(comp.componentType)
      let portLine = switch comp.config->Dict.get("port") {
      | Some(port) => "port = " ++ port ++ "\n"
      | None => ""
      }
      "[[services]]\n" ++
      "name = \"" ++
      comp.id ++
      "\"\n" ++
      "type = \"" ++
      componentTypeToString(comp.componentType) ++
      "\"\n" ++
      "image = \"" ++
      image ++
      "\"\n" ++
      portLine
    })
    ->joinWith("\n")

  let fullToml = toml ++ services

  let timestamp = Date.now()->Float.toString
  let filename = "compose-" ++ timestamp ++ ".toml"

  downloadFile(filename, fullToml, "text/plain")
  Console.log("Exported to " ++ filename)
}

// ---------------------------------------------------------------------------
// docker-compose.yml export
// ---------------------------------------------------------------------------

let exportToDockerCompose = (model: model) => {
  let yaml = "# SPDX-License-Identifier: MPL-2.0\n# Generated by stapeln\n" ++ "version: '3.8'\n\n" ++ "services:\n"

  let services =
    model.components
    ->Array.map(comp => {
      let image = componentTypeToImage(comp.componentType)
      let portLine = switch comp.config->Dict.get("port") {
      | Some(port) => "    ports:\n      - \"" ++ port ++ ":" ++ port ++ "\"\n"
      | None => ""
      }
      "  " ++
      comp.id ++
      ":\n" ++
      "    image: " ++
      image ++
      "\n" ++
      "    # type: " ++
      componentTypeToString(comp.componentType) ++
      "\n" ++
      portLine ++
      "    restart: unless-stopped\n"
    })
    ->joinWith("\n")

  let fullYaml = yaml ++ services

  let timestamp = Date.now()->Float.toString
  let filename = "docker-compose-" ++ timestamp ++ ".yml"

  downloadFile(filename, fullYaml, "text/yaml")
  Console.log("Exported to " ++ filename)
}

// ---------------------------------------------------------------------------
// podman-compose.yml export (same structure as docker-compose)
// ---------------------------------------------------------------------------

let exportToPodmanCompose = (model: model) => {
  exportToDockerCompose(model)
}

// ---------------------------------------------------------------------------
// Kubernetes YAML export (Deployments + Services)
// ---------------------------------------------------------------------------

let exportToKubernetesYaml = (model: model) => {
  let namespace = "stapeln"
  let timestamp = getCurrentTimestamp()

  let manifests =
    model.components
    ->Array.map(comp => {
      let name = sanitiseK8sName(comp.id)
      let image = componentTypeToImage(comp.componentType)
      let port = switch comp.config->Dict.get("port") {
      | Some(p) => p
      | None => "8080"
      }
      let compType = componentTypeToString(comp.componentType)

      // Deployment manifest
      let deployment =
        "---\n" ++
        "apiVersion: apps/v1\n" ++
        "kind: Deployment\n" ++
        "metadata:\n" ++
        "  name: " ++ name ++ "\n" ++
        "  namespace: " ++ namespace ++ "\n" ++
        "  labels:\n" ++
        "    app: " ++ name ++ "\n" ++
        "    app.kubernetes.io/managed-by: stapeln\n" ++
        "    app.kubernetes.io/component: " ++ sanitiseK8sName(compType) ++ "\n" ++
        "  annotations:\n" ++
        "    stapeln.hyperpolymath.dev/generated: \"" ++ timestamp ++ "\"\n" ++
        "spec:\n" ++
        "  replicas: 1\n" ++
        "  selector:\n" ++
        "    matchLabels:\n" ++
        "      app: " ++ name ++ "\n" ++
        "  template:\n" ++
        "    metadata:\n" ++
        "      labels:\n" ++
        "        app: " ++ name ++ "\n" ++
        "    spec:\n" ++
        "      containers:\n" ++
        "        - name: " ++ name ++ "\n" ++
        "          image: " ++ image ++ "\n" ++
        "          ports:\n" ++
        "            - containerPort: " ++ port ++ "\n" ++
        "          resources:\n" ++
        "            limits:\n" ++
        "              cpu: \"1\"\n" ++
        "              memory: \"512Mi\"\n" ++
        "            requests:\n" ++
        "              cpu: \"100m\"\n" ++
        "              memory: \"128Mi\"\n" ++
        "          securityContext:\n" ++
        "            runAsNonRoot: true\n" ++
        "            readOnlyRootFilesystem: true\n" ++
        "            allowPrivilegeEscalation: false\n"

      // Service manifest
      let service =
        "---\n" ++
        "apiVersion: v1\n" ++
        "kind: Service\n" ++
        "metadata:\n" ++
        "  name: " ++ name ++ "\n" ++
        "  namespace: " ++ namespace ++ "\n" ++
        "  labels:\n" ++
        "    app: " ++ name ++ "\n" ++
        "spec:\n" ++
        "  selector:\n" ++
        "    app: " ++ name ++ "\n" ++
        "  ports:\n" ++
        "    - port: " ++ port ++ "\n" ++
        "      targetPort: " ++ port ++ "\n" ++
        "      protocol: TCP\n" ++
        "  type: ClusterIP\n"

      deployment ++ "\n" ++ service
    })
    ->joinWith("\n")

  // Namespace manifest
  let namespaceMf =
    "# SPDX-License-Identifier: MPL-2.0\n" ++
    "# Generated by stapeln — Kubernetes manifests\n" ++
    "# Apply with: kubectl apply -f <filename>\n\n" ++
    "---\n" ++
    "apiVersion: v1\n" ++
    "kind: Namespace\n" ++
    "metadata:\n" ++
    "  name: " ++ namespace ++ "\n" ++
    "  labels:\n" ++
    "    app.kubernetes.io/managed-by: stapeln\n\n"

  let fullYaml = namespaceMf ++ manifests

  let ts = Date.now()->Float.toString
  let filename = "k8s-manifests-" ++ ts ++ ".yaml"

  downloadFile(filename, fullYaml, "text/yaml")
  Console.log("Exported Kubernetes manifests to " ++ filename)
}

// ---------------------------------------------------------------------------
// Helm chart export (Chart.yaml + values.yaml + templates/)
// ---------------------------------------------------------------------------

let exportToHelmChart = (model: model) => {
  let chartName = "stapeln-stack"
  let timestamp = getCurrentTimestamp()

  // Chart.yaml
  let chartYaml =
    "# SPDX-License-Identifier: MPL-2.0\n" ++
    "apiVersion: v2\n" ++
    "name: " ++ chartName ++ "\n" ++
    "description: A Helm chart generated by stapeln container stack designer\n" ++
    "type: application\n" ++
    "version: 0.1.0\n" ++
    "appVersion: \"1.0.0\"\n" ++
    "maintainers:\n" ++
    "  - name: Jonathan D.A. Jewell\n" ++
    "    email: j.d.a.jewell@open.ac.uk\n" ++
    "annotations:\n" ++
    "  stapeln.hyperpolymath.dev/generated: \"" ++ timestamp ++ "\"\n"

  // values.yaml
  let valuesHeader =
    "# SPDX-License-Identifier: MPL-2.0\n" ++
    "# Default values for " ++ chartName ++ "\n\n" ++
    "namespace: stapeln\n" ++
    "replicaCount: 1\n\n" ++
    "services:\n"

  let valuesServices =
    model.components
    ->Array.map(comp => {
      let name = sanitiseK8sName(comp.id)
      let image = componentTypeToImage(comp.componentType)
      let port = switch comp.config->Dict.get("port") {
      | Some(p) => p
      | None => "8080"
      }
      let (imageRepo, imageTag) = switch String.split(image, ":") {
      | [repo, tag] => (repo, tag)
      | [repo] => (repo, "latest")
      | _ => (image, "latest")
      }

      "  " ++ name ++ ":\n" ++
      "    enabled: true\n" ++
      "    image:\n" ++
      "      repository: " ++ imageRepo ++ "\n" ++
      "      tag: " ++ imageTag ++ "\n" ++
      "      pullPolicy: IfNotPresent\n" ++
      "    port: " ++ port ++ "\n" ++
      "    resources:\n" ++
      "      limits:\n" ++
      "        cpu: \"1\"\n" ++
      "        memory: 512Mi\n" ++
      "      requests:\n" ++
      "        cpu: 100m\n" ++
      "        memory: 128Mi\n"
    })
    ->joinWith("\n")

  let valuesYaml = valuesHeader ++ valuesServices

  // templates/deployment.yaml (Helm template)
  let deploymentTemplate =
    "# SPDX-License-Identifier: MPL-2.0\n" ++
    "{{- range $name, $svc := .Values.services }}\n" ++
    "{{- if $svc.enabled }}\n" ++
    "---\n" ++
    "apiVersion: apps/v1\n" ++
    "kind: Deployment\n" ++
    "metadata:\n" ++
    "  name: {{ $name }}\n" ++
    "  namespace: {{ $.Values.namespace }}\n" ++
    "  labels:\n" ++
    "    app: {{ $name }}\n" ++
    "    app.kubernetes.io/managed-by: stapeln\n" ++
    "spec:\n" ++
    "  replicas: {{ $.Values.replicaCount }}\n" ++
    "  selector:\n" ++
    "    matchLabels:\n" ++
    "      app: {{ $name }}\n" ++
    "  template:\n" ++
    "    metadata:\n" ++
    "      labels:\n" ++
    "        app: {{ $name }}\n" ++
    "    spec:\n" ++
    "      containers:\n" ++
    "        - name: {{ $name }}\n" ++
    "          image: \"{{ $svc.image.repository }}:{{ $svc.image.tag }}\"\n" ++
    "          imagePullPolicy: {{ $svc.image.pullPolicy }}\n" ++
    "          ports:\n" ++
    "            - containerPort: {{ $svc.port }}\n" ++
    "          resources:\n" ++
    "            {{- toYaml $svc.resources | nindent 12 }}\n" ++
    "          securityContext:\n" ++
    "            runAsNonRoot: true\n" ++
    "            readOnlyRootFilesystem: true\n" ++
    "            allowPrivilegeEscalation: false\n" ++
    "{{- end }}\n" ++
    "{{- end }}\n"

  // templates/service.yaml (Helm template)
  let serviceTemplate =
    "# SPDX-License-Identifier: MPL-2.0\n" ++
    "{{- range $name, $svc := .Values.services }}\n" ++
    "{{- if $svc.enabled }}\n" ++
    "---\n" ++
    "apiVersion: v1\n" ++
    "kind: Service\n" ++
    "metadata:\n" ++
    "  name: {{ $name }}\n" ++
    "  namespace: {{ $.Values.namespace }}\n" ++
    "spec:\n" ++
    "  selector:\n" ++
    "    app: {{ $name }}\n" ++
    "  ports:\n" ++
    "    - port: {{ $svc.port }}\n" ++
    "      targetPort: {{ $svc.port }}\n" ++
    "  type: ClusterIP\n" ++
    "{{- end }}\n" ++
    "{{- end }}\n"

  // Download all files
  let ts = Date.now()->Float.toString
  let prefix = "helm-" ++ chartName ++ "-" ++ ts

  downloadFile(prefix ++ "-Chart.yaml", chartYaml, "text/yaml")
  downloadFile(prefix ++ "-values.yaml", valuesYaml, "text/yaml")
  downloadFile(prefix ++ "-deployment.yaml", deploymentTemplate, "text/yaml")
  downloadFile(prefix ++ "-service.yaml", serviceTemplate, "text/yaml")

  Console.log("Exported Helm chart files with prefix " ++ prefix)
}
