// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Model from "./Model.res.js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as DesignFormat from "./DesignFormat.res.js";

function getCurrentTimestamp() {
  return new Date().toISOString();
}

function downloadFile(filename, content, mimeType) {
  let blob = new Blob([content], {
    type: mimeType
  });
  let url = URL.createObjectURL(blob);
  let link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  Belt_Option.forEach(link, htmlElement => {
    htmlElement.click();
  });
  URL.revokeObjectURL(url);
}

function exportDesignToJson(model, description) {
  let metadata_created = new Date().toISOString();
  let metadata = {
    version: DesignFormat.currentVersion,
    created: metadata_created,
    author: "Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>",
    description: description
  };
  let jsonString = DesignFormat.serializeDesign(model, metadata);
  let timestamp = String(Date.now());
  let filename = "stapeln-design-" + timestamp + ".json";
  downloadFile(filename, jsonString, "application/json");
  console.log("Exported design to " + filename);
}

function componentTypeToImage(ct) {
  if (typeof ct === "object") {
    return "scratch # unrecognised component type: " + ct._0;
  }
  switch (ct) {
    case "LagoGrey" :
      return "ghcr.io/hyperpolymath/lago-grey:latest";
    case "Svalinn" :
      return "ghcr.io/hyperpolymath/svalinn:latest";
    case "Selur" :
      return "ghcr.io/hyperpolymath/selur:latest";
    case "Vordr" :
      return "ghcr.io/hyperpolymath/vordr:latest";
    case "Rokur" :
      return "ghcr.io/hyperpolymath/rokur:latest";
    case "CerroTorre" :
    case "Podman" :
    case "Docker" :
    case "Nerdctl" :
      return "cgr.dev/chainguard/wolfi-base:latest";
    case "Volume" :
    case "Network" :
      return "busybox:latest";
  }
}

function sanitiseK8sName(name) {
  return name.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/^-+|-+$/g, "");
}

function exportToSelurCompose(model) {
  let toml = "# SPDX-License-Identifier: MPL-2.0\n# Generated by stapeln (selur-compose format)\n\n[stack]\nname = \"my-stack\"\nversion = \"1.0\"\n\n";
  let services = Belt_Array.map(model.components, comp => {
    let image = componentTypeToImage(comp.componentType);
    let port = comp.config["port"];
    let portLine = port !== undefined ? "port = " + port + "\n" : "";
    return "[[services]]\nname = \"" + comp.id + "\"\ntype = \"" + Model.componentTypeToString(comp.componentType) + "\"\nimage = \"" + image + "\"\n" + portLine;
  }).join("\n");
  let fullToml = toml + services;
  let timestamp = String(Date.now());
  let filename = "compose-" + timestamp + ".toml";
  downloadFile(filename, fullToml, "text/plain");
  console.log("Exported to " + filename);
}

function exportToDockerCompose(model) {
  let yaml = "# SPDX-License-Identifier: MPL-2.0\n# Generated by stapeln\nversion: '3.8'\n\nservices:\n";
  let services = Belt_Array.map(model.components, comp => {
    let image = componentTypeToImage(comp.componentType);
    let port = comp.config["port"];
    let portLine = port !== undefined ? "    ports:\n      - \"" + port + ":" + port + "\"\n" : "";
    return "  " + comp.id + ":\n    image: " + image + "\n    # type: " + Model.componentTypeToString(comp.componentType) + "\n" + portLine + "    restart: unless-stopped\n";
  }).join("\n");
  let fullYaml = yaml + services;
  let timestamp = String(Date.now());
  let filename = "docker-compose-" + timestamp + ".yml";
  downloadFile(filename, fullYaml, "text/yaml");
  console.log("Exported to " + filename);
}

let exportToPodmanCompose = exportToDockerCompose;

function exportToKubernetesYaml(model) {
  let namespace = "stapeln";
  let timestamp = new Date().toISOString();
  let manifests = Belt_Array.map(model.components, comp => {
    let name = sanitiseK8sName(comp.id);
    let image = componentTypeToImage(comp.componentType);
    let p = comp.config["port"];
    let port = p !== undefined ? p : "8080";
    let compType = Model.componentTypeToString(comp.componentType);
    let deployment = "---\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: " + name + "\n  namespace: " + namespace + "\n  labels:\n    app: " + name + "\n    app.kubernetes.io/managed-by: stapeln\n    app.kubernetes.io/component: " + sanitiseK8sName(compType) + "\n  annotations:\n    stapeln.hyperpolymath.dev/generated: \"" + timestamp + "\"\nspec:\n  replicas: 1\n  selector:\n    matchLabels:\n      app: " + name + "\n  template:\n    metadata:\n      labels:\n        app: " + name + "\n    spec:\n      containers:\n        - name: " + name + "\n          image: " + image + "\n          ports:\n            - containerPort: " + port + "\n          resources:\n            limits:\n              cpu: \"1\"\n              memory: \"512Mi\"\n            requests:\n              cpu: \"100m\"\n              memory: \"128Mi\"\n          securityContext:\n            runAsNonRoot: true\n            readOnlyRootFilesystem: true\n            allowPrivilegeEscalation: false\n";
    let service = "---\napiVersion: v1\nkind: Service\nmetadata:\n  name: " + name + "\n  namespace: " + namespace + "\n  labels:\n    app: " + name + "\nspec:\n  selector:\n    app: " + name + "\n  ports:\n    - port: " + port + "\n      targetPort: " + port + "\n      protocol: TCP\n  type: ClusterIP\n";
    return deployment + "\n" + service;
  }).join("\n");
  let namespaceMf = "# SPDX-License-Identifier: MPL-2.0\n# Generated by stapeln — Kubernetes manifests\n# Apply with: kubectl apply -f <filename>\n\n---\napiVersion: v1\nkind: Namespace\nmetadata:\n  name: " + namespace + "\n  labels:\n    app.kubernetes.io/managed-by: stapeln\n\n";
  let fullYaml = namespaceMf + manifests;
  let ts = String(Date.now());
  let filename = "k8s-manifests-" + ts + ".yaml";
  downloadFile(filename, fullYaml, "text/yaml");
  console.log("Exported Kubernetes manifests to " + filename);
}

function exportToHelmChart(model) {
  let chartName = "stapeln-stack";
  let timestamp = new Date().toISOString();
  let chartYaml = "# SPDX-License-Identifier: MPL-2.0\napiVersion: v2\nname: " + chartName + "\ndescription: A Helm chart generated by stapeln container stack designer\ntype: application\nversion: 0.1.0\nappVersion: \"1.0.0\"\nmaintainers:\n  - name: Jonathan D.A. Jewell\n    email: j.d.a.jewell@open.ac.uk\nannotations:\n  stapeln.hyperpolymath.dev/generated: \"" + timestamp + "\"\n";
  let valuesHeader = "# SPDX-License-Identifier: MPL-2.0\n# Default values for " + chartName + "\n\nnamespace: stapeln\nreplicaCount: 1\n\nservices:\n";
  let valuesServices = Belt_Array.map(model.components, comp => {
    let name = sanitiseK8sName(comp.id);
    let image = componentTypeToImage(comp.componentType);
    let p = comp.config["port"];
    let port = p !== undefined ? p : "8080";
    let match = image.split(":");
    let len = match.length;
    let match$1;
    if (len >= 3) {
      match$1 = [
        image,
        "latest"
      ];
    } else {
      switch (len) {
        case 0 :
          match$1 = [
            image,
            "latest"
          ];
          break;
        case 1 :
          let repo = match[0];
          match$1 = [
            repo,
            "latest"
          ];
          break;
        case 2 :
          let repo$1 = match[0];
          let tag = match[1];
          match$1 = [
            repo$1,
            tag
          ];
          break;
      }
    }
    return "  " + name + ":\n    enabled: true\n    image:\n      repository: " + match$1[0] + "\n      tag: " + match$1[1] + "\n      pullPolicy: IfNotPresent\n    port: " + port + "\n    resources:\n      limits:\n        cpu: \"1\"\n        memory: 512Mi\n      requests:\n        cpu: 100m\n        memory: 128Mi\n";
  }).join("\n");
  let valuesYaml = valuesHeader + valuesServices;
  let deploymentTemplate = "# SPDX-License-Identifier: MPL-2.0\n{{- range $name, $svc := .Values.services }}\n{{- if $svc.enabled }}\n---\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: {{ $name }}\n  namespace: {{ $.Values.namespace }}\n  labels:\n    app: {{ $name }}\n    app.kubernetes.io/managed-by: stapeln\nspec:\n  replicas: {{ $.Values.replicaCount }}\n  selector:\n    matchLabels:\n      app: {{ $name }}\n  template:\n    metadata:\n      labels:\n        app: {{ $name }}\n    spec:\n      containers:\n        - name: {{ $name }}\n          image: \"{{ $svc.image.repository }}:{{ $svc.image.tag }}\"\n          imagePullPolicy: {{ $svc.image.pullPolicy }}\n          ports:\n            - containerPort: {{ $svc.port }}\n          resources:\n            {{- toYaml $svc.resources | nindent 12 }}\n          securityContext:\n            runAsNonRoot: true\n            readOnlyRootFilesystem: true\n            allowPrivilegeEscalation: false\n{{- end }}\n{{- end }}\n";
  let serviceTemplate = "# SPDX-License-Identifier: MPL-2.0\n{{- range $name, $svc := .Values.services }}\n{{- if $svc.enabled }}\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: {{ $name }}\n  namespace: {{ $.Values.namespace }}\nspec:\n  selector:\n    app: {{ $name }}\n  ports:\n    - port: {{ $svc.port }}\n      targetPort: {{ $svc.port }}\n  type: ClusterIP\n{{- end }}\n{{- end }}\n";
  let ts = String(Date.now());
  let prefix = "helm-" + chartName + "-" + ts;
  downloadFile(prefix + "-Chart.yaml", chartYaml, "text/yaml");
  downloadFile(prefix + "-values.yaml", valuesYaml, "text/yaml");
  downloadFile(prefix + "-deployment.yaml", deploymentTemplate, "text/yaml");
  downloadFile(prefix + "-service.yaml", serviceTemplate, "text/yaml");
  console.log("Exported Helm chart files with prefix " + prefix);
}

export {
  getCurrentTimestamp,
  downloadFile,
  exportDesignToJson,
  componentTypeToImage,
  sanitiseK8sName,
  exportToSelurCompose,
  exportToDockerCompose,
  exportToPodmanCompose,
  exportToKubernetesYaml,
  exportToHelmChart,
}
/* Model Not a pure module */
