// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function proofEmoji(proof) {
  switch (proof) {
    case "MemorySafety" :
      return "🛡️";
    case "ThreadSafety" :
      return "🔒";
    case "TypeCorrectness" :
      return "✓";
    case "NonEmpty" :
      return "📝";
    case "ElementExists" :
      return "🔍";
  }
}

function proofLabel(proof) {
  switch (proof) {
    case "MemorySafety" :
      return "Memory Safe";
    case "ThreadSafety" :
      return "Thread Safe";
    case "TypeCorrectness" :
      return "Type Correct";
    case "NonEmpty" :
      return "Non-Empty";
    case "ElementExists" :
      return "Element Exists";
  }
}

function viewCompactBadge() {
  return JsxRuntime.jsxs("span", {
    children: [
      "⚡",
      "Idris²"
    ],
    style: {
      alignItems: "center",
      background: "linear-gradient(135deg, #bc13fe 0%, #7209b7 100%)",
      borderRadius: "4px",
      color: "white",
      display: "inline-flex",
      fontFamily: "monospace",
      fontSize: "10px",
      fontWeight: "700",
      gap: "4px",
      letterSpacing: "0.5px",
      padding: "2px 8px",
      textTransform: "uppercase"
    }
  });
}

function viewStandardBadge() {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "⚡",
        style: {
          fontSize: "24px",
          lineHeight: "1"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Idris² inside",
            style: {
              color: "white",
              fontFamily: "monospace",
              fontSize: "14px",
              fontWeight: "700",
              lineHeight: "1.2"
            }
          }),
          JsxRuntime.jsx("div", {
            children: "Formally Verified",
            style: {
              color: "rgba(255, 255, 255, 0.8)",
              fontSize: "10px",
              fontWeight: "600",
              marginTop: "2px"
            }
          })
        ]
      })
    ],
    style: {
      alignItems: "center",
      background: "linear-gradient(135deg, #bc13fe 0%, #7209b7 50%, #480ca8 100%)",
      border: "2px solid #bc13fe",
      borderRadius: "8px",
      boxShadow: "0 4px 12px rgba(188, 19, 254, 0.3)",
      display: "inline-flex",
      gap: "8px",
      padding: "8px 16px"
    }
  });
}

function viewDetailedBadge(proofs) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "⚡",
            style: {
              fontSize: "32px",
              lineHeight: "1"
            }
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: "Idris² inside",
                style: {
                  background: "linear-gradient(135deg, #bc13fe, #f72585)",
                  color: "white",
                  fontFamily: "monospace",
                  fontSize: "20px",
                  fontWeight: "700",
                  lineHeight: "1.2"
                }
              }),
              JsxRuntime.jsx("div", {
                children: "Dependently-typed formal verification",
                style: {
                  color: "rgba(255, 255, 255, 0.7)",
                  fontSize: "12px",
                  fontWeight: "600",
                  marginTop: "4px"
                }
              })
            ]
          })
        ],
        style: {
          alignItems: "center",
          display: "flex",
          gap: "12px",
          marginBottom: "16px"
        }
      }),
      JsxRuntime.jsx("div", {
        children: Belt_Array.map(proofs, proof => JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("span", {
              children: proofEmoji(proof),
              style: {
                fontSize: "16px"
              }
            }),
            JsxRuntime.jsx("span", {
              children: proofLabel(proof),
              style: {
                color: "white",
                fontSize: "13px",
                fontWeight: "600"
              }
            }),
            JsxRuntime.jsx("span", {
              children: "✓ PROVEN",
              style: {
                color: "#4ade80",
                fontSize: "11px",
                fontWeight: "700",
                marginLeft: "auto"
              }
            })
          ],
          style: {
            alignItems: "center",
            background: "rgba(188, 19, 254, 0.15)",
            border: "1px solid rgba(188, 19, 254, 0.3)",
            borderRadius: "6px",
            display: "flex",
            gap: "8px",
            padding: "8px 12px"
          }
        }, proofLabel(proof))),
        style: {
          display: "flex",
          flexDirection: "column",
          gap: "8px"
        }
      }),
      JsxRuntime.jsx("div", {
        children: "Compile-time guarantees backed by dependent type theory",
        style: {
          borderTop: "1px solid rgba(188, 19, 254, 0.3)",
          color: "rgba(255, 255, 255, 0.6)",
          fontSize: "11px",
          marginTop: "16px",
          paddingTop: "16px",
          textAlign: "center"
        }
      })
    ],
    style: {
      background: "linear-gradient(135deg, #1e0836 0%, #2d0a4e 100%)",
      border: "2px solid #bc13fe",
      borderRadius: "12px",
      boxShadow: "0 8px 24px rgba(188, 19, 254, 0.4)",
      padding: "20px"
    }
  });
}

function IdrisBadge(props) {
  let proofs = props.proofs;
  let __style = props.style;
  let __style_value = __style !== undefined ? __style : "Standard";
  switch (__style_value) {
    case "Compact" :
      return viewCompactBadge();
    case "Standard" :
      return viewStandardBadge();
    case "Detailed" :
      return viewDetailedBadge(proofs !== undefined ? proofs : [
          "MemorySafety",
          "ThreadSafety",
          "TypeCorrectness",
          "NonEmpty",
          "ElementExists"
        ]);
  }
}

let make = IdrisBadge;

export {
  proofEmoji,
  proofLabel,
  viewCompactBadge,
  viewStandardBadge,
  viewDetailedBadge,
  make,
}
/* react/jsx-runtime Not a pure module */
