// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as DesignFormat from "./DesignFormat.res.js";

function readFileAsText(file, callback) {
  let reader = new FileReader();
  reader.onload = () => callback(reader.result);
  reader.readAsText(file);
}

function importDesignFromFile(file, onSuccess, onError) {
  readFileAsText(file, jsonStr => {
    let err = DesignFormat.deserializeDesign(jsonStr);
    if (err.TAG === "Ok") {
      let match = err._0;
      let model = match[1];
      let metadata = match[0];
      console.log("Imported design created at:", metadata.created);
      console.log("Author:", metadata.author);
      console.log("Description:", metadata.description);
      console.log("Components:", model.components.length);
      let newrecord = {...model};
      return onSuccess((newrecord.stackDescription = metadata.description, newrecord.stackName = metadata.name, newrecord));
    }
    let err$1 = err._0;
    console.error("Import error:", err$1);
    onError(err$1);
  });
}

function triggerImport(onSuccess, onError) {
  let input = document.createElement("input");
  input.setAttribute("type", "file");
  input.setAttribute("accept", ".json,application/json");
  Belt_Option.forEach(input, htmlElement => {
    htmlElement.addEventListener("change", _evt => Belt_Option.forEach(Belt_Option.flatMap(Belt_Option.flatMap(htmlElement, prim => prim.files), fileList => fileList.item(0)), file => importDesignFromFile(file, onSuccess, onError)));
  });
  Belt_Option.forEach(input, htmlElement => {
    htmlElement.click();
  });
}

export {
  readFileAsText,
  importDesignFromFile,
  triggerImport,
}
/* DesignFormat Not a pure module */
