// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function LoginPage(props) {
  let onSwitchToRegister = props.onSwitchToRegister;
  let dispatch = props.dispatch;
  let isDark = props.isDark;
  let auth = props.auth;
  let inputStyle = {
    backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
    border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
    borderRadius: "4px",
    color: isDark ? "#FFFFFF" : "#000000",
    fontSize: "1rem",
    marginBottom: "1rem",
    maxWidth: "400px",
    padding: "0.75rem",
    width: "100%"
  };
  let labelStyle = {
    color: isDark ? "#FFFFFF" : "#000000",
    display: "block",
    fontWeight: "600",
    marginBottom: "0.5rem"
  };
  let buttonStyle = {
    backgroundColor: isDark ? "#66B2FF" : "#0052CC",
    border: "none",
    borderRadius: "6px",
    color: "white",
    cursor: auth.authLoading ? "wait" : "pointer",
    fontSize: "1rem",
    fontWeight: "600",
    maxWidth: "400px",
    opacity: auth.authLoading ? "0.7" : "1",
    padding: "0.75rem 1.5rem",
    width: "100%"
  };
  let handleSubmit = e => {
    e.preventDefault();
    dispatch("LoginRequested");
  };
  let error = auth.authError;
  return JsxRuntime.jsx("main", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("h1", {
          children: "Stapeln",
          style: {
            fontSize: "2rem",
            fontWeight: "700",
            marginBottom: "0.5rem",
            textAlign: "center"
          }
        }),
        JsxRuntime.jsx("p", {
          children: "Sign in to your account",
          style: {
            color: isDark ? "#AAAAAA" : "#666666",
            marginBottom: "2rem",
            textAlign: "center"
          }
        }),
        error !== undefined ? JsxRuntime.jsx("div", {
            children: error,
            role: "alert",
            style: {
              backgroundColor: isDark ? "#3d1010" : "#fde8e8",
              border: isDark ? "1px solid #ff6b6b" : "1px solid #c53030",
              borderRadius: "4px",
              color: isDark ? "#ff6b6b" : "#c53030",
              marginBottom: "1rem",
              maxWidth: "400px",
              padding: "0.75rem",
              width: "100%"
            }
          }) : null,
        JsxRuntime.jsxs("form", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("label", {
                  children: "Email",
                  style: labelStyle,
                  htmlFor: "login-email"
                }),
                JsxRuntime.jsx("input", {
                  "aria-label": "Email address",
                  "aria-required": true,
                  id: "login-email",
                  style: inputStyle,
                  autoComplete: "email",
                  disabled: auth.authLoading,
                  placeholder: "you@example.com",
                  type: "email",
                  value: auth.loginForm.email,
                  onChange: e => {
                    let value = e.target.value;
                    dispatch({
                      TAG: "UpdateLoginEmail",
                      _0: value
                    });
                  }
                })
              ],
              style: {
                marginBottom: "1rem"
              }
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("label", {
                  children: "Password",
                  style: labelStyle,
                  htmlFor: "login-password"
                }),
                JsxRuntime.jsx("input", {
                  "aria-label": "Password",
                  "aria-required": true,
                  id: "login-password",
                  style: inputStyle,
                  autoComplete: "current-password",
                  disabled: auth.authLoading,
                  placeholder: "Enter your password",
                  type: "password",
                  value: auth.loginForm.password,
                  onChange: e => {
                    let value = e.target.value;
                    dispatch({
                      TAG: "UpdateLoginPassword",
                      _0: value
                    });
                  }
                })
              ],
              style: {
                marginBottom: "1.5rem"
              }
            }),
            JsxRuntime.jsx("button", {
              children: auth.authLoading ? "Signing in..." : "Sign in",
              "aria-label": "Sign in",
              style: buttonStyle,
              disabled: auth.authLoading,
              type: "submit"
            })
          ],
          onSubmit: handleSubmit
        }),
        JsxRuntime.jsxs("p", {
          children: [
            "Don't have an account? ",
            JsxRuntime.jsx("button", {
              children: "Create one",
              style: {
                background: "none",
                border: "none",
                color: isDark ? "#66B2FF" : "#0052CC",
                cursor: "pointer",
                fontSize: "inherit",
                fontWeight: "600",
                padding: "0"
              },
              onClick: param => onSwitchToRegister()
            })
          ],
          style: {
            color: isDark ? "#AAAAAA" : "#666666",
            marginTop: "1.5rem",
            textAlign: "center"
          }
        })
      ],
      style: {
        border: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
        borderRadius: "8px",
        maxWidth: "460px",
        padding: "2rem",
        width: "100%"
      }
    }),
    "aria-label": "Login to Stapeln",
    role: "main",
    style: {
      alignItems: "center",
      backgroundColor: isDark ? "#000000" : "#FFFFFF",
      color: isDark ? "#FFFFFF" : "#000000",
      display: "flex",
      flexDirection: "column",
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      justifyContent: "center",
      minHeight: "100vh",
      padding: "2rem"
    }
  });
}

let make = LoginPage;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
