// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as PipelineModel from "./PipelineModel.res.js";
import * as JsxRuntime from "react/jsx-runtime";

let categoryColor = PipelineModel.nodeColor;

function categoryBadgeColor(cat) {
  switch (cat) {
    case "Application" :
      return "#4fc3f7";
    case "Data Science" :
      return "#ffb74d";
    case "Infrastructure" :
      return "#42a5f5";
    case "Web" :
      return "#81c784";
    default:
      return "#bdbdbd";
  }
}

let sourceItems = [
  {
    kind: {
      TAG: "Source",
      imageRef: "",
      tag: "latest"
    },
    label: "Base Image",
    description: "Pull a standard base image from a registry",
    icon: PipelineModel.nodeIcon({
      TAG: "Source",
      imageRef: "",
      tag: ""
    }),
    category: "Sources"
  },
  {
    kind: {
      TAG: "LagoGreyFormation",
      formation: "",
      size: 0
    },
    label: "Lago Grey Formation",
    description: "Minimal Lago Grey ice formation base",
    icon: PipelineModel.nodeIcon({
      TAG: "LagoGreyFormation",
      formation: "",
      size: 0
    }),
    category: "Sources"
  },
  {
    kind: {
      TAG: "CustomScript",
      script: "",
      shell: "/bin/sh"
    },
    label: "Custom Base",
    description: "User-specified base image URI",
    icon: PipelineModel.nodeIcon({
      TAG: "CustomScript",
      script: "",
      shell: ""
    }),
    category: "Sources"
  }
];

let buildStepItems = [
  {
    kind: {
      TAG: "BuildStep",
      command: "RUN",
      layer: 0
    },
    label: "RUN Command",
    description: "Execute a shell command in the build",
    icon: PipelineModel.nodeIcon({
      TAG: "BuildStep",
      command: "",
      layer: 0
    }),
    category: "Build Steps"
  },
  {
    kind: {
      TAG: "BuildStep",
      command: "COPY",
      layer: 0
    },
    label: "COPY Files",
    description: "Copy files from the build context",
    icon: PipelineModel.nodeIcon({
      TAG: "BuildStep",
      command: "",
      layer: 0
    }),
    category: "Build Steps"
  },
  {
    kind: {
      TAG: "BuildStep",
      command: "ADD",
      layer: 0
    },
    label: "ADD Archive",
    description: "Add and extract an archive into the image",
    icon: PipelineModel.nodeIcon({
      TAG: "BuildStep",
      command: "",
      layer: 0
    }),
    category: "Build Steps"
  },
  {
    kind: {
      TAG: "BuildStep",
      command: "ENV",
      layer: 0
    },
    label: "ENV Variable",
    description: "Set an environment variable",
    icon: PipelineModel.nodeIcon({
      TAG: "BuildStep",
      command: "",
      layer: 0
    }),
    category: "Build Steps"
  },
  {
    kind: {
      TAG: "BuildStep",
      command: "WORKDIR",
      layer: 0
    },
    label: "WORKDIR",
    description: "Set the working directory",
    icon: PipelineModel.nodeIcon({
      TAG: "BuildStep",
      command: "",
      layer: 0
    }),
    category: "Build Steps"
  },
  {
    kind: {
      TAG: "BuildStep",
      command: "USER",
      layer: 0
    },
    label: "USER",
    description: "Set the runtime user",
    icon: PipelineModel.nodeIcon({
      TAG: "BuildStep",
      command: "",
      layer: 0
    }),
    category: "Build Steps"
  },
  {
    kind: {
      TAG: "BuildStep",
      command: "EXPOSE",
      layer: 0
    },
    label: "EXPOSE",
    description: "Declare a network port",
    icon: PipelineModel.nodeIcon({
      TAG: "BuildStep",
      command: "",
      layer: 0
    }),
    category: "Build Steps"
  },
  {
    kind: {
      TAG: "BuildStep",
      command: "LABEL",
      layer: 0
    },
    label: "LABEL",
    description: "Add metadata label",
    icon: PipelineModel.nodeIcon({
      TAG: "BuildStep",
      command: "",
      layer: 0
    }),
    category: "Build Steps"
  }
];

let securityItems = [
  {
    kind: {
      TAG: "SecurityGate",
      policy: "",
      mode: "enforce"
    },
    label: "Svalinn Gate",
    description: "Security gate checkpoint (Svalinn)",
    icon: PipelineModel.nodeIcon({
      TAG: "SecurityGate",
      policy: "",
      mode: ""
    }),
    category: "Security"
  },
  {
    kind: {
      TAG: "SecurityGate",
      policy: "cve-scan",
      mode: "audit"
    },
    label: "Vulnerability Scan",
    description: "Scan for known CVEs",
    icon: PipelineModel.nodeIcon({
      TAG: "SecurityGate",
      policy: "",
      mode: ""
    }),
    category: "Security"
  },
  {
    kind: {
      TAG: "SecurityGate",
      policy: "policy-check",
      mode: "enforce"
    },
    label: "Policy Check",
    description: "Validate against security policy",
    icon: PipelineModel.nodeIcon({
      TAG: "SecurityGate",
      policy: "",
      mode: ""
    }),
    category: "Security"
  }
];

let supplyChainItems = [
  {
    kind: {
      TAG: "SignStep",
      keyId: "",
      transparency: true
    },
    label: "Sign (Cerro Torre)",
    description: "Cryptographically sign with Cerro Torre",
    icon: PipelineModel.nodeIcon({
      TAG: "SignStep",
      keyId: "",
      transparency: true
    }),
    category: "Supply Chain"
  },
  {
    kind: {
      TAG: "SbomGenerate",
      format: "cyclonedx"
    },
    label: "SBOM Generate",
    description: "Generate Software Bill of Materials",
    icon: PipelineModel.nodeIcon({
      TAG: "SbomGenerate",
      format: ""
    }),
    category: "Supply Chain"
  },
  {
    kind: {
      TAG: "ProvenanceAttach",
      builder: ""
    },
    label: "Provenance Attach",
    description: "Attach SLSA provenance attestation",
    icon: PipelineModel.nodeIcon({
      TAG: "ProvenanceAttach",
      builder: ""
    }),
    category: "Supply Chain"
  }
];

let registryItems = [
  {
    kind: {
      TAG: "Push",
      registry: "",
      repository: ""
    },
    label: "Push to Registry",
    description: "Push image to a container registry",
    icon: PipelineModel.nodeIcon({
      TAG: "Push",
      registry: "",
      repository: ""
    }),
    category: "Registry"
  },
  {
    kind: {
      TAG: "Source",
      imageRef: "",
      tag: "latest"
    },
    label: "Pull from Registry",
    description: "Pull image from a container registry",
    icon: PipelineModel.nodeIcon({
      TAG: "Source",
      imageRef: "",
      tag: ""
    }),
    category: "Registry"
  }
];

let compositionItems = [
  {
    kind: {
      TAG: "Compose",
      services: []
    },
    label: "Multi-service Compose",
    description: "Compose multiple services together",
    icon: PipelineModel.nodeIcon({
      TAG: "Compose",
      services: []
    }),
    category: "Composition"
  },
  {
    kind: {
      TAG: "Compose",
      services: []
    },
    label: "Dependency Link",
    description: "Declare a service dependency",
    icon: PipelineModel.nodeIcon({
      TAG: "Compose",
      services: []
    }),
    category: "Composition"
  }
];

let allPaletteItems = Belt_Array.concatMany([
  sourceItems,
  buildStepItems,
  securityItems,
  supplyChainItems,
  registryItems,
  compositionItems
]);

function filterItems(items, query) {
  if (query === "") {
    return items;
  }
  let lowerQuery = query.toLowerCase();
  return Belt_Array.keep(items, item => {
    if (item.label.toLowerCase().includes(lowerQuery) || item.description.toLowerCase().includes(lowerQuery)) {
      return true;
    } else {
      return item.category.toLowerCase().includes(lowerQuery);
    }
  });
}

function PipelinePalette$PaletteItemView(props) {
  let onAdd = props.onAdd;
  let item = props.item;
  return JsxRuntime.jsxs("button", {
    children: [
      JsxRuntime.jsx("span", {
        children: item.icon,
        className: "flex-shrink-0 w-8 h-8 flex items-center justify-center rounded text-sm font-bold",
        style: {
          backgroundColor: PipelineModel.nodeColor(item.kind),
          color: "#fff"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: item.label,
            className: "text-sm font-semibold text-gray-100 truncate"
          }),
          JsxRuntime.jsx("div", {
            children: item.description,
            className: "text-xs text-gray-400 leading-tight"
          })
        ],
        className: "min-w-0"
      })
    ],
    "aria-label": "Add " + item.label + " node to pipeline",
    className: "flex items-start gap-2 w-full p-2 rounded-md text-left\n                 hover:bg-gray-700/50 transition-colors cursor-grab\n                 focus:outline-none focus:ring-2 focus:ring-blue-500",
    draggable: true,
    onClick: param => onAdd(item),
    onDragStart: _e => {
      ((e.dataTransfer.setData("text/plain", _label)));
    }
  });
}

let PaletteItemView = {
  make: PipelinePalette$PaletteItemView
};

function PipelinePalette$CategoryGroup(props) {
  let onAdd = props.onAdd;
  let items = props.items;
  let title = props.title;
  let match = React.useState(() => false);
  if (items.length === 0) {
    return null;
  }
  let setCollapsed = match[1];
  let collapsed = match[0];
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("button", {
        children: [
          JsxRuntime.jsx("span", {
            children: collapsed ? "+" : "-",
            className: "text-[10px]"
          }),
          title,
          JsxRuntime.jsx("span", {
            children: String(items.length),
            className: "ml-auto text-gray-500"
          })
        ],
        "aria-expanded": !collapsed,
        className: "flex items-center gap-1 w-full text-xs font-bold uppercase tracking-wider\n                     text-gray-400 mb-1 px-1 hover:text-gray-200 transition-colors\n                     focus:outline-none focus:ring-1 focus:ring-blue-500 rounded",
        onClick: param => setCollapsed(prev => !prev)
      }),
      collapsed ? null : JsxRuntime.jsx("div", {
          children: Belt_Array.mapWithIndex(items, (idx, item) => JsxRuntime.jsx(PipelinePalette$PaletteItemView, {
            item: item,
            onAdd: onAdd
          }, item.label + String(idx))),
          className: "flex flex-col gap-0.5"
        })
    ],
    "aria-label": title + " category",
    className: "mb-3",
    role: "group"
  });
}

let CategoryGroup = {
  make: PipelinePalette$CategoryGroup
};

function PipelinePalette$TemplateCard(props) {
  let onLoad = props.onLoad;
  let template = props.template;
  let nodeCount = template.pipeline.nodes.length;
  return JsxRuntime.jsxs("button", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: template.name,
            className: "text-sm font-semibold text-gray-100"
          }),
          JsxRuntime.jsx("span", {
            children: template.category,
            className: "text-[10px] px-1.5 py-0.5 rounded-full font-medium",
            style: {
              backgroundColor: categoryBadgeColor(template.category),
              color: "#000"
            }
          })
        ],
        className: "flex items-center justify-between mb-1"
      }),
      JsxRuntime.jsx("p", {
        children: template.description,
        className: "text-xs text-gray-400 mb-2 leading-tight"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: String(nodeCount) + " nodes"
          }),
          JsxRuntime.jsx("span", {
            children: String(template.pipeline.connections.length) + " edges"
          })
        ],
        className: "flex gap-3 text-xs text-gray-500"
      })
    ],
    "aria-label": "Load " + template.name + " template",
    className: "w-full text-left p-3 rounded-lg bg-gray-800/60 hover:bg-gray-700/60\n                 border border-gray-700 hover:border-gray-500 transition-all\n                 focus:outline-none focus:ring-2 focus:ring-blue-500",
    onClick: param => onLoad(template)
  });
}

let TemplateCard = {
  make: PipelinePalette$TemplateCard
};

function PipelinePalette$RecentPipelineRow(props) {
  let onLoad = props.onLoad;
  let entry = props.entry;
  return JsxRuntime.jsx("button", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("div", {
          children: entry.name,
          className: "text-sm font-medium text-gray-100 truncate"
        }),
        JsxRuntime.jsx("div", {
          children: entry.updatedAt,
          className: "text-xs text-gray-500"
        })
      ],
      className: "min-w-0 flex-1"
    }),
    "aria-label": "Load recent pipeline: " + entry.name,
    className: "flex items-center gap-2 w-full p-2 rounded-md text-left\n                 hover:bg-gray-700/50 transition-colors\n                 focus:outline-none focus:ring-2 focus:ring-blue-500",
    onClick: param => onLoad(entry.id)
  });
}

let RecentPipelineRow = {
  make: PipelinePalette$RecentPipelineRow
};

function PipelinePalette(props) {
  let dispatch = props.dispatch;
  let state = props.state;
  let panels = state.panels;
  let activeTab = panels.activeLeftTab;
  let searchQuery;
  switch (activeTab) {
    case "Components" :
    case "Templates" :
    case "History" :
      searchQuery = "";
      break;
  }
  let match = React.useState(() => "");
  let setLocalSearch = match[1];
  let localSearch = match[0];
  let effectiveSearch;
  switch (activeTab) {
    case "Components" :
      effectiveSearch = localSearch;
      break;
    case "Templates" :
    case "History" :
      effectiveSearch = searchQuery;
      break;
  }
  let handleAddItem = item => {
    let centerX = state.pipeline.panX + 400.0;
    let centerY = state.pipeline.panY + 300.0;
    dispatch({
      TAG: "AddNode",
      _0: item.kind,
      _1: {
        x: centerX,
        y: centerY
      }
    });
  };
  let handleLoadTemplate = template => dispatch({
    TAG: "LoadTemplate",
    _0: template
  });
  let handleLoadRecent = id => dispatch({
    TAG: "LoadRecentPipeline",
    _0: id
  });
  if (panels.leftCollapsed) {
    return JsxRuntime.jsx("aside", {
      children: JsxRuntime.jsx("button", {
        children: ">",
        "aria-label": "Expand palette panel",
        className: "p-1 rounded hover:bg-gray-700 text-gray-400 hover:text-gray-100\n                   focus:outline-none focus:ring-2 focus:ring-blue-500",
        title: "Expand palette",
        onClick: param => dispatch("TogglePaletteCollapsed")
      }),
      "aria-label": "Pipeline palette (collapsed)",
      className: "flex flex-col items-center py-4 bg-gray-900 border-r border-gray-700",
      role: "complementary",
      style: {
        minWidth: "40px",
        width: "40px"
      }
    });
  }
  let tmp;
  switch (activeTab) {
    case "Components" :
      tmp = JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          JsxRuntime.jsx("div", {
            children: JsxRuntime.jsx("input", {
              "aria-label": "Filter pipeline components",
              className: "w-full px-2 py-1.5 text-sm rounded-md bg-gray-800 border border-gray-600\n                           text-gray-100 placeholder-gray-500\n                           focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500",
              placeholder: "Filter components...",
              type: "search",
              value: localSearch,
              onChange: e => {
                let v = e.target.value;
                setLocalSearch(param => v);
              }
            }),
            className: "mb-3"
          }),
          JsxRuntime.jsx(PipelinePalette$CategoryGroup, {
            title: "Sources",
            items: filterItems(sourceItems, effectiveSearch),
            onAdd: handleAddItem
          }),
          JsxRuntime.jsx(PipelinePalette$CategoryGroup, {
            title: "Build Steps",
            items: filterItems(buildStepItems, effectiveSearch),
            onAdd: handleAddItem
          }),
          JsxRuntime.jsx(PipelinePalette$CategoryGroup, {
            title: "Security",
            items: filterItems(securityItems, effectiveSearch),
            onAdd: handleAddItem
          }),
          JsxRuntime.jsx(PipelinePalette$CategoryGroup, {
            title: "Supply Chain",
            items: filterItems(supplyChainItems, effectiveSearch),
            onAdd: handleAddItem
          }),
          JsxRuntime.jsx(PipelinePalette$CategoryGroup, {
            title: "Registry",
            items: filterItems(registryItems, effectiveSearch),
            onAdd: handleAddItem
          }),
          JsxRuntime.jsx(PipelinePalette$CategoryGroup, {
            title: "Composition",
            items: filterItems(compositionItems, effectiveSearch),
            onAdd: handleAddItem
          })
        ]
      });
      break;
    case "Templates" :
      tmp = JsxRuntime.jsx("div", {
        children: state.templates.length === 0 ? JsxRuntime.jsx("p", {
            children: "No templates available.",
            className: "text-sm text-gray-500 py-4 text-center"
          }) : Belt_Array.mapWithIndex(state.templates, (idx, tpl) => JsxRuntime.jsx(PipelinePalette$TemplateCard, {
            template: tpl,
            onLoad: handleLoadTemplate
          }, tpl.id + String(idx))),
        className: "flex flex-col gap-2"
      });
      break;
    case "History" :
      tmp = JsxRuntime.jsx("div", {
        children: state.recentPipelines.length === 0 ? JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("p", {
                children: "No recent pipelines.",
                className: "text-sm text-gray-500 mb-1"
              }),
              JsxRuntime.jsx("p", {
                children: "Saved pipelines will appear here.",
                className: "text-xs text-gray-600"
              })
            ],
            className: "text-center py-6"
          }) : Belt_Array.mapWithIndex(state.recentPipelines, (idx, entry) => JsxRuntime.jsx(PipelinePalette$RecentPipelineRow, {
            entry: entry,
            onLoad: handleLoadRecent
          }, entry.id + String(idx))),
        className: "flex flex-col gap-0.5"
      });
      break;
  }
  return JsxRuntime.jsxs("aside", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h2", {
            children: "Palette",
            className: "text-sm font-bold text-gray-200 tracking-wide uppercase"
          }),
          JsxRuntime.jsx("button", {
            children: "<",
            "aria-label": "Collapse palette panel",
            className: "p-1 rounded hover:bg-gray-700 text-gray-400 hover:text-gray-100 text-xs\n                     focus:outline-none focus:ring-2 focus:ring-blue-500",
            title: "Collapse",
            onClick: param => dispatch("TogglePaletteCollapsed")
          })
        ],
        className: "flex items-center justify-between px-3 py-2 border-b border-gray-700"
      }),
      JsxRuntime.jsx("div", {
        children: Belt_Array.map([
          [
            "Components",
            "Components"
          ],
          [
            "Templates",
            "Templates"
          ],
          [
            "History",
            "History"
          ]
        ], param => {
          let label = param[1];
          let tab = param[0];
          let isActive = activeTab === tab;
          return JsxRuntime.jsx("button", {
            children: label,
            "aria-selected": isActive,
            className: "flex-1 px-2 py-2 text-xs font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500 " + (
              isActive ? "text-blue-400 border-b-2 border-blue-400" : "text-gray-400 hover:text-gray-200"
            ),
            role: "tab",
            onClick: param => dispatch({
              TAG: "SetPaletteTab",
              _0: tab
            })
          }, label);
        }),
        "aria-label": "Palette tabs",
        className: "flex border-b border-gray-700",
        role: "tablist"
      }),
      JsxRuntime.jsx("div", {
        children: tmp,
        className: "flex-1 overflow-y-auto px-3 py-2",
        role: "tabpanel"
      })
    ],
    "aria-label": "Pipeline palette",
    className: "flex flex-col bg-gray-900 border-r border-gray-700 overflow-hidden",
    role: "complementary",
    style: {
      maxWidth: "400px",
      minWidth: "200px",
      width: String(panels.leftPanelWidth) + "px"
    }
  });
}

let make = PipelinePalette;

export {
  categoryColor,
  categoryBadgeColor,
  sourceItems,
  buildStepItems,
  securityItems,
  supplyChainItems,
  registryItems,
  compositionItems,
  allPaletteItems,
  filterItems,
  PaletteItemView,
  CategoryGroup,
  TemplateCard,
  RecentPipelineRow,
  make,
}
/* sourceItems Not a pure module */
