// Generated by ReScript, PLEASE EDIT WITH CARE


function generateId() {
  let uuid = "";
  for (let i = 0; i <= 35; ++i) {
    let idx = Math.random() * 16.0 | 0;
    let char = "0123456789abcdef".charAt(idx);
    uuid = uuid + char;
    if (i === 7 || i === 12 || i === 17 || i === 22) {
      uuid = uuid + "-";
    }
  }
  return uuid;
}

function emptyPipeline() {
  return {
    id: generateId(),
    name: "Untitled Pipeline",
    description: "",
    nodes: [],
    connections: [],
    selectedNode: undefined,
    selectedConnection: undefined,
    zoom: 1.0,
    panX: 0.0,
    panY: 0.0
  };
}

function defaultPanelState() {
  return {
    leftPanelWidth: 260.0,
    rightPanelWidth: 320.0,
    leftCollapsed: false,
    rightCollapsed: false,
    activeLeftTab: "Components",
    activeRightTab: "Preview"
  };
}

function nodeColor(kind) {
  switch (kind.TAG) {
    case "Source" :
      return "#4fc3f7";
    case "LagoGreyFormation" :
      return "#81c784";
    case "BuildStep" :
      return "#ffb74d";
    case "SecurityGate" :
      return "#ef5350";
    case "SignStep" :
      return "#ab47bc";
    case "SbomGenerate" :
      return "#26c6da";
    case "ProvenanceAttach" :
      return "#7e57c2";
    case "Push" :
      return "#66bb6a";
    case "Compose" :
      return "#42a5f5";
    case "CustomScript" :
      return "#bdbdbd";
  }
}

function nodeIcon(kind) {
  switch (kind.TAG) {
    case "Source" :
      return "\u{1F4E6}";
    case "LagoGreyFormation" :
      return "\u{1F9CA}";
    case "BuildStep" :
      return "\u{1F527}";
    case "SecurityGate" :
      return "\u{1F6E1}";
    case "SignStep" :
      return "\u{1F58A}";
    case "SbomGenerate" :
      return "\u{1F4CB}";
    case "ProvenanceAttach" :
      return "\u{1F3F7}";
    case "Push" :
      return "\u{1F680}";
    case "Compose" :
      return "\u{1F517}";
    case "CustomScript" :
      return "\u{1F4DD}";
  }
}

function nodeKindToString(kind) {
  switch (kind.TAG) {
    case "Source" :
      return "Source Image";
    case "LagoGreyFormation" :
      return "Lago Grey Formation";
    case "BuildStep" :
      return "Build Step";
    case "SecurityGate" :
      return "Security Gate";
    case "SignStep" :
      return "Sign Step";
    case "SbomGenerate" :
      return "SBOM Generate";
    case "ProvenanceAttach" :
      return "Provenance Attach";
    case "Push" :
      return "Push";
    case "Compose" :
      return "Compose";
    case "CustomScript" :
      return "Custom Script";
  }
}

function outputFormatToString(fmt) {
  switch (fmt) {
    case "Containerfile" :
      return "Containerfile";
    case "SelurCompose" :
      return "selur-compose";
    case "PodmanCompose" :
      return "Podman Compose";
    case "K8sManifest" :
      return "Kubernetes Manifest";
    case "HelmChart" :
      return "Helm Chart";
    case "OciBundle" :
      return "OCI Bundle";
  }
}

function makeTemplate(id, name, description, category, nodes, connections) {
  return {
    id: id,
    name: name,
    description: description,
    category: category,
    pipeline: {
      id: generateId(),
      name: name,
      description: description,
      nodes: nodes,
      connections: connections,
      selectedNode: undefined,
      selectedConnection: undefined,
      zoom: 1.0,
      panX: 0.0,
      panY: 0.0
    }
  };
}

function defaultTemplates() {
  return [
    makeTemplate("tpl-web-app", "Web Application", "Node/Deno web app with security scanning, signing, and registry push", "Application", [
      {
        id: "src-1",
        kind: {
          TAG: "Source",
          imageRef: "cgr.dev/chainguard/wolfi-base",
          tag: "latest"
        },
        x: 50.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Base Image",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "build-1",
        kind: {
          TAG: "BuildStep",
          command: "COPY . /app && RUN deno task build",
          layer: 1
        },
        x: 300.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Build App",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "sec-1",
        kind: {
          TAG: "SecurityGate",
          policy: "strict",
          mode: "enforce"
        },
        x: 550.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Security Scan",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "sign-1",
        kind: {
          TAG: "SignStep",
          keyId: "default",
          transparency: true
        },
        x: 800.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Sign Image",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "push-1",
        kind: {
          TAG: "Push",
          registry: "ghcr.io",
          repository: "org/web-app"
        },
        x: 1050.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Push to Registry",
        status: "Idle",
        validationErrors: []
      }
    ], [
      {
        id: "c1",
        fromNode: "src-1",
        fromPort: "output",
        toNode: "build-1",
        toPort: "input"
      },
      {
        id: "c2",
        fromNode: "build-1",
        fromPort: "output",
        toNode: "sec-1",
        toPort: "input"
      },
      {
        id: "c3",
        fromNode: "sec-1",
        fromPort: "output",
        toNode: "sign-1",
        toPort: "input"
      },
      {
        id: "c4",
        fromNode: "sign-1",
        fromPort: "output",
        toNode: "push-1",
        toPort: "input"
      }
    ]),
    makeTemplate("tpl-microservice", "Microservice", "Minimal Rust microservice with SBOM and provenance attestation", "Application", [
      {
        id: "src-1",
        kind: {
          TAG: "Source",
          imageRef: "cgr.dev/chainguard/rust",
          tag: "latest"
        },
        x: 50.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Rust Base",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "build-1",
        kind: {
          TAG: "BuildStep",
          command: "cargo build --release",
          layer: 1
        },
        x: 300.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Compile",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "sbom-1",
        kind: {
          TAG: "SbomGenerate",
          format: "spdx-json"
        },
        x: 550.0,
        y: 120.0,
        width: 180.0,
        height: 80.0,
        label: "Generate SBOM",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "prov-1",
        kind: {
          TAG: "ProvenanceAttach",
          builder: "slsa-github-generator"
        },
        x: 550.0,
        y: 280.0,
        width: 180.0,
        height: 80.0,
        label: "Attach Provenance",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "push-1",
        kind: {
          TAG: "Push",
          registry: "ghcr.io",
          repository: "org/microservice"
        },
        x: 800.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Push to Registry",
        status: "Idle",
        validationErrors: []
      }
    ], [
      {
        id: "c1",
        fromNode: "src-1",
        fromPort: "output",
        toNode: "build-1",
        toPort: "input"
      },
      {
        id: "c2",
        fromNode: "build-1",
        fromPort: "output",
        toNode: "sbom-1",
        toPort: "input"
      },
      {
        id: "c3",
        fromNode: "build-1",
        fromPort: "output",
        toNode: "prov-1",
        toPort: "input"
      },
      {
        id: "c4",
        fromNode: "sbom-1",
        fromPort: "output",
        toNode: "push-1",
        toPort: "metadata"
      },
      {
        id: "c5",
        fromNode: "prov-1",
        fromPort: "output",
        toNode: "push-1",
        toPort: "attestation"
      }
    ]),
    makeTemplate("tpl-static-site", "Static Site", "Static site build with Lago Grey minimal base and signing", "Web", [
      {
        id: "lago-1",
        kind: {
          TAG: "LagoGreyFormation",
          formation: "static-serve",
          size: 5
        },
        x: 50.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Lago Grey Base",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "build-1",
        kind: {
          TAG: "BuildStep",
          command: "COPY dist/ /srv/static",
          layer: 1
        },
        x: 300.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Copy Assets",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "sign-1",
        kind: {
          TAG: "SignStep",
          keyId: "default",
          transparency: true
        },
        x: 550.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Sign Image",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "push-1",
        kind: {
          TAG: "Push",
          registry: "ghcr.io",
          repository: "org/static-site"
        },
        x: 800.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Push",
        status: "Idle",
        validationErrors: []
      }
    ], [
      {
        id: "c1",
        fromNode: "lago-1",
        fromPort: "output",
        toNode: "build-1",
        toPort: "input"
      },
      {
        id: "c2",
        fromNode: "build-1",
        fromPort: "output",
        toNode: "sign-1",
        toPort: "input"
      },
      {
        id: "c3",
        fromNode: "sign-1",
        fromPort: "output",
        toNode: "push-1",
        toPort: "input"
      }
    ]),
    makeTemplate("tpl-ml-model", "ML Model", "Machine learning model container with large layer optimisation and security gate", "Data Science", [
      {
        id: "src-1",
        kind: {
          TAG: "Source",
          imageRef: "cgr.dev/chainguard/python",
          tag: "latest-dev"
        },
        x: 50.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Python Base",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "build-1",
        kind: {
          TAG: "BuildStep",
          command: "pip install -r requirements.txt",
          layer: 1
        },
        x: 300.0,
        y: 140.0,
        width: 180.0,
        height: 80.0,
        label: "Install Deps",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "build-2",
        kind: {
          TAG: "BuildStep",
          command: "COPY model/ /app/model",
          layer: 2
        },
        x: 300.0,
        y: 260.0,
        width: 180.0,
        height: 80.0,
        label: "Copy Model Weights",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "sec-1",
        kind: {
          TAG: "SecurityGate",
          policy: "ml-supply-chain",
          mode: "audit"
        },
        x: 550.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Supply Chain Gate",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "push-1",
        kind: {
          TAG: "Push",
          registry: "ghcr.io",
          repository: "org/ml-model"
        },
        x: 800.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Push",
        status: "Idle",
        validationErrors: []
      }
    ], [
      {
        id: "c1",
        fromNode: "src-1",
        fromPort: "output",
        toNode: "build-1",
        toPort: "input"
      },
      {
        id: "c2",
        fromNode: "src-1",
        fromPort: "output",
        toNode: "build-2",
        toPort: "input"
      },
      {
        id: "c3",
        fromNode: "build-1",
        fromPort: "output",
        toNode: "sec-1",
        toPort: "input"
      },
      {
        id: "c4",
        fromNode: "build-2",
        fromPort: "output",
        toNode: "sec-1",
        toPort: "input"
      },
      {
        id: "c5",
        fromNode: "sec-1",
        fromPort: "output",
        toNode: "push-1",
        toPort: "input"
      }
    ]),
    makeTemplate("tpl-database", "Database", "Database container with persistent volume and custom init scripts", "Infrastructure", [
      {
        id: "src-1",
        kind: {
          TAG: "Source",
          imageRef: "cgr.dev/chainguard/postgres",
          tag: "latest"
        },
        x: 50.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "PostgreSQL Base",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "build-1",
        kind: {
          TAG: "BuildStep",
          command: "COPY init.sql /docker-entrypoint-initdb.d/",
          layer: 1
        },
        x: 300.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Init Scripts",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "sec-1",
        kind: {
          TAG: "SecurityGate",
          policy: "database-hardening",
          mode: "enforce"
        },
        x: 550.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Hardening Gate",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "sign-1",
        kind: {
          TAG: "SignStep",
          keyId: "infra-key",
          transparency: false
        },
        x: 800.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Sign",
        status: "Idle",
        validationErrors: []
      }
    ], [
      {
        id: "c1",
        fromNode: "src-1",
        fromPort: "output",
        toNode: "build-1",
        toPort: "input"
      },
      {
        id: "c2",
        fromNode: "build-1",
        fromPort: "output",
        toNode: "sec-1",
        toPort: "input"
      },
      {
        id: "c3",
        fromNode: "sec-1",
        fromPort: "output",
        toNode: "sign-1",
        toPort: "input"
      }
    ]),
    makeTemplate("tpl-multi-service", "Multi-Service", "Compose-based multi-service stack with shared security policy", "Infrastructure", [
      {
        id: "src-api",
        kind: {
          TAG: "Source",
          imageRef: "cgr.dev/chainguard/wolfi-base",
          tag: "latest"
        },
        x: 50.0,
        y: 100.0,
        width: 180.0,
        height: 80.0,
        label: "API Base",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "src-worker",
        kind: {
          TAG: "Source",
          imageRef: "cgr.dev/chainguard/wolfi-base",
          tag: "latest"
        },
        x: 50.0,
        y: 300.0,
        width: 180.0,
        height: 80.0,
        label: "Worker Base",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "build-api",
        kind: {
          TAG: "BuildStep",
          command: "COPY api/ /app && RUN deno cache main.ts",
          layer: 1
        },
        x: 300.0,
        y: 100.0,
        width: 180.0,
        height: 80.0,
        label: "Build API",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "build-worker",
        kind: {
          TAG: "BuildStep",
          command: "COPY worker/ /app && RUN deno cache worker.ts",
          layer: 1
        },
        x: 300.0,
        y: 300.0,
        width: 180.0,
        height: 80.0,
        label: "Build Worker",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "compose-1",
        kind: {
          TAG: "Compose",
          services: [
            "api",
            "worker",
            "redis"
          ]
        },
        x: 550.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Compose Stack",
        status: "Idle",
        validationErrors: []
      },
      {
        id: "sec-1",
        kind: {
          TAG: "SecurityGate",
          policy: "strict",
          mode: "enforce"
        },
        x: 800.0,
        y: 200.0,
        width: 180.0,
        height: 80.0,
        label: "Security Gate",
        status: "Idle",
        validationErrors: []
      }
    ], [
      {
        id: "c1",
        fromNode: "src-api",
        fromPort: "output",
        toNode: "build-api",
        toPort: "input"
      },
      {
        id: "c2",
        fromNode: "src-worker",
        fromPort: "output",
        toNode: "build-worker",
        toPort: "input"
      },
      {
        id: "c3",
        fromNode: "build-api",
        fromPort: "output",
        toNode: "compose-1",
        toPort: "api"
      },
      {
        id: "c4",
        fromNode: "build-worker",
        fromPort: "output",
        toNode: "compose-1",
        toPort: "worker"
      },
      {
        id: "c5",
        fromNode: "compose-1",
        fromPort: "output",
        toNode: "sec-1",
        toPort: "input"
      }
    ])
  ];
}

function initialState() {
  return {
    pipeline: emptyPipeline(),
    panels: {
      leftPanelWidth: 260.0,
      rightPanelWidth: 320.0,
      leftCollapsed: false,
      rightCollapsed: false,
      activeLeftTab: "Components",
      activeRightTab: "Preview"
    },
    validation: undefined,
    outputFormat: "Containerfile",
    generatedOutput: undefined,
    isDragging: undefined,
    isConnecting: undefined,
    templates: defaultTemplates(),
    recentPipelines: [],
    isDirty: false
  };
}

export {
  generateId,
  emptyPipeline,
  defaultPanelState,
  nodeColor,
  nodeIcon,
  nodeKindToString,
  outputFormatToString,
  makeTemplate,
  defaultTemplates,
  initialState,
}
/* No side effect */
