// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as PipelineModel from "./PipelineModel.res.js";

function snapToGrid(v) {
  return Math.round(v / 20.0) * 20.0;
}

function genId() {
  return PipelineModel.generateId();
}

function hasCycle(nodes, connections) {
  let visited = {};
  let inStack = {};
  let dfs = nodeId => {
    visited[nodeId] = true;
    inStack[nodeId] = true;
    let outgoing = Belt_Array.keep(connections, c => c.fromNode === nodeId);
    let foundCycle = Belt_Array.some(outgoing, c => {
      let match = inStack[c.toNode];
      if (match !== undefined && match) {
        return true;
      }
      let match$1 = visited[c.toNode];
      if (match$1 !== undefined && match$1) {
        return false;
      } else {
        return dfs(c.toNode);
      }
    });
    inStack[nodeId] = false;
    return foundCycle;
  };
  return Belt_Array.some(nodes, n => {
    let match = visited[n.id];
    if (match !== undefined && match) {
      return false;
    } else {
      return dfs(n.id);
    }
  });
}

function validatePipeline(pipeline) {
  let errors = [];
  let warnings = [];
  if (pipeline.nodes.length === 0) {
    Belt_Array.concat(errors, [{
        nodeId: "",
        message: "Pipeline has no nodes"
      }]);
  }
  let orphans = Belt_Array.keep(pipeline.nodes, n => {
    let hasIncoming = Belt_Array.some(pipeline.connections, c => c.toNode === n.id);
    let hasOutgoing = Belt_Array.some(pipeline.connections, c => c.fromNode === n.id);
    if (hasIncoming) {
      return false;
    } else {
      return !hasOutgoing;
    }
  });
  Belt_Array.forEach(orphans, n => {
    Belt_Array.concat(warnings, [{
        nodeId: n.id,
        message: n.label + " has no connections"
      }]);
  });
  if (hasCycle(pipeline.nodes, pipeline.connections)) {
    Belt_Array.concat(errors, [{
        nodeId: "",
        message: "Pipeline contains a cycle"
      }]);
  }
  return {
    isValid: errors.length === 0,
    errors: errors,
    warnings: warnings,
    securityScore: 0.0,
    estimatedImageSize: 0
  };
}

function generateOutput(pipeline, format) {
  if (format !== "Containerfile") {
    return "# " + PipelineModel.outputFormatToString(format) + " output\n# Generated from pipeline: " + pipeline.name + "\n# Nodes: " + String(pipeline.nodes.length);
  }
  let lines = Belt_Array.map(pipeline.nodes, n => {
    let match = n.kind;
    switch (match.TAG) {
      case "Source" :
        return "FROM " + match.imageRef + ":" + match.tag;
      case "BuildStep" :
        return "RUN " + match.command;
      default:
        return "# " + PipelineModel.nodeKindToString(n.kind);
    }
  });
  return lines.join("\n");
}

function update(state, msg) {
  if (typeof msg !== "object") {
    switch (msg) {
      case "TogglePaletteCollapsed" :
        let init = state.panels;
        let panels_leftPanelWidth = init.leftPanelWidth;
        let panels_rightPanelWidth = init.rightPanelWidth;
        let panels_leftCollapsed = !state.panels.leftCollapsed;
        let panels_rightCollapsed = init.rightCollapsed;
        let panels_activeLeftTab = init.activeLeftTab;
        let panels_activeRightTab = init.activeRightTab;
        let panels = {
          leftPanelWidth: panels_leftPanelWidth,
          rightPanelWidth: panels_rightPanelWidth,
          leftCollapsed: panels_leftCollapsed,
          rightCollapsed: panels_rightCollapsed,
          activeLeftTab: panels_activeLeftTab,
          activeRightTab: panels_activeRightTab
        };
        return {
          pipeline: state.pipeline,
          panels: panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "ToggleOutputCollapsed" :
        let init$1 = state.panels;
        let panels_leftPanelWidth$1 = init$1.leftPanelWidth;
        let panels_rightPanelWidth$1 = init$1.rightPanelWidth;
        let panels_leftCollapsed$1 = init$1.leftCollapsed;
        let panels_rightCollapsed$1 = !state.panels.rightCollapsed;
        let panels_activeLeftTab$1 = init$1.activeLeftTab;
        let panels_activeRightTab$1 = init$1.activeRightTab;
        let panels$1 = {
          leftPanelWidth: panels_leftPanelWidth$1,
          rightPanelWidth: panels_rightPanelWidth$1,
          leftCollapsed: panels_leftCollapsed$1,
          rightCollapsed: panels_rightCollapsed$1,
          activeLeftTab: panels_activeLeftTab$1,
          activeRightTab: panels_activeRightTab$1
        };
        return {
          pipeline: state.pipeline,
          panels: panels$1,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "RegeneratePreview" :
        let output = generateOutput(state.pipeline, state.outputFormat);
        return {
          pipeline: state.pipeline,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: output,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "RunValidation" :
        let result = validatePipeline(state.pipeline);
        let nodes = Belt_Array.map(state.pipeline.nodes, n => {
          let nodeErrors = Belt_Array.keep(result.errors, e => e.nodeId === n.id);
          let errorMsgs = Belt_Array.map(nodeErrors, e => e.message);
          return {
            id: n.id,
            kind: n.kind,
            x: n.x,
            y: n.y,
            width: n.width,
            height: n.height,
            label: n.label,
            status: n.status,
            validationErrors: errorMsgs
          };
        });
        let init$2 = state.pipeline;
        let pipeline_id = init$2.id;
        let pipeline_name = init$2.name;
        let pipeline_description = init$2.description;
        let pipeline_connections = init$2.connections;
        let pipeline_selectedNode = init$2.selectedNode;
        let pipeline_selectedConnection = init$2.selectedConnection;
        let pipeline_zoom = init$2.zoom;
        let pipeline_panX = init$2.panX;
        let pipeline_panY = init$2.panY;
        let pipeline = {
          id: pipeline_id,
          name: pipeline_name,
          description: pipeline_description,
          nodes: nodes,
          connections: pipeline_connections,
          selectedNode: pipeline_selectedNode,
          selectedConnection: pipeline_selectedConnection,
          zoom: pipeline_zoom,
          panX: pipeline_panX,
          panY: pipeline_panY
        };
        return {
          pipeline: pipeline,
          panels: state.panels,
          validation: result,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "ZoomIn" :
        let zoom = Math.min(state.pipeline.zoom * 1.2, 3.0);
        let init$3 = state.pipeline;
        let pipeline_id$1 = init$3.id;
        let pipeline_name$1 = init$3.name;
        let pipeline_description$1 = init$3.description;
        let pipeline_nodes = init$3.nodes;
        let pipeline_connections$1 = init$3.connections;
        let pipeline_selectedNode$1 = init$3.selectedNode;
        let pipeline_selectedConnection$1 = init$3.selectedConnection;
        let pipeline_panX$1 = init$3.panX;
        let pipeline_panY$1 = init$3.panY;
        let pipeline$1 = {
          id: pipeline_id$1,
          name: pipeline_name$1,
          description: pipeline_description$1,
          nodes: pipeline_nodes,
          connections: pipeline_connections$1,
          selectedNode: pipeline_selectedNode$1,
          selectedConnection: pipeline_selectedConnection$1,
          zoom: zoom,
          panX: pipeline_panX$1,
          panY: pipeline_panY$1
        };
        return {
          pipeline: pipeline$1,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "ZoomOut" :
        let zoom$1 = Math.max(state.pipeline.zoom / 1.2, 0.3);
        let init$4 = state.pipeline;
        let pipeline_id$2 = init$4.id;
        let pipeline_name$2 = init$4.name;
        let pipeline_description$2 = init$4.description;
        let pipeline_nodes$1 = init$4.nodes;
        let pipeline_connections$2 = init$4.connections;
        let pipeline_selectedNode$2 = init$4.selectedNode;
        let pipeline_selectedConnection$2 = init$4.selectedConnection;
        let pipeline_panX$2 = init$4.panX;
        let pipeline_panY$2 = init$4.panY;
        let pipeline$2 = {
          id: pipeline_id$2,
          name: pipeline_name$2,
          description: pipeline_description$2,
          nodes: pipeline_nodes$1,
          connections: pipeline_connections$2,
          selectedNode: pipeline_selectedNode$2,
          selectedConnection: pipeline_selectedConnection$2,
          zoom: zoom$1,
          panX: pipeline_panX$2,
          panY: pipeline_panY$2
        };
        return {
          pipeline: pipeline$2,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "ResetZoom" :
        let init$5 = state.pipeline;
        let pipeline_id$3 = init$5.id;
        let pipeline_name$3 = init$5.name;
        let pipeline_description$3 = init$5.description;
        let pipeline_nodes$2 = init$5.nodes;
        let pipeline_connections$3 = init$5.connections;
        let pipeline_selectedNode$3 = init$5.selectedNode;
        let pipeline_selectedConnection$3 = init$5.selectedConnection;
        let pipeline$3 = {
          id: pipeline_id$3,
          name: pipeline_name$3,
          description: pipeline_description$3,
          nodes: pipeline_nodes$2,
          connections: pipeline_connections$3,
          selectedNode: pipeline_selectedNode$3,
          selectedConnection: pipeline_selectedConnection$3,
          zoom: 1.0,
          panX: 0.0,
          panY: 0.0
        };
        return {
          pipeline: pipeline$3,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "EndDrag" :
        return {
          pipeline: state.pipeline,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: undefined,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "CancelConnect" :
        return {
          pipeline: state.pipeline,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: undefined,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "DeleteSelected" :
        let nodeId = state.pipeline.selectedNode;
        if (nodeId !== undefined) {
          let nodes$1 = Belt_Array.keep(state.pipeline.nodes, n => n.id !== nodeId);
          let connections = Belt_Array.keep(state.pipeline.connections, c => {
            if (c.fromNode !== nodeId) {
              return c.toNode !== nodeId;
            } else {
              return false;
            }
          });
          let init$6 = state.pipeline;
          let pipeline_id$4 = init$6.id;
          let pipeline_name$4 = init$6.name;
          let pipeline_description$4 = init$6.description;
          let pipeline_selectedConnection$4 = init$6.selectedConnection;
          let pipeline_zoom$1 = init$6.zoom;
          let pipeline_panX$3 = init$6.panX;
          let pipeline_panY$3 = init$6.panY;
          let pipeline$4 = {
            id: pipeline_id$4,
            name: pipeline_name$4,
            description: pipeline_description$4,
            nodes: nodes$1,
            connections: connections,
            selectedNode: undefined,
            selectedConnection: pipeline_selectedConnection$4,
            zoom: pipeline_zoom$1,
            panX: pipeline_panX$3,
            panY: pipeline_panY$3
          };
          return {
            pipeline: pipeline$4,
            panels: state.panels,
            validation: state.validation,
            outputFormat: state.outputFormat,
            generatedOutput: state.generatedOutput,
            isDragging: state.isDragging,
            isConnecting: state.isConnecting,
            templates: state.templates,
            recentPipelines: state.recentPipelines,
            isDirty: true
          };
        }
        let connId = state.pipeline.selectedConnection;
        if (connId === undefined) {
          return state;
        }
        let connections$1 = Belt_Array.keep(state.pipeline.connections, c => c.id !== connId);
        let init$7 = state.pipeline;
        let pipeline_id$5 = init$7.id;
        let pipeline_name$5 = init$7.name;
        let pipeline_description$5 = init$7.description;
        let pipeline_nodes$3 = init$7.nodes;
        let pipeline_selectedNode$4 = init$7.selectedNode;
        let pipeline_zoom$2 = init$7.zoom;
        let pipeline_panX$4 = init$7.panX;
        let pipeline_panY$4 = init$7.panY;
        let pipeline$5 = {
          id: pipeline_id$5,
          name: pipeline_name$5,
          description: pipeline_description$5,
          nodes: pipeline_nodes$3,
          connections: connections$1,
          selectedNode: pipeline_selectedNode$4,
          selectedConnection: undefined,
          zoom: pipeline_zoom$2,
          panX: pipeline_panX$4,
          panY: pipeline_panY$4
        };
        return {
          pipeline: pipeline$5,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "SavePipeline" :
        console.log("Saving pipeline...");
        return {
          pipeline: state.pipeline,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: false
        };
      case "PipelineSaved" :
        return {
          pipeline: state.pipeline,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: false
        };
      default:
        return state;
    }
  } else {
    switch (msg.TAG) {
      case "AddNode" :
        let pos = msg._1;
        let kind = msg._0;
        let node_id = PipelineModel.generateId();
        let node_x = snapToGrid(pos.x);
        let node_y = snapToGrid(pos.y);
        let node_label = PipelineModel.nodeKindToString(kind);
        let node_validationErrors = [];
        let node = {
          id: node_id,
          kind: kind,
          x: node_x,
          y: node_y,
          width: 180.0,
          height: 80.0,
          label: node_label,
          status: "Idle",
          validationErrors: node_validationErrors
        };
        let init$8 = state.pipeline;
        let pipeline_id$6 = init$8.id;
        let pipeline_name$6 = init$8.name;
        let pipeline_description$6 = init$8.description;
        let pipeline_nodes$4 = Belt_Array.concat(state.pipeline.nodes, [node]);
        let pipeline_connections$4 = init$8.connections;
        let pipeline_selectedNode$5 = init$8.selectedNode;
        let pipeline_selectedConnection$5 = init$8.selectedConnection;
        let pipeline_zoom$3 = init$8.zoom;
        let pipeline_panX$5 = init$8.panX;
        let pipeline_panY$5 = init$8.panY;
        let pipeline$6 = {
          id: pipeline_id$6,
          name: pipeline_name$6,
          description: pipeline_description$6,
          nodes: pipeline_nodes$4,
          connections: pipeline_connections$4,
          selectedNode: pipeline_selectedNode$5,
          selectedConnection: pipeline_selectedConnection$5,
          zoom: pipeline_zoom$3,
          panX: pipeline_panX$5,
          panY: pipeline_panY$5
        };
        return {
          pipeline: pipeline$6,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "RemoveNode" :
        let nodeId$1 = msg._0;
        let nodes$2 = Belt_Array.keep(state.pipeline.nodes, n => n.id !== nodeId$1);
        let connections$2 = Belt_Array.keep(state.pipeline.connections, c => {
          if (c.fromNode !== nodeId$1) {
            return c.toNode !== nodeId$1;
          } else {
            return false;
          }
        });
        let id = state.pipeline.selectedNode;
        let selectedNode = id !== undefined && id === nodeId$1 ? undefined : id;
        let init$9 = state.pipeline;
        let pipeline_id$7 = init$9.id;
        let pipeline_name$7 = init$9.name;
        let pipeline_description$7 = init$9.description;
        let pipeline_selectedConnection$6 = init$9.selectedConnection;
        let pipeline_zoom$4 = init$9.zoom;
        let pipeline_panX$6 = init$9.panX;
        let pipeline_panY$6 = init$9.panY;
        let pipeline$7 = {
          id: pipeline_id$7,
          name: pipeline_name$7,
          description: pipeline_description$7,
          nodes: nodes$2,
          connections: connections$2,
          selectedNode: selectedNode,
          selectedConnection: pipeline_selectedConnection$6,
          zoom: pipeline_zoom$4,
          panX: pipeline_panX$6,
          panY: pipeline_panY$6
        };
        return {
          pipeline: pipeline$7,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "MoveNode" :
        let pos$1 = msg._1;
        let nodeId$2 = msg._0;
        let nodes$3 = Belt_Array.map(state.pipeline.nodes, n => {
          if (n.id === nodeId$2) {
            return {
              id: n.id,
              kind: n.kind,
              x: snapToGrid(pos$1.x),
              y: snapToGrid(pos$1.y),
              width: n.width,
              height: n.height,
              label: n.label,
              status: n.status,
              validationErrors: n.validationErrors
            };
          } else {
            return n;
          }
        });
        let init$10 = state.pipeline;
        let pipeline_id$8 = init$10.id;
        let pipeline_name$8 = init$10.name;
        let pipeline_description$8 = init$10.description;
        let pipeline_connections$5 = init$10.connections;
        let pipeline_selectedNode$6 = init$10.selectedNode;
        let pipeline_selectedConnection$7 = init$10.selectedConnection;
        let pipeline_zoom$5 = init$10.zoom;
        let pipeline_panX$7 = init$10.panX;
        let pipeline_panY$7 = init$10.panY;
        let pipeline$8 = {
          id: pipeline_id$8,
          name: pipeline_name$8,
          description: pipeline_description$8,
          nodes: nodes$3,
          connections: pipeline_connections$5,
          selectedNode: pipeline_selectedNode$6,
          selectedConnection: pipeline_selectedConnection$7,
          zoom: pipeline_zoom$5,
          panX: pipeline_panX$7,
          panY: pipeline_panY$7
        };
        return {
          pipeline: pipeline$8,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "SelectNode" :
        let init$11 = state.pipeline;
        let pipeline_id$9 = init$11.id;
        let pipeline_name$9 = init$11.name;
        let pipeline_description$9 = init$11.description;
        let pipeline_nodes$5 = init$11.nodes;
        let pipeline_connections$6 = init$11.connections;
        let pipeline_selectedNode$7 = msg._0;
        let pipeline_selectedConnection$8 = init$11.selectedConnection;
        let pipeline_zoom$6 = init$11.zoom;
        let pipeline_panX$8 = init$11.panX;
        let pipeline_panY$8 = init$11.panY;
        let pipeline$9 = {
          id: pipeline_id$9,
          name: pipeline_name$9,
          description: pipeline_description$9,
          nodes: pipeline_nodes$5,
          connections: pipeline_connections$6,
          selectedNode: pipeline_selectedNode$7,
          selectedConnection: pipeline_selectedConnection$8,
          zoom: pipeline_zoom$6,
          panX: pipeline_panX$8,
          panY: pipeline_panY$8
        };
        return {
          pipeline: pipeline$9,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "UpdateNodeConfig" :
        return {
          pipeline: state.pipeline,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "UpdateNodeLabel" :
        let label = msg._1;
        let nodeId$3 = msg._0;
        let nodes$4 = Belt_Array.map(state.pipeline.nodes, n => {
          if (n.id === nodeId$3) {
            return {
              id: n.id,
              kind: n.kind,
              x: n.x,
              y: n.y,
              width: n.width,
              height: n.height,
              label: label,
              status: n.status,
              validationErrors: n.validationErrors
            };
          } else {
            return n;
          }
        });
        let init$12 = state.pipeline;
        let pipeline_id$10 = init$12.id;
        let pipeline_name$10 = init$12.name;
        let pipeline_description$10 = init$12.description;
        let pipeline_connections$7 = init$12.connections;
        let pipeline_selectedNode$8 = init$12.selectedNode;
        let pipeline_selectedConnection$9 = init$12.selectedConnection;
        let pipeline_zoom$7 = init$12.zoom;
        let pipeline_panX$9 = init$12.panX;
        let pipeline_panY$9 = init$12.panY;
        let pipeline$10 = {
          id: pipeline_id$10,
          name: pipeline_name$10,
          description: pipeline_description$10,
          nodes: nodes$4,
          connections: pipeline_connections$7,
          selectedNode: pipeline_selectedNode$8,
          selectedConnection: pipeline_selectedConnection$9,
          zoom: pipeline_zoom$7,
          panX: pipeline_panX$9,
          panY: pipeline_panY$9
        };
        return {
          pipeline: pipeline$10,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "AddEdge" :
        let conn_id = PipelineModel.generateId();
        let conn_fromNode = msg._0;
        let conn_fromPort = msg._1;
        let conn_toNode = msg._2;
        let conn_toPort = msg._3;
        let conn = {
          id: conn_id,
          fromNode: conn_fromNode,
          fromPort: conn_fromPort,
          toNode: conn_toNode,
          toPort: conn_toPort
        };
        let connections$3 = Belt_Array.concat(state.pipeline.connections, [conn]);
        let init$13 = state.pipeline;
        let pipeline_id$11 = init$13.id;
        let pipeline_name$11 = init$13.name;
        let pipeline_description$11 = init$13.description;
        let pipeline_nodes$6 = init$13.nodes;
        let pipeline_selectedNode$9 = init$13.selectedNode;
        let pipeline_selectedConnection$10 = init$13.selectedConnection;
        let pipeline_zoom$8 = init$13.zoom;
        let pipeline_panX$10 = init$13.panX;
        let pipeline_panY$10 = init$13.panY;
        let pipeline$11 = {
          id: pipeline_id$11,
          name: pipeline_name$11,
          description: pipeline_description$11,
          nodes: pipeline_nodes$6,
          connections: connections$3,
          selectedNode: pipeline_selectedNode$9,
          selectedConnection: pipeline_selectedConnection$10,
          zoom: pipeline_zoom$8,
          panX: pipeline_panX$10,
          panY: pipeline_panY$10
        };
        return {
          pipeline: pipeline$11,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "RemoveEdge" :
        let edgeId = msg._0;
        let connections$4 = Belt_Array.keep(state.pipeline.connections, c => c.id !== edgeId);
        let init$14 = state.pipeline;
        let pipeline_id$12 = init$14.id;
        let pipeline_name$12 = init$14.name;
        let pipeline_description$12 = init$14.description;
        let pipeline_nodes$7 = init$14.nodes;
        let pipeline_selectedNode$10 = init$14.selectedNode;
        let pipeline_selectedConnection$11 = init$14.selectedConnection;
        let pipeline_zoom$9 = init$14.zoom;
        let pipeline_panX$11 = init$14.panX;
        let pipeline_panY$11 = init$14.panY;
        let pipeline$12 = {
          id: pipeline_id$12,
          name: pipeline_name$12,
          description: pipeline_description$12,
          nodes: pipeline_nodes$7,
          connections: connections$4,
          selectedNode: pipeline_selectedNode$10,
          selectedConnection: pipeline_selectedConnection$11,
          zoom: pipeline_zoom$9,
          panX: pipeline_panX$11,
          panY: pipeline_panY$11
        };
        return {
          pipeline: pipeline$12,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "SetPipelineName" :
        let init$15 = state.pipeline;
        let pipeline_id$13 = init$15.id;
        let pipeline_name$13 = msg._0;
        let pipeline_description$13 = init$15.description;
        let pipeline_nodes$8 = init$15.nodes;
        let pipeline_connections$8 = init$15.connections;
        let pipeline_selectedNode$11 = init$15.selectedNode;
        let pipeline_selectedConnection$12 = init$15.selectedConnection;
        let pipeline_zoom$10 = init$15.zoom;
        let pipeline_panX$12 = init$15.panX;
        let pipeline_panY$12 = init$15.panY;
        let pipeline$13 = {
          id: pipeline_id$13,
          name: pipeline_name$13,
          description: pipeline_description$13,
          nodes: pipeline_nodes$8,
          connections: pipeline_connections$8,
          selectedNode: pipeline_selectedNode$11,
          selectedConnection: pipeline_selectedConnection$12,
          zoom: pipeline_zoom$10,
          panX: pipeline_panX$12,
          panY: pipeline_panY$12
        };
        return {
          pipeline: pipeline$13,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "SetPaletteTab" :
        let init$16 = state.panels;
        let panels_leftPanelWidth$2 = init$16.leftPanelWidth;
        let panels_rightPanelWidth$2 = init$16.rightPanelWidth;
        let panels_leftCollapsed$2 = init$16.leftCollapsed;
        let panels_rightCollapsed$2 = init$16.rightCollapsed;
        let panels_activeLeftTab$2 = msg._0;
        let panels_activeRightTab$2 = init$16.activeRightTab;
        let panels$2 = {
          leftPanelWidth: panels_leftPanelWidth$2,
          rightPanelWidth: panels_rightPanelWidth$2,
          leftCollapsed: panels_leftCollapsed$2,
          rightCollapsed: panels_rightCollapsed$2,
          activeLeftTab: panels_activeLeftTab$2,
          activeRightTab: panels_activeRightTab$2
        };
        return {
          pipeline: state.pipeline,
          panels: panels$2,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "SetPaletteWidth" :
        let init$17 = state.panels;
        let panels_leftPanelWidth$3 = msg._0;
        let panels_rightPanelWidth$3 = init$17.rightPanelWidth;
        let panels_leftCollapsed$3 = init$17.leftCollapsed;
        let panels_rightCollapsed$3 = init$17.rightCollapsed;
        let panels_activeLeftTab$3 = init$17.activeLeftTab;
        let panels_activeRightTab$3 = init$17.activeRightTab;
        let panels$3 = {
          leftPanelWidth: panels_leftPanelWidth$3,
          rightPanelWidth: panels_rightPanelWidth$3,
          leftCollapsed: panels_leftCollapsed$3,
          rightCollapsed: panels_rightCollapsed$3,
          activeLeftTab: panels_activeLeftTab$3,
          activeRightTab: panels_activeRightTab$3
        };
        return {
          pipeline: state.pipeline,
          panels: panels$3,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "SetOutputTab" :
        let init$18 = state.panels;
        let panels_leftPanelWidth$4 = init$18.leftPanelWidth;
        let panels_rightPanelWidth$4 = init$18.rightPanelWidth;
        let panels_leftCollapsed$4 = init$18.leftCollapsed;
        let panels_rightCollapsed$4 = init$18.rightCollapsed;
        let panels_activeLeftTab$4 = init$18.activeLeftTab;
        let panels_activeRightTab$4 = msg._0;
        let panels$4 = {
          leftPanelWidth: panels_leftPanelWidth$4,
          rightPanelWidth: panels_rightPanelWidth$4,
          leftCollapsed: panels_leftCollapsed$4,
          rightCollapsed: panels_rightCollapsed$4,
          activeLeftTab: panels_activeLeftTab$4,
          activeRightTab: panels_activeRightTab$4
        };
        return {
          pipeline: state.pipeline,
          panels: panels$4,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "SetOutputWidth" :
        let init$19 = state.panels;
        let panels_leftPanelWidth$5 = init$19.leftPanelWidth;
        let panels_rightPanelWidth$5 = msg._0;
        let panels_leftCollapsed$5 = init$19.leftCollapsed;
        let panels_rightCollapsed$5 = init$19.rightCollapsed;
        let panels_activeLeftTab$5 = init$19.activeLeftTab;
        let panels_activeRightTab$5 = init$19.activeRightTab;
        let panels$5 = {
          leftPanelWidth: panels_leftPanelWidth$5,
          rightPanelWidth: panels_rightPanelWidth$5,
          leftCollapsed: panels_leftCollapsed$5,
          rightCollapsed: panels_rightCollapsed$5,
          activeLeftTab: panels_activeLeftTab$5,
          activeRightTab: panels_activeRightTab$5
        };
        return {
          pipeline: state.pipeline,
          panels: panels$5,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "SetOutputFormat" :
        return {
          pipeline: state.pipeline,
          panels: state.panels,
          validation: state.validation,
          outputFormat: msg._0,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "LoadTemplate" :
        let pipeline$14 = msg._0.pipeline;
        return {
          pipeline: pipeline$14,
          panels: state.panels,
          validation: undefined,
          outputFormat: state.outputFormat,
          generatedOutput: undefined,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: false
        };
      case "ValidationComplete" :
        return {
          pipeline: state.pipeline,
          panels: state.panels,
          validation: msg._0,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "SetZoom" :
        let init$20 = state.pipeline;
        let pipeline_id$14 = init$20.id;
        let pipeline_name$14 = init$20.name;
        let pipeline_description$14 = init$20.description;
        let pipeline_nodes$9 = init$20.nodes;
        let pipeline_connections$9 = init$20.connections;
        let pipeline_selectedNode$12 = init$20.selectedNode;
        let pipeline_selectedConnection$13 = init$20.selectedConnection;
        let pipeline_zoom$11 = msg._0;
        let pipeline_panX$13 = init$20.panX;
        let pipeline_panY$13 = init$20.panY;
        let pipeline$15 = {
          id: pipeline_id$14,
          name: pipeline_name$14,
          description: pipeline_description$14,
          nodes: pipeline_nodes$9,
          connections: pipeline_connections$9,
          selectedNode: pipeline_selectedNode$12,
          selectedConnection: pipeline_selectedConnection$13,
          zoom: pipeline_zoom$11,
          panX: pipeline_panX$13,
          panY: pipeline_panY$13
        };
        return {
          pipeline: pipeline$15,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "PanCanvas" :
        let pos$2 = msg._0;
        let init$21 = state.pipeline;
        let pipeline_id$15 = init$21.id;
        let pipeline_name$15 = init$21.name;
        let pipeline_description$15 = init$21.description;
        let pipeline_nodes$10 = init$21.nodes;
        let pipeline_connections$10 = init$21.connections;
        let pipeline_selectedNode$13 = init$21.selectedNode;
        let pipeline_selectedConnection$14 = init$21.selectedConnection;
        let pipeline_zoom$12 = init$21.zoom;
        let pipeline_panX$14 = pos$2.x;
        let pipeline_panY$14 = pos$2.y;
        let pipeline$16 = {
          id: pipeline_id$15,
          name: pipeline_name$15,
          description: pipeline_description$15,
          nodes: pipeline_nodes$10,
          connections: pipeline_connections$10,
          selectedNode: pipeline_selectedNode$13,
          selectedConnection: pipeline_selectedConnection$14,
          zoom: pipeline_zoom$12,
          panX: pipeline_panX$14,
          panY: pipeline_panY$14
        };
        return {
          pipeline: pipeline$16,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "SetPan" :
        let init$22 = state.pipeline;
        let pipeline_id$16 = init$22.id;
        let pipeline_name$16 = init$22.name;
        let pipeline_description$16 = init$22.description;
        let pipeline_nodes$11 = init$22.nodes;
        let pipeline_connections$11 = init$22.connections;
        let pipeline_selectedNode$14 = init$22.selectedNode;
        let pipeline_selectedConnection$15 = init$22.selectedConnection;
        let pipeline_zoom$13 = init$22.zoom;
        let pipeline_panX$15 = msg._0;
        let pipeline_panY$15 = msg._1;
        let pipeline$17 = {
          id: pipeline_id$16,
          name: pipeline_name$16,
          description: pipeline_description$16,
          nodes: pipeline_nodes$11,
          connections: pipeline_connections$11,
          selectedNode: pipeline_selectedNode$14,
          selectedConnection: pipeline_selectedConnection$15,
          zoom: pipeline_zoom$13,
          panX: pipeline_panX$15,
          panY: pipeline_panY$15
        };
        return {
          pipeline: pipeline$17,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "StartDrag" :
        return {
          pipeline: state.pipeline,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: {
            nodeId: msg._0,
            offsetX: msg._1,
            offsetY: msg._2
          },
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "UpdateDrag" :
        let match = state.isDragging;
        if (match === undefined) {
          return state;
        }
        let nodeId$4 = match.nodeId;
        let x = snapToGrid(msg._0 - match.offsetX);
        let y = snapToGrid(msg._1 - match.offsetY);
        let nodes$5 = Belt_Array.map(state.pipeline.nodes, n => {
          if (n.id === nodeId$4) {
            return {
              id: n.id,
              kind: n.kind,
              x: x,
              y: y,
              width: n.width,
              height: n.height,
              label: n.label,
              status: n.status,
              validationErrors: n.validationErrors
            };
          } else {
            return n;
          }
        });
        let init$23 = state.pipeline;
        let pipeline_id$17 = init$23.id;
        let pipeline_name$17 = init$23.name;
        let pipeline_description$17 = init$23.description;
        let pipeline_connections$12 = init$23.connections;
        let pipeline_selectedNode$15 = init$23.selectedNode;
        let pipeline_selectedConnection$16 = init$23.selectedConnection;
        let pipeline_zoom$14 = init$23.zoom;
        let pipeline_panX$16 = init$23.panX;
        let pipeline_panY$16 = init$23.panY;
        let pipeline$18 = {
          id: pipeline_id$17,
          name: pipeline_name$17,
          description: pipeline_description$17,
          nodes: nodes$5,
          connections: pipeline_connections$12,
          selectedNode: pipeline_selectedNode$15,
          selectedConnection: pipeline_selectedConnection$16,
          zoom: pipeline_zoom$14,
          panX: pipeline_panX$16,
          panY: pipeline_panY$16
        };
        return {
          pipeline: pipeline$18,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "StartConnect" :
        return {
          pipeline: state.pipeline,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: {
            fromNode: msg._0,
            fromPort: msg._1,
            mouseX: msg._2,
            mouseY: msg._3
          },
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "UpdateConnect" :
        let cs = state.isConnecting;
        if (cs !== undefined) {
          return {
            pipeline: state.pipeline,
            panels: state.panels,
            validation: state.validation,
            outputFormat: state.outputFormat,
            generatedOutput: state.generatedOutput,
            isDragging: state.isDragging,
            isConnecting: {
              fromNode: cs.fromNode,
              fromPort: cs.fromPort,
              mouseX: msg._0,
              mouseY: msg._1
            },
            templates: state.templates,
            recentPipelines: state.recentPipelines,
            isDirty: state.isDirty
          };
        } else {
          return state;
        }
      case "EndConnect" :
        let match$1 = state.isConnecting;
        if (match$1 === undefined) {
          return state;
        }
        let conn_id$1 = PipelineModel.generateId();
        let conn_fromNode$1 = match$1.fromNode;
        let conn_fromPort$1 = match$1.fromPort;
        let conn_toNode$1 = msg._0;
        let conn_toPort$1 = msg._1;
        let conn$1 = {
          id: conn_id$1,
          fromNode: conn_fromNode$1,
          fromPort: conn_fromPort$1,
          toNode: conn_toNode$1,
          toPort: conn_toPort$1
        };
        let connections$5 = Belt_Array.concat(state.pipeline.connections, [conn$1]);
        let init$24 = state.pipeline;
        let pipeline_id$18 = init$24.id;
        let pipeline_name$18 = init$24.name;
        let pipeline_description$18 = init$24.description;
        let pipeline_nodes$12 = init$24.nodes;
        let pipeline_selectedNode$16 = init$24.selectedNode;
        let pipeline_selectedConnection$17 = init$24.selectedConnection;
        let pipeline_zoom$15 = init$24.zoom;
        let pipeline_panX$17 = init$24.panX;
        let pipeline_panY$17 = init$24.panY;
        let pipeline$19 = {
          id: pipeline_id$18,
          name: pipeline_name$18,
          description: pipeline_description$18,
          nodes: pipeline_nodes$12,
          connections: connections$5,
          selectedNode: pipeline_selectedNode$16,
          selectedConnection: pipeline_selectedConnection$17,
          zoom: pipeline_zoom$15,
          panX: pipeline_panX$17,
          panY: pipeline_panY$17
        };
        return {
          pipeline: pipeline$19,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: undefined,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "SelectConnection" :
        let init$25 = state.pipeline;
        let pipeline_id$19 = init$25.id;
        let pipeline_name$19 = init$25.name;
        let pipeline_description$19 = init$25.description;
        let pipeline_nodes$13 = init$25.nodes;
        let pipeline_connections$13 = init$25.connections;
        let pipeline_selectedNode$17 = init$25.selectedNode;
        let pipeline_selectedConnection$18 = msg._0;
        let pipeline_zoom$16 = init$25.zoom;
        let pipeline_panX$18 = init$25.panX;
        let pipeline_panY$18 = init$25.panY;
        let pipeline$20 = {
          id: pipeline_id$19,
          name: pipeline_name$19,
          description: pipeline_description$19,
          nodes: pipeline_nodes$13,
          connections: pipeline_connections$13,
          selectedNode: pipeline_selectedNode$17,
          selectedConnection: pipeline_selectedConnection$18,
          zoom: pipeline_zoom$16,
          panX: pipeline_panX$18,
          panY: pipeline_panY$18
        };
        return {
          pipeline: pipeline$20,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: state.isDirty
        };
      case "DuplicateNode" :
        let nodeId$5 = msg._0;
        let original = Belt_Array.getBy(state.pipeline.nodes, n => n.id === nodeId$5);
        if (original === undefined) {
          return state;
        }
        let newNode_id = PipelineModel.generateId();
        let newNode_kind = original.kind;
        let newNode_x = original.x + 40.0;
        let newNode_y = original.y + 40.0;
        let newNode_width = original.width;
        let newNode_height = original.height;
        let newNode_label = original.label + " (copy)";
        let newNode_status = original.status;
        let newNode_validationErrors = original.validationErrors;
        let newNode = {
          id: newNode_id,
          kind: newNode_kind,
          x: newNode_x,
          y: newNode_y,
          width: newNode_width,
          height: newNode_height,
          label: newNode_label,
          status: newNode_status,
          validationErrors: newNode_validationErrors
        };
        let nodes$6 = Belt_Array.concat(state.pipeline.nodes, [newNode]);
        let init$26 = state.pipeline;
        let pipeline_id$20 = init$26.id;
        let pipeline_name$20 = init$26.name;
        let pipeline_description$20 = init$26.description;
        let pipeline_connections$14 = init$26.connections;
        let pipeline_selectedNode$18 = init$26.selectedNode;
        let pipeline_selectedConnection$19 = init$26.selectedConnection;
        let pipeline_zoom$17 = init$26.zoom;
        let pipeline_panX$19 = init$26.panX;
        let pipeline_panY$19 = init$26.panY;
        let pipeline$21 = {
          id: pipeline_id$20,
          name: pipeline_name$20,
          description: pipeline_description$20,
          nodes: nodes$6,
          connections: pipeline_connections$14,
          selectedNode: pipeline_selectedNode$18,
          selectedConnection: pipeline_selectedConnection$19,
          zoom: pipeline_zoom$17,
          panX: pipeline_panX$19,
          panY: pipeline_panY$19
        };
        return {
          pipeline: pipeline$21,
          panels: state.panels,
          validation: state.validation,
          outputFormat: state.outputFormat,
          generatedOutput: state.generatedOutput,
          isDragging: state.isDragging,
          isConnecting: state.isConnecting,
          templates: state.templates,
          recentPipelines: state.recentPipelines,
          isDirty: true
        };
      case "LoadPipeline" :
        console.log("Loading pipeline...");
        return state;
      case "PipelineLoaded" :
        return msg._0;
      default:
        return state;
    }
  }
}

let gridSize = 20.0;

export {
  gridSize,
  snapToGrid,
  genId,
  hasCycle,
  validatePipeline,
  generateOutput,
  update,
}
/* No side effect */
