// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as PipelineCanvas from "./PipelineCanvas.res.js";
import * as PipelineOutput from "./PipelineOutput.res.js";
import * as PipelinePalette from "./PipelinePalette.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function PipelineDesigner$Toolbar(props) {
  let dispatch = props.dispatch;
  let pipelineName = props.pipelineName;
  let match = React.useState(() => false);
  let setIsEditing = match[1];
  let match$1 = React.useState(() => pipelineName);
  let setEditValue = match$1[1];
  let editValue = match$1[0];
  let commitName = () => {
    if (editValue !== "") {
      dispatch({
        TAG: "SetPipelineName",
        _0: editValue
      });
    } else {
      setEditValue(param => pipelineName);
    }
    setIsEditing(param => false);
  };
  return JsxRuntime.jsxs("header", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          match[0] ? JsxRuntime.jsx("input", {
              "aria-label": "Edit pipeline name",
              className: "text-lg font-semibold bg-gray-800 text-gray-100 border border-blue-500\n                         rounded px-2 py-0.5 focus:outline-none focus:ring-2 focus:ring-blue-400",
              autoFocus: true,
              type: "text",
              value: editValue,
              onKeyDown: e => {
                if (e.key === "Enter") {
                  return commitName();
                } else if (e.key === "Escape") {
                  setEditValue(param => pipelineName);
                  return setIsEditing(param => false);
                } else {
                  return;
                }
              },
              onBlur: param => commitName(),
              onChange: e => {
                let v = e.target.value;
                setEditValue(param => v);
              }
            }) : JsxRuntime.jsx("button", {
              children: pipelineName,
              "aria-label": "Pipeline name: " + pipelineName + ". Click to edit.",
              className: "text-lg font-semibold text-gray-100 hover:text-blue-300\n                         truncate max-w-xs cursor-text\n                         focus:outline-none focus:ring-2 focus:ring-blue-500 rounded px-1",
              title: "Click to rename",
              onClick: param => {
                setEditValue(param => pipelineName);
                setIsEditing(param => true);
              }
            }),
          props.isDirty ? JsxRuntime.jsx("span", {
              children: "*",
              "aria-label": "Unsaved changes",
              className: "text-xs text-yellow-400 flex-shrink-0",
              title: "Unsaved changes"
            }) : null
        ],
        className: "flex items-center gap-2 min-w-0"
      }),
      JsxRuntime.jsx("div", {
        className: "flex-1"
      }),
      JsxRuntime.jsxs("nav", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Save",
            "aria-label": "Save pipeline",
            className: "px-3 py-1.5 text-sm rounded-md bg-gray-700 text-gray-200\n                     hover:bg-gray-600 transition-colors\n                     focus:outline-none focus:ring-2 focus:ring-blue-500",
            title: "Save (Ctrl+S)",
            onClick: param => dispatch("SavePipeline")
          }),
          JsxRuntime.jsx("button", {
            children: "Load",
            "aria-label": "Load pipeline",
            className: "px-3 py-1.5 text-sm rounded-md bg-gray-700 text-gray-200\n                     hover:bg-gray-600 transition-colors\n                     focus:outline-none focus:ring-2 focus:ring-blue-500",
            title: "Load",
            onClick: param => dispatch({
              TAG: "LoadPipeline",
              _0: ""
            })
          }),
          JsxRuntime.jsx("button", {
            children: "Run",
            "aria-label": "Validate and run pipeline",
            className: "px-3 py-1.5 text-sm rounded-md bg-blue-600 text-white\n                     hover:bg-blue-500 transition-colors\n                     focus:outline-none focus:ring-2 focus:ring-blue-400",
            title: "Run (Ctrl+Enter)",
            onClick: param => dispatch("RunValidation")
          }),
          JsxRuntime.jsx("button", {
            children: "Export",
            "aria-label": "Export pipeline output",
            className: "px-3 py-1.5 text-sm rounded-md bg-green-700 text-white\n                     hover:bg-green-600 transition-colors\n                     focus:outline-none focus:ring-2 focus:ring-green-400",
            title: "Export",
            onClick: param => dispatch("RegeneratePreview")
          })
        ],
        "aria-label": "Pipeline actions",
        className: "flex items-center gap-2"
      })
    ],
    "aria-label": "Pipeline designer toolbar",
    className: "flex items-center gap-3 px-4 py-2 bg-gray-900 border-b border-gray-700",
    role: "toolbar"
  });
}

let Toolbar = {
  make: PipelineDesigner$Toolbar
};

function PipelineDesigner$StatusBar(props) {
  let dispatch = props.dispatch;
  let state = props.state;
  let nodeCount = state.pipeline.nodes.length;
  let connCount = state.pipeline.connections.length;
  let zoomPct = String(state.pipeline.zoom * 100.0 | 0);
  let v = state.validation;
  let validationStatus;
  if (v !== undefined) {
    if (v.isValid) {
      validationStatus = [
        "Valid",
        "text-green-400"
      ];
    } else {
      let errCount = v.errors.length;
      validationStatus = [
        String(errCount) + " error" + (
          errCount === 1 ? "" : "s"
        ),
        "text-red-400"
      ];
    }
  } else {
    validationStatus = [
      "--",
      "text-gray-500"
    ];
  }
  return JsxRuntime.jsxs("footer", {
    children: [
      JsxRuntime.jsx("span", {
        children: String(nodeCount) + " node" + (
          nodeCount === 1 ? "" : "s"
        ),
        "aria-label": "Nodes: " + String(nodeCount)
      }),
      JsxRuntime.jsx("span", {
        children: "|",
        className: "text-gray-600"
      }),
      JsxRuntime.jsx("span", {
        children: String(connCount) + " connection" + (
          connCount === 1 ? "" : "s"
        ),
        "aria-label": "Connections: " + String(connCount)
      }),
      JsxRuntime.jsx("span", {
        children: "|",
        className: "text-gray-600"
      }),
      JsxRuntime.jsx("span", {
        children: validationStatus[0],
        "aria-label": "Validation: " + validationStatus[0],
        className: validationStatus[1]
      }),
      JsxRuntime.jsx("div", {
        className: "flex-1"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "-",
            "aria-label": "Zoom out",
            className: "px-1.5 py-0.5 rounded hover:bg-gray-700 transition-colors\n                     focus:outline-none focus:ring-1 focus:ring-blue-500",
            title: "Zoom out",
            onClick: param => dispatch("ZoomOut")
          }),
          JsxRuntime.jsx("span", {
            children: zoomPct + "%",
            "aria-label": "Zoom: " + zoomPct + "%",
            className: "min-w-[3rem] text-center"
          }),
          JsxRuntime.jsx("button", {
            children: "+",
            "aria-label": "Zoom in",
            className: "px-1.5 py-0.5 rounded hover:bg-gray-700 transition-colors\n                     focus:outline-none focus:ring-1 focus:ring-blue-500",
            title: "Zoom in",
            onClick: param => dispatch("ZoomIn")
          }),
          JsxRuntime.jsx("button", {
            children: "1:1",
            "aria-label": "Reset zoom to 100%",
            className: "px-1.5 py-0.5 rounded hover:bg-gray-700 text-gray-500\n                     hover:text-gray-300 transition-colors ml-1\n                     focus:outline-none focus:ring-1 focus:ring-blue-500",
            title: "Reset zoom",
            onClick: param => dispatch("ResetZoom")
          })
        ],
        "aria-label": "Zoom controls",
        className: "flex items-center gap-1",
        role: "group"
      }),
      JsxRuntime.jsx("span", {
        children: "Ctrl+S Save  |  Ctrl+Enter Run  |  Ctrl+Z Undo",
        className: "text-gray-600 hidden sm:inline"
      })
    ],
    "aria-label": "Pipeline status",
    className: "flex items-center gap-4 px-4 py-1.5 bg-gray-900 border-t border-gray-700\n                 text-xs text-gray-400",
    role: "status"
  });
}

let StatusBar = {
  make: PipelineDesigner$StatusBar
};

function PipelineDesigner(props) {
  let dispatch = props.dispatch;
  let state = props.state;
  React.useEffect(() => {
    ((document.addEventListener("keydown", _handler)));
    return () => {
      ((document.removeEventListener("keydown", _handler)));
    };
  }, []);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx(PipelineDesigner$Toolbar, {
        pipelineName: state.pipeline.name,
        isDirty: state.isDirty,
        dispatch: dispatch
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx(PipelinePalette.make, {
            state: state,
            dispatch: dispatch
          }),
          JsxRuntime.jsx(PipelineCanvas.make, {
            pipeline: state.pipeline,
            dispatch: dispatch
          }),
          JsxRuntime.jsx(PipelineOutput.make, {
            state: state,
            dispatch: dispatch
          })
        ],
        className: "flex flex-1 overflow-hidden"
      }),
      JsxRuntime.jsx(PipelineDesigner$StatusBar, {
        state: state,
        dispatch: dispatch
      })
    ],
    "aria-label": "Assembly Pipeline Designer",
    className: "flex flex-col h-full w-full bg-gray-950 text-gray-100",
    role: "region"
  });
}

let make = PipelineDesigner;

export {
  Toolbar,
  StatusBar,
  make,
}
/* react Not a pure module */
