// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as JsxRuntime from "react/jsx-runtime";

let init_metrics = {
  security: 0,
  performance: 0,
  reliability: 0,
  compliance: 0
};

let init_vulnerabilities = [];

let init_checks = [];

let init_exposedPorts = [];

let init = {
  metrics: init_metrics,
  grade: "F",
  vulnerabilities: init_vulnerabilities,
  checks: init_checks,
  exposedPorts: init_exposedPorts,
  selectedVulnerability: undefined,
  showDetails: true,
  filterSeverity: undefined
};

function calculateGrade(metrics) {
  let avg = (((metrics.security + metrics.performance | 0) + metrics.reliability | 0) + metrics.compliance | 0) / 4 | 0;
  if (avg >= 97) {
    return "APlus";
  } else if (avg >= 93) {
    return "A";
  } else if (avg >= 90) {
    return "AMinus";
  } else if (avg >= 87) {
    return "BPlus";
  } else if (avg >= 83) {
    return "B";
  } else if (avg >= 80) {
    return "BMinus";
  } else if (avg >= 77) {
    return "CPlus";
  } else if (avg >= 73) {
    return "C";
  } else if (avg >= 70) {
    return "CMinus";
  } else if (avg >= 60) {
    return "D";
  } else {
    return "F";
  }
}

function update(msg, state) {
  if (typeof msg !== "object") {
    if (msg === "ToggleDetails") {
      return {
        metrics: state.metrics,
        grade: state.grade,
        vulnerabilities: state.vulnerabilities,
        checks: state.checks,
        exposedPorts: state.exposedPorts,
        selectedVulnerability: state.selectedVulnerability,
        showDetails: !state.showDetails,
        filterSeverity: state.filterSeverity
      };
    } else {
      return state;
    }
  }
  switch (msg.TAG) {
    case "UpdateMetrics" :
      let newMetrics = msg._0;
      let grade = calculateGrade(newMetrics);
      return {
        metrics: newMetrics,
        grade: grade,
        vulnerabilities: state.vulnerabilities,
        checks: state.checks,
        exposedPorts: state.exposedPorts,
        selectedVulnerability: state.selectedVulnerability,
        showDetails: state.showDetails,
        filterSeverity: state.filterSeverity
      };
    case "SelectVulnerability" :
      return {
        metrics: state.metrics,
        grade: state.grade,
        vulnerabilities: state.vulnerabilities,
        checks: state.checks,
        exposedPorts: state.exposedPorts,
        selectedVulnerability: msg._0,
        showDetails: state.showDetails,
        filterSeverity: state.filterSeverity
      };
    case "FilterBySeverity" :
      return {
        metrics: state.metrics,
        grade: state.grade,
        vulnerabilities: state.vulnerabilities,
        checks: state.checks,
        exposedPorts: state.exposedPorts,
        selectedVulnerability: state.selectedVulnerability,
        showDetails: state.showDetails,
        filterSeverity: msg._0
      };
    case "ApplyFix" :
      let vulnId = msg._0;
      let updatedVulns = Belt_Array.keep(state.vulnerabilities, v => v.id !== vulnId);
      let init = state.metrics;
      let newMetrics_security = Primitive_int.min(100, state.metrics.security + 5 | 0);
      let newMetrics_performance = init.performance;
      let newMetrics_reliability = init.reliability;
      let newMetrics_compliance = init.compliance;
      let newMetrics$1 = {
        security: newMetrics_security,
        performance: newMetrics_performance,
        reliability: newMetrics_reliability,
        compliance: newMetrics_compliance
      };
      let grade$1 = calculateGrade(newMetrics$1);
      return {
        metrics: newMetrics$1,
        grade: grade$1,
        vulnerabilities: updatedVulns,
        checks: state.checks,
        exposedPorts: state.exposedPorts,
        selectedVulnerability: state.selectedVulnerability,
        showDetails: state.showDetails,
        filterSeverity: state.filterSeverity
      };
  }
}

function severityColor(severity) {
  switch (severity) {
    case "Critical" :
      return "#d32f2f";
    case "High" :
      return "#f57c00";
    case "Medium" :
      return "#fbc02d";
    case "Low" :
      return "#388e3c";
    case "Info" :
      return "#1976d2";
  }
}

function severityLabel(severity) {
  switch (severity) {
    case "Critical" :
      return "Critical";
    case "High" :
      return "High";
    case "Medium" :
      return "Medium";
    case "Low" :
      return "Low";
    case "Info" :
      return "Info";
  }
}

function checkResultIcon(result) {
  switch (result) {
    case "Pass" :
      return "✅";
    case "Fail" :
      return "❌";
    case "Warning" :
      return "⚠️";
    case "Unknown" :
      return "❓";
  }
}

function checkResultColor(result) {
  switch (result) {
    case "Pass" :
      return "#4caf50";
    case "Fail" :
      return "#f44336";
    case "Warning" :
      return "#ff9800";
    case "Unknown" :
      return "#9e9e9e";
  }
}

function gradeDisplay(grade) {
  switch (grade) {
    case "APlus" :
      return "A+";
    case "A" :
      return "A";
    case "AMinus" :
      return "A-";
    case "BPlus" :
      return "B+";
    case "B" :
      return "B";
    case "BMinus" :
      return "B-";
    case "CPlus" :
      return "C+";
    case "C" :
      return "C";
    case "CMinus" :
      return "C-";
    case "D" :
      return "D";
    case "F" :
      return "F";
  }
}

function gradeColor(grade) {
  switch (grade) {
    case "APlus" :
    case "A" :
      return "#4caf50";
    case "AMinus" :
    case "BPlus" :
      return "#8bc34a";
    case "B" :
    case "BMinus" :
      return "#ffc107";
    case "CPlus" :
    case "C" :
      return "#ff9800";
    case "CMinus" :
    case "D" :
      return "#ff5722";
    case "F" :
      return "#f44336";
  }
}

function viewMetricBar(label, value, color) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: label,
            style: {
              color: "#e0e6ed",
              fontSize: "14px",
              fontWeight: "600"
            }
          }),
          JsxRuntime.jsx("span", {
            children: String(value) + "%",
            style: {
              color: color,
              fontSize: "14px",
              fontWeight: "700"
            }
          })
        ],
        style: {
          display: "flex",
          justifyContent: "space-between",
          marginBottom: "8px"
        }
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx("div", {
          style: {
            background: color,
            height: "100%",
            transition: "width 0.3s ease",
            width: String(value) + "%"
          }
        }),
        style: {
          background: "#2a3142",
          borderRadius: "4px",
          height: "8px",
          overflow: "hidden",
          width: "100%"
        }
      })
    ],
    style: {
      marginBottom: "16px"
    }
  });
}

function viewVulnerability(vuln, dispatch) {
  let cveId = vuln.cveId;
  let desc = vuln.fixDescription;
  return JsxRuntime.jsx("div", {
    children: JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsx("div", {
          children: severityLabel(vuln.severity),
          style: {
            background: severityColor(vuln.severity),
            borderRadius: "6px",
            color: "white",
            fontSize: "11px",
            fontWeight: "700",
            minWidth: "80px",
            padding: "4px 12px",
            textAlign: "center",
            textTransform: "uppercase"
          }
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: vuln.title,
              style: {
                color: "#e0e6ed",
                fontSize: "15px",
                fontWeight: "700",
                marginBottom: "6px"
              }
            }),
            JsxRuntime.jsx("div", {
              children: vuln.description,
              style: {
                color: "#8892a6",
                fontSize: "13px",
                lineHeight: "1.5",
                marginBottom: "8px"
              }
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("span", {
                  children: [
                    "Component: ",
                    JsxRuntime.jsx("strong", {
                      children: vuln.affectedComponent,
                      style: {
                        color: "#4a9eff"
                      }
                    })
                  ],
                  style: {
                    color: "#6b7a90",
                    fontSize: "12px"
                  }
                }),
                cveId !== undefined ? JsxRuntime.jsxs("span", {
                    children: [
                      "CVE: ",
                      JsxRuntime.jsx("strong", {
                        children: cveId,
                        style: {
                          color: "#ff9800"
                        }
                      })
                    ],
                    style: {
                      color: "#6b7a90",
                      fontSize: "12px"
                    }
                  }) : null,
                vuln.fixAvailable ? JsxRuntime.jsx("button", {
                    children: "🔧 Auto-Fix",
                    style: {
                      background: "linear-gradient(135deg, #4caf50, #66bb6a)",
                      border: "none",
                      borderRadius: "6px",
                      color: "white",
                      cursor: "pointer",
                      fontSize: "11px",
                      fontWeight: "600",
                      padding: "6px 12px"
                    },
                    onClick: e => {
                      e.stopPropagation();
                      dispatch({
                        TAG: "ApplyFix",
                        _0: vuln.id
                      });
                    }
                  }) : null
              ],
              style: {
                alignItems: "center",
                display: "flex",
                gap: "16px"
              }
            }),
            desc !== undefined ? JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("strong", {
                    children: "Fix: ",
                    style: {
                      color: "#4caf50"
                    }
                  }),
                  desc
                ],
                style: {
                  background: "rgba(76, 175, 80, 0.1)",
                  border: "1px solid #4caf50",
                  borderRadius: "6px",
                  color: "#b0b8c4",
                  fontSize: "12px",
                  marginTop: "12px",
                  padding: "12px"
                }
              }) : null
          ],
          style: {
            flex: "1"
          }
        })
      ],
      style: {
        alignItems: "flex-start",
        display: "flex",
        gap: "12px"
      }
    }),
    style: {
      background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
      border: "2px solid #2a3142",
      borderRadius: "12px",
      cursor: "pointer",
      marginBottom: "12px",
      padding: "16px",
      transition: "all 0.2s"
    },
    onClick: param => dispatch({
      TAG: "SelectVulnerability",
      _0: vuln.id
    })
  }, vuln.id);
}

function viewSecurityCheck(check) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: checkResultIcon(check.result),
            style: {
              fontSize: "24px"
            }
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: check.name,
                style: {
                  color: "#e0e6ed",
                  fontSize: "14px",
                  fontWeight: "600"
                }
              }),
              JsxRuntime.jsx("div", {
                children: check.description,
                style: {
                  color: "#8892a6",
                  fontSize: "12px",
                  marginTop: "2px"
                }
              })
            ]
          })
        ],
        style: {
          alignItems: "center",
          display: "flex",
          gap: "12px"
        }
      }),
      JsxRuntime.jsx("div", {
        children: check.details,
        style: {
          background: checkResultColor(check.result),
          borderRadius: "6px",
          color: "white",
          fontSize: "11px",
          fontWeight: "700",
          minWidth: "100px",
          padding: "6px 12px",
          textAlign: "center"
        }
      })
    ],
    style: {
      alignItems: "center",
      background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
      border: "1px solid #2a3142",
      borderRadius: "8px",
      display: "flex",
      justifyContent: "space-between",
      marginBottom: "8px",
      padding: "16px"
    }
  }, check.name);
}

function viewExposedPort(port) {
  let match = port.risk;
  let tmp;
  switch (match) {
    case "Critical" :
      tmp = "#d32f2f";
      break;
    case "High" :
      tmp = "#f57c00";
      break;
    case "Low" :
      tmp = "#388e3c";
      break;
    case "Medium" :
      tmp = "#fbc02d";
      break;
    default:
      tmp = "#9e9e9e";
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: String(port.port),
            style: {
              color: "#4a9eff",
              fontSize: "16px",
              fontWeight: "700"
            }
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: port.service,
                style: {
                  color: "#e0e6ed",
                  fontSize: "13px",
                  fontWeight: "600"
                }
              }),
              JsxRuntime.jsx("div", {
                children: port.protocol,
                style: {
                  color: "#8892a6",
                  fontSize: "11px"
                }
              })
            ]
          })
        ],
        style: {
          alignItems: "center",
          display: "flex",
          gap: "12px"
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          port.publiclyAccessible ? JsxRuntime.jsx("span", {
              children: "PUBLIC",
              style: {
                background: "rgba(244, 67, 54, 0.2)",
                border: "1px solid #f44336",
                borderRadius: "4px",
                color: "#f44336",
                fontSize: "10px",
                fontWeight: "600",
                padding: "4px 8px"
              }
            }) : null,
          JsxRuntime.jsx("div", {
            children: port.risk,
            style: {
              background: tmp,
              borderRadius: "4px",
              color: "white",
              fontSize: "10px",
              fontWeight: "700",
              padding: "4px 8px"
            }
          })
        ],
        style: {
          alignItems: "center",
          display: "flex",
          gap: "8px"
        }
      })
    ],
    style: {
      alignItems: "center",
      background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
      border: "1px solid #2a3142",
      borderRadius: "8px",
      display: "flex",
      justifyContent: "space-between",
      marginBottom: "6px",
      padding: "12px"
    }
  }, String(port.port));
}

function SecurityInspector(props) {
  let onStateChange = props.onStateChange;
  let initialState = props.initialState;
  let match = React.useState(() => {
    if (initialState !== undefined) {
      return initialState;
    } else {
      return init;
    }
  });
  let setState = match[1];
  let state = match[0];
  let dispatch = msg => {
    let newState = update(msg, state);
    setState(param => newState);
    if (onStateChange !== undefined) {
      return onStateChange(newState);
    }
  };
  let isEmpty = state.checks.length === 0 && state.vulnerabilities.length === 0 && state.metrics.security === 0;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h1", {
            children: "🛡️ Security Inspector",
            style: {
              background: "linear-gradient(135deg, #f44336, #ff9800)",
              fontSize: "32px",
              fontWeight: "700",
              marginBottom: "8px"
            }
          }),
          JsxRuntime.jsx("p", {
            children: "Real-time attack surface analysis and vulnerability assessment",
            style: {
              color: "#8892a6",
              fontSize: "16px"
            }
          })
        ],
        style: {
          marginBottom: "32px"
        }
      }),
      isEmpty ? JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("div", {
              children: "🔍",
              style: {
                fontSize: "48px",
                marginBottom: "16px"
              }
            }),
            JsxRuntime.jsx("h2", {
              children: "No security scan results yet",
              style: {
                color: "#e0e6ed",
                fontSize: "20px",
                fontWeight: "700",
                marginBottom: "12px"
              }
            }),
            JsxRuntime.jsx("p", {
              children: "Add components to your stack and run a security scan to see real-time vulnerability assessment, compliance checks, and improvement suggestions.",
              style: {
                color: "#8892a6",
                fontSize: "14px",
                lineHeight: "1.6",
                marginBottom: "24px"
              }
            }),
            JsxRuntime.jsx("button", {
              children: "Run Security Scan",
              style: {
                background: "linear-gradient(135deg, #4a9eff, #7b6cff)",
                border: "none",
                borderRadius: "8px",
                color: "white",
                cursor: "pointer",
                fontSize: "16px",
                fontWeight: "600",
                padding: "12px 28px"
              },
              onClick: param => dispatch("RunSecurityScan")
            })
          ],
          style: {
            background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
            border: "2px dashed #2a3f5f",
            borderRadius: "16px",
            padding: "60px 40px",
            textAlign: "center"
          }
        }) : null,
      isEmpty ? null : JsxRuntime.jsxs(JsxRuntime.Fragment, {
          children: [
            JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                    children: gradeDisplay(state.grade),
                    style: {
                      color: gradeColor(state.grade),
                      fontSize: "72px",
                      fontWeight: "900",
                      marginBottom: "8px"
                    }
                  }),
                  JsxRuntime.jsx("div", {
                    children: "Security Grade",
                    style: {
                      color: "#8892a6",
                      fontSize: "16px"
                    }
                  })
                ],
                style: {
                  textAlign: "center"
                }
              }),
              style: {
                alignItems: "center",
                background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
                border: "3px solid " + gradeColor(state.grade),
                borderRadius: "16px",
                display: "flex",
                justifyContent: "center",
                marginBottom: "32px",
                padding: "40px"
              }
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h3", {
                  children: "📊 Security Metrics",
                  style: {
                    color: "#e0e6ed",
                    fontSize: "20px",
                    fontWeight: "700",
                    marginBottom: "24px"
                  }
                }),
                viewMetricBar("Security", state.metrics.security, "#f44336"),
                viewMetricBar("Performance", state.metrics.performance, "#4caf50"),
                viewMetricBar("Reliability", state.metrics.reliability, "#2196f3"),
                viewMetricBar("Compliance", state.metrics.compliance, "#9c27b0")
              ],
              style: {
                background: "linear-gradient(135deg, #1e2431 0%, #252d3d 100%)",
                border: "2px solid #2a3142",
                borderRadius: "16px",
                marginBottom: "32px",
                padding: "24px"
              }
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h3", {
                  children: "✓ Quick Security Checks",
                  style: {
                    color: "#e0e6ed",
                    fontSize: "20px",
                    fontWeight: "700",
                    marginBottom: "16px"
                  }
                }),
                Belt_Array.map(state.checks, viewSecurityCheck)
              ],
              style: {
                marginBottom: "32px"
              }
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsxs("h3", {
                      children: [
                        "🚨 Vulnerabilities (",
                        String(state.vulnerabilities.length),
                        ")"
                      ],
                      style: {
                        color: "#e0e6ed",
                        fontSize: "20px",
                        fontWeight: "700"
                      }
                    }),
                    JsxRuntime.jsx("button", {
                      children: "🔍 Run Full Scan",
                      style: {
                        background: "linear-gradient(135deg, #4a9eff, #7b6cff)",
                        border: "none",
                        borderRadius: "8px",
                        color: "white",
                        cursor: "pointer",
                        fontSize: "14px",
                        fontWeight: "600",
                        padding: "10px 20px"
                      },
                      onClick: param => dispatch("RunSecurityScan")
                    })
                  ],
                  style: {
                    alignItems: "center",
                    display: "flex",
                    justifyContent: "space-between",
                    marginBottom: "16px"
                  }
                }),
                state.vulnerabilities.length !== 0 ? Belt_Array.map(state.vulnerabilities, vuln => viewVulnerability(vuln, dispatch)) : JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                        children: "✅",
                        style: {
                          fontSize: "48px",
                          marginBottom: "16px"
                        }
                      }),
                      JsxRuntime.jsx("div", {
                        children: "No Vulnerabilities Detected",
                        style: {
                          color: "#4caf50",
                          fontSize: "18px",
                          fontWeight: "700",
                          marginBottom: "8px"
                        }
                      }),
                      JsxRuntime.jsx("div", {
                        children: "Your stack meets all security requirements",
                        style: {
                          color: "#8892a6",
                          fontSize: "14px"
                        }
                      })
                    ],
                    style: {
                      background: "rgba(76, 175, 80, 0.1)",
                      border: "2px solid #4caf50",
                      borderRadius: "12px",
                      padding: "40px",
                      textAlign: "center"
                    }
                  })
              ],
              style: {
                marginBottom: "32px"
              }
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h3", {
                  children: "🔌 Exposed Ports Analysis",
                  style: {
                    color: "#e0e6ed",
                    fontSize: "20px",
                    fontWeight: "700",
                    marginBottom: "16px"
                  }
                }),
                Belt_Array.map(state.exposedPorts, viewExposedPort)
              ]
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h4", {
                  children: "⚠️ Security Intelligence",
                  style: {
                    color: "#ff9800",
                    fontSize: "16px",
                    fontWeight: "700",
                    marginBottom: "12px"
                  }
                }),
                JsxRuntime.jsx("p", {
                  children: "Security analysis powered by miniKanren reasoning engine. All findings logged to VeriSimDB for compliance audit. Auto-fix applies verified security patches with formal verification proofs.",
                  style: {
                    color: "#b0b8c4",
                    fontSize: "13px",
                    lineHeight: "1.8"
                  }
                })
              ],
              style: {
                background: "rgba(255, 152, 0, 0.1)",
                border: "2px solid #ff9800",
                borderRadius: "12px",
                marginTop: "32px",
                padding: "20px"
              }
            })
          ]
        })
    ],
    className: "security-inspector",
    style: {
      background: "#0a0e1a",
      minHeight: "100vh",
      padding: "32px"
    }
  });
}

let make = SecurityInspector;

export {
  init,
  calculateGrade,
  update,
  severityColor,
  severityLabel,
  checkResultIcon,
  checkResultColor,
  gradeDisplay,
  gradeColor,
  viewMetricBar,
  viewVulnerability,
  viewSecurityCheck,
  viewExposedPort,
  make,
}
/* react Not a pure module */
