// SPDX-License-Identifier: PMPL-1.0-or-later
// Sx.res - ReactDOM.Style.make compatibility shim for @rescript/react 0.14
//
// In @rescript/react 0.14, ReactDOMStyle.make was removed. This module
// provides a drop-in replacement using @obj external.

@obj
external make: (
  ~alignItems: string=?,
  ~animation: string=?,
  ~background: string=?,
  ~backgroundColor: string=?,
  ~border: string=?,
  ~borderBottom: string=?,
  ~borderLeft: string=?,
  ~borderRadius: string=?,
  ~borderRight: string=?,
  ~borderTop: string=?,
  ~bottom: string=?,
  ~boxShadow: string=?,
  ~color: string=?,
  ~cursor: string=?,
  ~display: string=?,
  ~flex: string=?,
  ~flexDirection: string=?,
  ~flexWrap: string=?,
  ~fontFamily: string=?,
  ~fontSize: string=?,
  ~fontWeight: string=?,
  ~gap: string=?,
  ~gridTemplateColumns: string=?,
  ~height: string=?,
  ~justifyContent: string=?,
  ~left: string=?,
  ~letterSpacing: string=?,
  ~lineHeight: string=?,
  ~listStyle: string=?,
  ~margin: string=?,
  ~marginBottom: string=?,
  ~marginLeft: string=?,
  ~marginRight: string=?,
  ~marginTop: string=?,
  ~maxHeight: string=?,
  ~maxWidth: string=?,
  ~minHeight: string=?,
  ~minWidth: string=?,
  ~opacity: string=?,
  ~outline: string=?,
  ~outlineOffset: string=?,
  ~overflow: string=?,
  ~overflowY: string=?,
  ~padding: string=?,
  ~paddingBottom: string=?,
  ~paddingLeft: string=?,
  ~paddingRight: string=?,
  ~paddingTop: string=?,
  ~pointerEvents: string=?,
  ~position: string=?,
  ~right: string=?,
  ~textAlign: string=?,
  ~textTransform: string=?,
  ~top: string=?,
  ~transform: string=?,
  ~transition: string=?,
  ~whiteSpace: string=?,
  ~width: string=?,
  ~zIndex: string=?,
  unit,
) => ReactDOM.style = ""
