// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Model from "./Model.res.js";
import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function snapToGrid(pos) {
  return {
    x: Math.round(pos.x / 20.0) * 20.0,
    y: Math.round(pos.y / 20.0) * 20.0
  };
}

let initialCanvasState_undoStack = [];

let initialCanvasState = {
  undoStack: initialCanvasState_undoStack,
  connectionDrawing: undefined,
  deleteConfirm: undefined
};

function toCiscoComponent(comp) {
  let match = comp.componentType;
  let shape;
  switch (match) {
    case "CerroTorre" :
    case "Svalinn" :
      shape = "Gateway";
      break;
    case "Volume" :
      shape = "Oval";
      break;
    default:
      shape = "Box";
  }
  return {
    id: comp.id,
    shape: shape,
    label: Model.componentTypeToString(comp.componentType),
    position: comp.position,
    size: [
      150.0,
      100.0
    ],
    ports: [],
    config: comp.config,
    children: []
  };
}

function renderShape(comp, isSelected, isDark) {
  let match = comp.size;
  let height = match[1];
  let width = match[0];
  let x = comp.position.x;
  let y = comp.position.y;
  let borderColor = isDark ? "#CCCCCC" : "#333333";
  let fillColor = isDark ? "#1A1A1A" : "#F5F5F5";
  let selectedBorder = isDark ? "#66B2FF" : "#0052CC";
  let strokeWidth = isSelected ? "3" : "2";
  let stroke = isSelected ? selectedBorder : borderColor;
  let match$1 = comp.shape;
  switch (match$1) {
    case "Box" :
      return JsxRuntime.jsx("rect", {
        "aria-label": comp.label + " container (box shape)",
        role: "graphics-symbol",
        height: String(height),
        width: String(width),
        fill: fillColor,
        rx: "8",
        stroke: stroke,
        strokeWidth: strokeWidth,
        x: String(x),
        y: String(y)
      });
    case "Oval" :
      return JsxRuntime.jsx("ellipse", {
        "aria-label": comp.label + " container (oval shape)",
        role: "graphics-symbol",
        cx: String(x + width / 2.0),
        cy: String(y + height / 2.0),
        fill: fillColor,
        rx: String(width / 2.0),
        ry: String(height / 2.0),
        stroke: stroke,
        strokeWidth: strokeWidth
      });
    case "Gateway" :
      return JsxRuntime.jsx("rect", {
        "aria-label": comp.label + " security gateway",
        role: "graphics-symbol",
        height: String(height),
        width: String(width),
        fill: fillColor,
        rx: "8",
        stroke: stroke,
        strokeDasharray: "10,5",
        strokeWidth: "4",
        x: String(x),
        y: String(y)
      });
    case "Nested" :
      return JsxRuntime.jsxs(JsxRuntime.Fragment, {
        children: [
          JsxRuntime.jsx("rect", {
            "aria-label": comp.label + " nested container group",
            role: "graphics-symbol",
            height: String(height),
            width: String(width),
            fill: fillColor,
            rx: "8",
            stroke: stroke,
            strokeWidth: strokeWidth,
            x: String(x),
            y: String(y)
          }),
          Belt_Array.mapWithIndex(comp.children, (idx, child) => {
            let childX = x + 20.0 + idx * 30.0;
            let childY = y + 40.0;
            return renderShape({
              id: child.id,
              shape: child.shape,
              label: child.label,
              position: {
                x: childX,
                y: childY
              },
              size: child.size,
              ports: child.ports,
              config: child.config,
              children: child.children
            }, false, isDark);
          })
        ]
      });
  }
}

function renderConnection(conn, components, isDark) {
  let fromComp = Belt_Array.getBy(components, c => c.id === conn.from);
  let toComp = Belt_Array.getBy(components, c => c.id === conn.to);
  if (fromComp === undefined) {
    return null;
  }
  if (toComp === undefined) {
    return null;
  }
  let x1 = fromComp.position.x + 75.0;
  let y1 = fromComp.position.y + 50.0;
  let x2 = toComp.position.x + 75.0;
  let y2 = toComp.position.y + 50.0;
  let midX = (x1 + x2) / 2.0;
  let path = `M ` + String(x1) + ` ` + String(y1) + ` Q ` + String(midX) + ` ` + String(y1) + ` ` + String(midX) + ` ` + String((y1 + y2) / 2.0) + ` T ` + String(x2) + ` ` + String(y2);
  return JsxRuntime.jsx("path", {
    "aria-label": `Connection from ` + conn.from + ` to ` + conn.to,
    role: "graphics-symbol",
    d: path,
    fill: "none",
    markerEnd: "url(#arrowhead)",
    stroke: isDark ? "#66B2FF" : "#0052CC",
    strokeWidth: "2"
  }, conn.id);
}

function renderConnectionPreview(fromId, mousePos, components, isDark) {
  let fromComp = Belt_Array.getBy(components, c => c.id === fromId);
  if (fromComp === undefined) {
    return null;
  }
  let x1 = fromComp.position.x + 75.0;
  let y1 = fromComp.position.y + 50.0;
  return JsxRuntime.jsx("line", {
    stroke: isDark ? "#66B2FF80" : "#0052CC80",
    strokeDasharray: "6,4",
    strokeWidth: "2",
    x1: String(x1),
    x2: String(mousePos.x),
    y1: String(y1),
    y2: String(mousePos.y)
  });
}

function renderPortIndicator(comp, isDark) {
  let match = comp.size;
  let cx = comp.position.x + match[0];
  let cy = comp.position.y + 50.0;
  return JsxRuntime.jsx("circle", {
    "aria-label": comp.label + " connection port",
    role: "graphics-symbol",
    style: {
      cursor: "crosshair"
    },
    cx: String(cx),
    cy: String(cy),
    fill: isDark ? "#66B2FF" : "#0052CC",
    r: "6",
    stroke: isDark ? "#FFFFFF" : "#000000",
    strokeWidth: "1"
  });
}

function renderDeleteConfirmation(compId, components, isDark, onConfirm, onCancel) {
  let comp = Belt_Array.getBy(components, c => c.id === compId);
  if (comp !== undefined) {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("h3", {
            children: "Delete Component?",
            style: {
              marginBottom: "1rem"
            }
          }),
          JsxRuntime.jsx("p", {
            children: "Remove \"" + Model.componentTypeToString(comp.componentType) + "\" and all its connections?",
            style: {
              marginBottom: "1.5rem"
            }
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("button", {
                children: "Cancel",
                "aria-label": "Cancel deletion",
                style: {
                  backgroundColor: isDark ? "#333333" : "#E0E0E0",
                  border: "none",
                  borderRadius: "4px",
                  color: isDark ? "#FFFFFF" : "#000000",
                  cursor: "pointer",
                  padding: "0.5rem 1.5rem"
                },
                onClick: param => onCancel()
              }),
              JsxRuntime.jsx("button", {
                children: "Delete",
                "aria-label": "Confirm deletion",
                style: {
                  backgroundColor: "#CC3333",
                  border: "none",
                  borderRadius: "4px",
                  color: "white",
                  cursor: "pointer",
                  fontWeight: "600",
                  padding: "0.5rem 1.5rem"
                },
                onClick: param => onConfirm()
              })
            ],
            style: {
              display: "flex",
              gap: "1rem",
              justifyContent: "flex-end"
            }
          })
        ],
        style: {
          backgroundColor: isDark ? "#1A1A1A" : "#FFFFFF",
          border: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
          borderRadius: "8px",
          color: isDark ? "#FFFFFF" : "#000000",
          maxWidth: "400px",
          padding: "2rem"
        }
      }),
      "aria-label": "Confirm component deletion",
      role: "alertdialog",
      style: {
        alignItems: "center",
        backgroundColor: "rgba(0,0,0,0.5)",
        display: "flex",
        height: "100%",
        justifyContent: "center",
        left: "0",
        position: "fixed",
        top: "0",
        width: "100%",
        zIndex: "1000"
      }
    });
  } else {
    return null;
  }
}

function renderConfigPanel(component, isDark, dispatch) {
  if (component !== undefined) {
    return JsxRuntime.jsxs("aside", {
      children: [
        JsxRuntime.jsx("h3", {
          children: Model.componentTypeToString(component.componentType),
          style: {
            fontSize: "1.2rem",
            marginBottom: "1rem"
          }
        }),
        JsxRuntime.jsxs("form", {
          children: [
            JsxRuntime.jsxs("fieldset", {
              children: [
                JsxRuntime.jsx("legend", {
                  children: "Shape",
                  style: {
                    fontWeight: "600",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsxs("label", {
                  children: [
                    JsxRuntime.jsx("input", {
                      defaultChecked: true,
                      name: "shape",
                      type: "radio",
                      value: "box"
                    }),
                    " Box"
                  ],
                  style: {
                    display: "block",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsxs("label", {
                  children: [
                    JsxRuntime.jsx("input", {
                      name: "shape",
                      type: "radio",
                      value: "oval"
                    }),
                    " Oval"
                  ],
                  style: {
                    display: "block",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsxs("label", {
                  children: [
                    JsxRuntime.jsx("input", {
                      name: "shape",
                      type: "radio",
                      value: "gateway"
                    }),
                    " Gateway"
                  ],
                  style: {
                    display: "block"
                  }
                })
              ],
              style: {
                border: "none",
                marginBottom: "1rem",
                padding: "0"
              }
            }),
            JsxRuntime.jsxs("fieldset", {
              children: [
                JsxRuntime.jsx("legend", {
                  children: "Ports",
                  style: {
                    fontWeight: "600",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsx("input", {
                  "aria-label": "Port mapping",
                  style: {
                    backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                    border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                    borderRadius: "4px",
                    color: isDark ? "#FFFFFF" : "#000000",
                    padding: "0.5rem",
                    width: "100%"
                  },
                  placeholder: "8080:80",
                  type: "text"
                })
              ],
              style: {
                border: "none",
                marginBottom: "1rem",
                padding: "0"
              }
            }),
            JsxRuntime.jsxs("fieldset", {
              children: [
                JsxRuntime.jsx("legend", {
                  children: "Resources",
                  style: {
                    fontWeight: "600",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsxs("label", {
                  children: [
                    "CPU (cores)",
                    JsxRuntime.jsx("input", {
                      "aria-label": "CPU cores",
                      defaultValue: "1.0",
                      style: {
                        backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                        border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                        borderRadius: "4px",
                        color: isDark ? "#FFFFFF" : "#000000",
                        marginTop: "0.25rem",
                        padding: "0.5rem",
                        width: "100%"
                      },
                      min: "0.1",
                      step: 0.1,
                      type: "number"
                    })
                  ],
                  style: {
                    display: "block",
                    marginBottom: "0.5rem"
                  }
                }),
                JsxRuntime.jsxs("label", {
                  children: [
                    "Memory (MB)",
                    JsxRuntime.jsx("input", {
                      "aria-label": "Memory in megabytes",
                      defaultValue: "512",
                      style: {
                        backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                        border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                        borderRadius: "4px",
                        color: isDark ? "#FFFFFF" : "#000000",
                        marginTop: "0.25rem",
                        padding: "0.5rem",
                        width: "100%"
                      },
                      min: "128",
                      step: 128.0,
                      type: "number"
                    })
                  ],
                  style: {
                    display: "block"
                  }
                })
              ],
              style: {
                border: "none",
                marginBottom: "1rem",
                padding: "0"
              }
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                  children: "Apply",
                  "aria-label": "Apply configuration changes",
                  style: {
                    backgroundColor: isDark ? "#66B2FF" : "#0052CC",
                    border: "none",
                    borderRadius: "6px",
                    color: "white",
                    cursor: "pointer",
                    flex: "1",
                    fontWeight: "600",
                    padding: "0.75rem"
                  },
                  type: "submit"
                }),
                JsxRuntime.jsx("button", {
                  children: "Cancel",
                  "aria-label": "Cancel configuration",
                  style: {
                    backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
                    border: isDark ? "1px solid #CCCCCC" : "1px solid #333333",
                    borderRadius: "6px",
                    color: isDark ? "#FFFFFF" : "#000000",
                    cursor: "pointer",
                    flex: "1",
                    fontWeight: "600",
                    padding: "0.75rem"
                  },
                  type: "button",
                  onClick: param => dispatch({
                    TAG: "SelectComponent",
                    _0: undefined
                  })
                })
              ],
              style: {
                display: "flex",
                gap: "0.5rem",
                marginTop: "1rem"
              }
            })
          ],
          onSubmit: e => {
            e.preventDefault();
          }
        })
      ],
      "aria-label": "Configuration for " + Model.componentTypeToString(component.componentType),
      role: "complementary",
      style: {
        backgroundColor: isDark ? "#000000" : "#FFFFFF",
        borderLeft: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
        color: isDark ? "#FFFFFF" : "#000000",
        padding: "1.5rem",
        width: "300px"
      }
    });
  } else {
    return JsxRuntime.jsxs("aside", {
      children: [
        JsxRuntime.jsx("h3", {
          children: "Configuration",
          style: {
            fontSize: "1.2rem",
            marginBottom: "1rem"
          }
        }),
        JsxRuntime.jsx("p", {
          children: "Click a component to configure it",
          style: {
            opacity: "0.7"
          }
        }),
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("h4", {
              children: "Keyboard Shortcuts",
              style: {
                marginBottom: "0.5rem"
              }
            }),
            JsxRuntime.jsx("p", {
              children: "Ctrl+Z: Undo last action"
            }),
            JsxRuntime.jsx("p", {
              children: "Delete: Remove selected component"
            }),
            JsxRuntime.jsx("p", {
              children: "Shift+Click port: Draw connection"
            })
          ],
          style: {
            fontSize: "0.85rem",
            marginTop: "2rem",
            opacity: "0.5"
          }
        })
      ],
      "aria-label": "Configuration panel",
      role: "complementary",
      style: {
        backgroundColor: isDark ? "#000000" : "#FFFFFF",
        borderLeft: isDark ? "2px solid #CCCCCC" : "2px solid #333333",
        color: isDark ? "#FFFFFF" : "#000000",
        padding: "1.5rem",
        width: "300px"
      }
    });
  }
}

function renderToolbar(isDark, canvasState, dispatch, onUndo, onToggleConnMode) {
  let undoDisabled = canvasState.undoStack.length === 0;
  let isDrawingConn = canvasState.connectionDrawing !== undefined;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("button", {
        children: "+",
        "aria-label": "Zoom in",
        style: {
          backgroundColor: isDark ? "#333" : "#DDD",
          border: "none",
          borderRadius: "4px",
          color: isDark ? "#FFF" : "#000",
          cursor: "pointer",
          padding: "0.4rem 0.8rem"
        },
        title: "Zoom in",
        onClick: param => dispatch("ZoomIn")
      }),
      JsxRuntime.jsx("button", {
        children: "-",
        "aria-label": "Zoom out",
        style: {
          backgroundColor: isDark ? "#333" : "#DDD",
          border: "none",
          borderRadius: "4px",
          color: isDark ? "#FFF" : "#000",
          cursor: "pointer",
          padding: "0.4rem 0.8rem"
        },
        title: "Zoom out",
        onClick: param => dispatch("ZoomOut")
      }),
      JsxRuntime.jsx("button", {
        children: "1:1",
        "aria-label": "Reset zoom",
        style: {
          backgroundColor: isDark ? "#333" : "#DDD",
          border: "none",
          borderRadius: "4px",
          color: isDark ? "#FFF" : "#000",
          cursor: "pointer",
          padding: "0.4rem 0.8rem"
        },
        title: "Reset zoom",
        onClick: param => dispatch("ResetZoom")
      }),
      JsxRuntime.jsx("div", {
        style: {
          backgroundColor: isDark ? "#444" : "#CCC",
          width: "1px"
        }
      }),
      JsxRuntime.jsx("button", {
        children: "Undo",
        "aria-label": "Undo last action",
        style: {
          backgroundColor: isDark ? "#333" : "#DDD",
          border: "none",
          borderRadius: "4px",
          color: isDark ? "#FFF" : "#000",
          cursor: undoDisabled ? "default" : "pointer",
          opacity: undoDisabled ? "0.4" : "1",
          padding: "0.4rem 0.8rem"
        },
        title: "Undo (Ctrl+Z)",
        disabled: undoDisabled,
        onClick: param => onUndo()
      }),
      JsxRuntime.jsx("div", {
        style: {
          backgroundColor: isDark ? "#444" : "#CCC",
          width: "1px"
        }
      }),
      JsxRuntime.jsx("button", {
        children: "Connect",
        "aria-label": isDrawingConn ? "Cancel connection drawing" : "Start connection drawing mode",
        style: {
          backgroundColor: isDrawingConn ? (
              isDark ? "#66B2FF" : "#0052CC"
            ) : (
              isDark ? "#333" : "#DDD"
            ),
          border: "none",
          borderRadius: "4px",
          color: isDrawingConn || isDark ? "#FFF" : "#000",
          cursor: "pointer",
          padding: "0.4rem 0.8rem"
        },
        title: "Draw connection",
        onClick: param => onToggleConnMode()
      })
    ],
    "aria-label": "Canvas toolbar",
    role: "toolbar",
    style: {
      backgroundColor: isDark ? "#1A1A1A" : "#F5F5F5",
      border: isDark ? "1px solid #444" : "1px solid #CCC",
      borderRadius: "8px",
      display: "flex",
      gap: "0.5rem",
      left: "10px",
      padding: "0.5rem",
      position: "absolute",
      top: "10px",
      zIndex: "100"
    }
  });
}

function view(model, isDark, dispatch) {
  let ciscoComponents = Belt_Array.map(model.components, toCiscoComponent);
  let match = React.useState(() => initialCanvasState);
  let setCanvasState = match[1];
  let canvasState = match[0];
  let handleUndo = () => {
    let stack = canvasState.undoStack;
    if (stack.length === 0) {
      return;
    }
    let lastEntry = Belt_Array.get(stack, stack.length - 1 | 0);
    let newStack = Belt_Array.slice(stack, 0, stack.length - 1 | 0);
    if (lastEntry !== undefined) {
      switch (lastEntry.TAG) {
        case "MovedComponent" :
          dispatch({
            TAG: "UpdateComponentPosition",
            _0: lastEntry._0,
            _1: snapToGrid(lastEntry._1)
          });
          break;
        case "DeletedComponent" :
          let comp = lastEntry._0;
          dispatch({
            TAG: "AddComponent",
            _0: comp.componentType,
            _1: comp.position
          });
          break;
        case "DeletedConnection" :
          let conn = lastEntry._0;
          dispatch({
            TAG: "AddConnection",
            _0: conn.from,
            _1: conn.to
          });
          break;
        case "AddedConnection" :
          dispatch({
            TAG: "RemoveConnection",
            _0: lastEntry._0
          });
          break;
      }
    }
    setCanvasState(prev => ({
      undoStack: newStack,
      connectionDrawing: prev.connectionDrawing,
      deleteConfirm: prev.deleteConfirm
    }));
  };
  let toggleConnMode = () => setCanvasState(prev => ({
    undoStack: prev.undoStack,
    connectionDrawing: undefined,
    deleteConfirm: prev.deleteConfirm
  }));
  let handleMouseMove = e => {
    let x = e.clientX;
    let y = e.clientY;
    let match = canvasState.connectionDrawing;
    if (match !== undefined) {
      let fromId = match[0];
      setCanvasState(prev => ({
        undoStack: prev.undoStack,
        connectionDrawing: [
          fromId,
          {
            x: x,
            y: y
          }
        ],
        deleteConfirm: prev.deleteConfirm
      }));
    }
    dispatch({
      TAG: "DragMove",
      _0: snapToGrid({
        x: x,
        y: y
      })
    });
  };
  let handleDeleteConfirm = () => {
    let compId = canvasState.deleteConfirm;
    if (compId === undefined) {
      return;
    }
    let comp = Belt_Array.getBy(model.components, c => c.id === compId);
    if (comp !== undefined) {
      setCanvasState(prev => ({
        undoStack: Belt_Array.concat(prev.undoStack, [{
            TAG: "DeletedComponent",
            _0: comp
          }]),
        connectionDrawing: prev.connectionDrawing,
        deleteConfirm: undefined
      }));
      return dispatch({
        TAG: "RemoveComponent",
        _0: compId
      });
    } else {
      return setCanvasState(prev => ({
        undoStack: prev.undoStack,
        connectionDrawing: prev.connectionDrawing,
        deleteConfirm: undefined
      }));
    }
  };
  let handleDeleteCancel = () => setCanvasState(prev => ({
    undoStack: prev.undoStack,
    connectionDrawing: prev.connectionDrawing,
    deleteConfirm: undefined
  }));
  let handleDragEnd = () => {
    let comp = model.dragState;
    if (typeof comp === "object" && comp.TAG === "DraggingComponent") {
      let comp$1 = comp._0;
      let snappedPos = snapToGrid(comp$1.position);
      dispatch({
        TAG: "UpdateComponentPosition",
        _0: comp$1.id,
        _1: snappedPos
      });
      setCanvasState(prev => ({
        undoStack: Belt_Array.concat(prev.undoStack, [{
            TAG: "MovedComponent",
            _0: comp$1.id,
            _1: comp$1.position,
            _2: snappedPos
          }]),
        connectionDrawing: prev.connectionDrawing,
        deleteConfirm: prev.deleteConfirm
      }));
    }
    dispatch("DragEnd");
  };
  let match$1 = canvasState.connectionDrawing;
  let id = model.selectedComponent;
  let compId = canvasState.deleteConfirm;
  return JsxRuntime.jsxs("div", {
    children: [
      renderToolbar(isDark, canvasState, dispatch, handleUndo, toggleConnMode),
      JsxRuntime.jsxs("svg", {
        children: [
          JsxRuntime.jsx("defs", {
            children: JsxRuntime.jsx("marker", {
              children: JsxRuntime.jsx("polygon", {
                fill: isDark ? "#66B2FF" : "#0052CC",
                points: "0 0, 10 3, 0 6"
              }),
              id: "arrowhead",
              markerHeight: "10",
              markerWidth: "10",
              orient: "auto",
              refX: "9",
              refY: "3"
            })
          }),
          JsxRuntime.jsxs("pattern", {
            children: [
              JsxRuntime.jsx("rect", {
                height: "20",
                width: "20",
                fill: "transparent"
              }),
              JsxRuntime.jsx("path", {
                d: "M 20 0 L 0 0 0 20",
                fill: "none",
                stroke: isDark ? "#1A1A1A" : "#E0E0E0",
                strokeWidth: "0.5"
              })
            ],
            id: "grid",
            height: "20",
            width: "20",
            patternUnits: "userSpaceOnUse"
          }),
          JsxRuntime.jsx("rect", {
            height: "100%",
            width: "100%",
            fill: "url(#grid)"
          }),
          JsxRuntime.jsxs("g", {
            children: [
              Belt_Array.map(model.connections, conn => renderConnection(conn, model.components, isDark)),
              match$1 !== undefined ? renderConnectionPreview(match$1[0], match$1[1], model.components, isDark) : null,
              Belt_Array.map(ciscoComponents, comp => {
                let id = model.selectedComponent;
                let isSelected = id !== undefined ? id === comp.id : false;
                return JsxRuntime.jsxs("g", {
                  children: [
                    renderShape(comp, isSelected, isDark),
                    renderPortIndicator(comp, isDark),
                    JsxRuntime.jsx("circle", {
                      style: {
                        cursor: "crosshair"
                      },
                      onClick: e => {
                        let compId = comp.id;
                        e.stopPropagation();
                        let x = e.clientX;
                        let y = e.clientY;
                        setCanvasState(prev => ({
                          undoStack: prev.undoStack,
                          connectionDrawing: [
                            compId,
                            {
                              x: x,
                              y: y
                            }
                          ],
                          deleteConfirm: prev.deleteConfirm
                        }));
                      },
                      cx: String(comp.position.x + comp.size[0]),
                      cy: String(comp.position.y + 50.0),
                      fill: "transparent",
                      r: "12"
                    }),
                    JsxRuntime.jsx("text", {
                      children: comp.label,
                      style: {
                        fontSize: "14px",
                        fontWeight: "600",
                        pointerEvents: "none"
                      },
                      dominantBaseline: "middle",
                      fill: isDark ? "#FFFFFF" : "#000000",
                      textAnchor: "middle",
                      x: String(comp.position.x + comp.size[0] / 2.0),
                      y: String(comp.position.y + comp.size[1] / 2.0)
                    }),
                    isSelected ? JsxRuntime.jsx("text", {
                        children: String(comp.position.x) + `, ` + String(comp.position.y),
                        style: {
                          fontSize: "10px",
                          pointerEvents: "none"
                        },
                        fill: isDark ? "#888" : "#999",
                        x: String(comp.position.x),
                        y: String(comp.position.y - 8.0)
                      }) : null
                  ],
                  style: {
                    cursor: "pointer"
                  },
                  onClick: param => {
                    let compId = comp.id;
                    let match = canvasState.connectionDrawing;
                    if (match === undefined) {
                      return dispatch({
                        TAG: "SelectComponent",
                        _0: compId
                      });
                    }
                    let fromId = match[0];
                    if (fromId === compId) {
                      return;
                    }
                    dispatch({
                      TAG: "AddConnection",
                      _0: fromId,
                      _1: compId
                    });
                    let connId = Model.generateId();
                    setCanvasState(prev => ({
                      undoStack: Belt_Array.concat(prev.undoStack, [{
                          TAG: "AddedConnection",
                          _0: connId
                        }]),
                      connectionDrawing: undefined,
                      deleteConfirm: prev.deleteConfirm
                    }));
                  },
                  onDoubleClick: param => {
                    let compId = comp.id;
                    setCanvasState(prev => ({
                      undoStack: prev.undoStack,
                      connectionDrawing: prev.connectionDrawing,
                      deleteConfirm: compId
                    }));
                  },
                  onMouseDown: e => {
                    let mousePos_x = e.clientX;
                    let mousePos_y = e.clientY;
                    let mousePos = {
                      x: mousePos_x,
                      y: mousePos_y
                    };
                    let c = Belt_Array.getBy(model.components, c => c.id === comp.id);
                    if (c !== undefined) {
                      return dispatch({
                        TAG: "StartDragComponent",
                        _0: c,
                        _1: mousePos
                      });
                    }
                  }
                }, comp.id);
              })
            ],
            transform: `translate(` + String(model.canvasOffset.x) + `, ` + String(model.canvasOffset.y) + `) scale(` + String(model.zoomLevel) + `)`
          })
        ],
        "aria-label": "Container network topology",
        role: "graphics-document",
        height: "100%",
        width: "100%",
        onMouseMove: handleMouseMove,
        onMouseUp: param => handleDragEnd()
      }),
      renderConfigPanel(id !== undefined ? Belt_Array.getBy(model.components, c => c.id === id) : undefined, isDark, dispatch),
      compId !== undefined ? renderDeleteConfirmation(compId, model.components, isDark, handleDeleteConfirm, handleDeleteCancel) : null
    ],
    "aria-label": "Cisco-style network topology designer",
    role: "main",
    style: {
      backgroundColor: isDark ? "#000000" : "#FFFFFF",
      color: isDark ? "#FFFFFF" : "#000000",
      display: "flex",
      height: "100vh",
      position: "relative"
    }
  });
}

let gridSize = 20.0;

export {
  gridSize,
  snapToGrid,
  initialCanvasState,
  toCiscoComponent,
  renderShape,
  renderConnection,
  renderConnectionPreview,
  renderPortIndicator,
  renderDeleteConfirmation,
  renderConfigPanel,
  renderToolbar,
  view,
}
/* Model Not a pure module */
