// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

let steps = [
  {
    title: "Welcome to Stapeln",
    body: "Stapeln is a visual container stack designer. This tour will walk you through the key areas of the interface. Press Enter to continue or Escape to skip.",
    targetSelector: "",
    position: "Center"
  },
  {
    title: "Navigation Tabs",
    body: "Use these tabs to switch between views: Network topology, Stack builder, Pipeline designer, Security inspector, Simulation mode, and more. Each tab focuses on a different aspect of your container stack.",
    targetSelector: ".nav-tabs",
    position: "Bottom"
  },
  {
    title: "Component Palette",
    body: "In the Stack view, the left sidebar lists available components: Cerro Torre (build bundles), Svalinn (edge gateway), selur (IPC bridge), and container runtimes. Click any component to add it to your stack.",
    targetSelector: "[aria-label='Component palette']",
    position: "Right"
  },
  {
    title: "Design Canvas",
    body: "The central area is your workspace. In the Network view, drag components to position them. Draw connections between components to define your topology. Use Ctrl+Z to undo and Ctrl+Y to redo.",
    targetSelector: "#main-content",
    position: "Center"
  },
  {
    title: "Configuration and Ports",
    body: "The Ports tab provides visual port configuration with risk indicators. You can create ephemeral pinholes -- time-limited port openings that automatically close after expiry. Critical ports like SSH are flagged with security warnings.",
    targetSelector: "[role='tab'][aria-selected='true']",
    position: "Bottom"
  },
  {
    title: "Simulation Mode",
    body: "The Simulation tab provides a Cisco Packet Tracer-style network simulator. Watch packets flow between nodes, adjust network conditions (latency, drop rate, jitter), and identify bottlenecks. Use the control bar to play, pause, and step through the simulation.",
    targetSelector: ".simulation-mode",
    position: "Center"
  },
  {
    title: "Save and Export",
    body: "Use the action buttons in the top-right to import/export designs as JSON, save your stack to the backend, and sign out. Your work is auto-saved every 30 seconds when changes are detected. You are all set -- enjoy building with Stapeln!",
    targetSelector: ".nav-actions",
    position: "Bottom"
  }
];

let storageKey = "stapeln_tour_completed";

function isTourCompleted() {
  let match = window.localStorage.getItem(storageKey);
  if (match == null) {
    return false;
  } else {
    return match === "true";
  }
}

function markTourCompleted() {
  window.localStorage.setItem(storageKey, "true");
}

function resetTour() {
  window.localStorage.removeItem(storageKey);
}

function measureTarget(selector) {
  if (selector === "") {
    return;
  } else {
    return ((function() {
        var el = document.querySelector(selector);
        if (!el) return undefined;
        var r = el.getBoundingClientRect();
        return { top: r.top, left: r.left, width: r.width, height: r.height, bottom: r.bottom, right: r.right };
      })());
  }
}

function computeTooltipPosition(step, targetRect) {
  if (targetRect !== undefined) {
    let match = step.position;
    switch (match) {
      case "Top" :
        let top = targetRect.top - 200.0 - 16.0;
        let left = Math.max(16.0, targetRect.left + targetRect.width / 2.0 - 400.0 / 2.0);
        return [
          String(top) + "px",
          String(left) + "px"
        ];
      case "Bottom" :
        let top$1 = targetRect.bottom + 16.0;
        let left$1 = Math.max(16.0, targetRect.left + targetRect.width / 2.0 - 400.0 / 2.0);
        return [
          String(top$1) + "px",
          String(left$1) + "px"
        ];
      case "Left" :
        let top$2 = Math.max(16.0, targetRect.top + targetRect.height / 2.0 - 200.0 / 2.0);
        let left$2 = targetRect.left - 400.0 - 16.0;
        return [
          String(top$2) + "px",
          String(left$2) + "px"
        ];
      case "Right" :
        let top$3 = Math.max(16.0, targetRect.top + targetRect.height / 2.0 - 200.0 / 2.0);
        let left$3 = targetRect.right + 16.0;
        return [
          String(top$3) + "px",
          String(left$3) + "px"
        ];
      case "Center" :
        let _top = ((window.innerHeight / 2 - 100));
        let _left = ((window.innerWidth / 2 - 200));
        return [
          String(_top) + "px",
          String(_left) + "px"
        ];
    }
  } else {
    let _top$1 = ((window.innerHeight / 2 - 100));
    let _left$1 = ((window.innerWidth / 2 - 200));
    return [
      String(_top$1) + "px",
      String(_left$1) + "px"
    ];
  }
}

let globalStartRef = {
  contents: undefined
};

let _registerGlobal = (window.stapelnStartTour = function() {
      // Reset localStorage so the tour shows
      localStorage.removeItem("stapeln_tour_completed");
      // Dispatch if component is mounted
      if (window.__stapelnTourStart) {
        window.__stapelnTourStart();
      } else {
        // Component not mounted yet — set a flag so it auto-starts
        window.__stapelnTourPending = true;
      }
    });

function Tour(props) {
  let totalSteps = steps.length;
  let match = React.useState(() => {
    if (isTourCompleted()) {
      return "Hidden";
    } else {
      return {
        TAG: "Active",
        _0: 0
      };
    }
  });
  let setTourState = match[1];
  let tourState = match[0];
  React.useEffect(() => {
    let startFn = () => {
      window.localStorage.removeItem(storageKey);
      setTourState(param => ({
        TAG: "Active",
        _0: 0
      }));
    };
    globalStartRef.contents = startFn;
    ((window.__stapelnTourStart = startFn));
    let pending = (!!window.__stapelnTourPending);
    if (pending) {
      ((delete window.__stapelnTourPending));
      window.localStorage.removeItem(storageKey);
      setTourState(param => ({
        TAG: "Active",
        _0: 0
      }));
    }
    return () => {
      globalStartRef.contents = undefined;
      ((delete window.__stapelnTourStart));
    };
  }, []);
  let advance = () => {
    if (typeof tourState !== "object") {
      return;
    }
    let idx = tourState._0;
    if (idx < (totalSteps - 1 | 0)) {
      return setTourState(param => ({
        TAG: "Active",
        _0: idx + 1 | 0
      }));
    } else {
      window.localStorage.setItem(storageKey, "true");
      return setTourState(param => "Completed");
    }
  };
  let goBack = () => {
    if (typeof tourState !== "object") {
      return;
    }
    let idx = tourState._0;
    if (idx > 0) {
      return setTourState(param => ({
        TAG: "Active",
        _0: idx - 1 | 0
      }));
    }
  };
  React.useEffect(() => {
    if (typeof tourState !== "object") {
      return;
    }
    ((document.addEventListener("keydown", _keyHandler)));
    return () => {
      ((document.removeEventListener("keydown", _keyHandler)));
    };
  }, [tourState]);
  if (typeof tourState !== "object") {
    return null;
  }
  let stepIdx = tourState._0;
  let step = Belt_Option.getWithDefault(Belt_Array.get(steps, stepIdx), Belt_Option.getExn(Belt_Array.get(steps, 0)));
  let targetRect = measureTarget(step.targetSelector);
  let match$1 = computeTooltipPosition(step, targetRect);
  let isFirst = stepIdx === 0;
  let isLast = stepIdx === (totalSteps - 1 | 0);
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
    children: [
      JsxRuntime.jsx("div", {
        "aria-hidden": true,
        className: "tour-overlay",
        onClick: param => {
          window.localStorage.setItem(storageKey, "true");
          setTourState(param => "Completed");
        }
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: "Step " + String(stepIdx + 1 | 0) + " of " + String(totalSteps),
            "aria-hidden": true,
            style: {
              color: "#8892a6",
              fontSize: "11px",
              letterSpacing: "0.5px",
              marginBottom: "4px"
            }
          }),
          JsxRuntime.jsx("h3", {
            children: step.title
          }),
          JsxRuntime.jsx("p", {
            children: step.body
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("div", {
                children: Belt_Array.mapWithIndex(steps, (idx, _s) => {
                  let dotClass = idx < stepIdx ? "tour-progress-dot completed" : (
                      idx === stepIdx ? "tour-progress-dot active" : "tour-progress-dot"
                    );
                  return JsxRuntime.jsx("div", {
                    className: dotClass
                  }, String(idx));
                }),
                "aria-hidden": true,
                className: "tour-progress"
              }),
              isLast ? null : JsxRuntime.jsx("button", {
                  children: "Skip",
                  "aria-label": "Skip tour",
                  className: "tour-btn tour-btn-secondary",
                  onClick: param => {
                    window.localStorage.setItem(storageKey, "true");
                    setTourState(param => "Completed");
                  }
                }),
              isFirst ? null : JsxRuntime.jsx("button", {
                  children: "Back",
                  "aria-label": "Go to previous step",
                  className: "tour-btn tour-btn-secondary",
                  onClick: param => goBack()
                }),
              JsxRuntime.jsx("button", {
                children: isLast ? "Finish" : "Next",
                "aria-label": isLast ? "Finish tour" : "Go to next step",
                className: "tour-btn tour-btn-primary",
                autoFocus: true,
                onClick: param => advance()
              })
            ],
            className: "tour-tooltip-actions"
          })
        ],
        "aria-label": "Tour step " + String(stepIdx + 1 | 0) + " of " + String(totalSteps) + ": " + step.title,
        "aria-modal": true,
        className: "tour-tooltip",
        role: "dialog",
        style: {
          left: match$1[1],
          top: match$1[0]
        }
      })
    ]
  });
}

let make = Tour;

export {
  steps,
  storageKey,
  isTourCompleted,
  markTourCompleted,
  resetTour,
  measureTarget,
  computeTooltipPosition,
  globalStartRef,
  _registerGlobal,
  make,
}
/* _registerGlobal Not a pure module */
