#!/usr/bin/env bash
# SPDX-License-Identifier: PMPL-1.0-or-later
#
# install-desktop.sh — Install Stapeln desktop entry, icon, and launcher on Linux.
#
# Usage:
#   ./scripts/install-desktop.sh          # Install
#   ./scripts/install-desktop.sh --remove # Remove
#
# Author: Jonathan D.A. Jewell

set -euo pipefail

APP_NAME="stapeln"
APP_DISPLAY="Stapeln"
APP_PORT="4010"
APP_DESC="Visual Container Stack Designer"

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DESKTOP_FILE="$REPO_DIR/${APP_NAME}.desktop"
ICON_DIR="$HOME/.local/share/icons/hicolor/256x256/apps"
APPS_DIR="$HOME/.local/share/applications"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/${APP_NAME}-launcher"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/${APP_NAME}"
CONFIG_FILE="$CONFIG_DIR/install.conf"

# --- Remove mode ---
if [[ "${1:-}" == "--remove" ]]; then
    echo "Removing ${APP_DISPLAY} desktop entry..."
    rm -f "$APPS_DIR/${APP_NAME}.desktop"
    rm -f "$ICON_DIR/${APP_NAME}.png"
    rm -f "$LAUNCHER"
    rm -f "$CONFIG_FILE"
    update-desktop-database "$APPS_DIR" 2>/dev/null || true
    echo "Done. ${APP_DISPLAY} desktop entry removed."
    exit 0
fi

# --- Install mode ---
echo "Installing ${APP_DISPLAY}..."

mkdir -p "$APPS_DIR" "$ICON_DIR" "$BIN_DIR"

# Copy desktop file
cp "$DESKTOP_FILE" "$APPS_DIR/${APP_NAME}.desktop"
echo "  + Desktop entry -> $APPS_DIR/${APP_NAME}.desktop"

# Copy icon if available
if [[ -f "$REPO_DIR/assets/icon-256.png" ]]; then
    cp "$REPO_DIR/assets/icon-256.png" "$ICON_DIR/${APP_NAME}.png"
    echo "  + Icon -> $ICON_DIR/${APP_NAME}.png"
elif [[ -f "$REPO_DIR/raw-assets/main/icon-256.png" ]]; then
    cp "$REPO_DIR/raw-assets/main/icon-256.png" "$ICON_DIR/${APP_NAME}.png"
    echo "  + Icon -> $ICON_DIR/${APP_NAME}.png"
else
    echo "  ! No icon found (place icon-256.png in assets/)"
fi

# Create launcher wrapper
cat > "$LAUNCHER" << LAUNCHER_EOF
#!/usr/bin/env bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# ${APP_DISPLAY} Launcher
set -euo pipefail

REPO_DIR="$REPO_DIR"
MODE="\${1:---auto}"

start_server() {
    if ! curl -s http://localhost:${APP_PORT} >/dev/null 2>&1; then
        echo "Starting ${APP_DISPLAY} server..."
        cd "\$REPO_DIR"
        nohup deno task dev > /tmp/${APP_NAME}-server.log 2>&1 &
        echo \$! > /tmp/${APP_NAME}-server.pid
        for i in {1..30}; do
            curl -s http://localhost:${APP_PORT} >/dev/null 2>&1 && break
            sleep 0.5
        done
    fi
}

open_client() {
    xdg-open "http://localhost:${APP_PORT}" 2>/dev/null || \
        echo "Open http://localhost:${APP_PORT} in your browser"
}

stop_server() {
    if [[ -f /tmp/${APP_NAME}-server.pid ]]; then
        kill "\$(cat /tmp/${APP_NAME}-server.pid)" 2>/dev/null || true
        rm -f /tmp/${APP_NAME}-server.pid
        echo "${APP_DISPLAY} server stopped."
    fi
}

case "\$MODE" in
    --gossamer)
        start_server
        if command -v gossamer &>/dev/null; then
            exec gossamer --url "http://localhost:${APP_PORT}" --title "${APP_DISPLAY}"
        else
            open_client
        fi
        ;;
    --web)
        start_server
        open_client
        ;;
    --stop)
        stop_server
        ;;
    --auto|*)
        start_server
        if command -v gossamer &>/dev/null; then
            exec gossamer --url "http://localhost:${APP_PORT}" --title "${APP_DISPLAY}"
        else
            open_client
        fi
        ;;
esac
LAUNCHER_EOF

chmod +x "$LAUNCHER"
echo "  + Launcher -> $LAUNCHER"

# Write install config
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" << CONF_EOF
# ${APP_DISPLAY} install configuration
# Generated by install-desktop.sh — $(date -Iseconds)
install_dir=$REPO_DIR
install_type=user
os=linux
installed_at=$(date -Iseconds)
CONF_EOF
echo "  + Config -> $CONFIG_FILE"

# Update desktop database
update-desktop-database "$APPS_DIR" 2>/dev/null || true
gtk-update-icon-cache "$HOME/.local/share/icons/hicolor/" 2>/dev/null || true

echo ""
echo "Done! ${APP_DISPLAY} is now available in your application menu."
echo ""
echo "Commands:"
echo "  ${APP_NAME}-launcher            # Start (auto-detect Gossamer/browser)"
echo "  ${APP_NAME}-launcher --web      # Force browser mode"
echo "  ${APP_NAME}-launcher --gossamer # Force Gossamer mode"
echo "  ${APP_NAME}-launcher --stop     # Stop server"
echo ""
echo "To remove: $0 --remove"
