// SPDX-License-Identifier: PMPL-1.0-or-later
// SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <6759885+hyperpolymath@users.noreply.github.com>
//
//! Property-based tests for selur IPC protocol invariants.
//!
//! These tests use proptest to verify that protocol invariants hold for
//! arbitrary inputs — covering edge cases that unit tests miss.

use proptest::prelude::*;
use selur::{Command, StatusCode};

// ---------------------------------------------------------------------------
// Helpers: custom strategies
// ---------------------------------------------------------------------------

/// Strategy: non-empty alphanumeric container name with no path separators or null bytes.
fn valid_container_name() -> impl Strategy<Value = String> {
    "[a-zA-Z][a-zA-Z0-9_-]{0,62}".prop_map(|s| s)
}

/// Strategy: port number in valid range [1, 65535].
fn valid_port() -> impl Strategy<Value = u16> {
    1u16..=65535u16
}

/// Strategy: environment variable key matching [A-Z_][A-Z0-9_]*
fn valid_env_key() -> impl Strategy<Value = String> {
    "[A-Z_][A-Z0-9_]{0,31}".prop_map(|s| s)
}

/// Strategy: environment variable value with no null bytes or newlines.
fn valid_env_value() -> impl Strategy<Value = String> {
    "[^\x00\n\r]{0,127}".prop_map(|s| s)
}

/// Strategy: container image with explicit tag.
fn valid_image_with_tag() -> impl Strategy<Value = String> {
    ("[a-z][a-z0-9-]{0,30}", "[a-zA-Z0-9._-]{1,30}").prop_map(|(name, tag)| {
        format!("{}:{}", name, tag)
    })
}

/// Strategy: restart policy as one of the four valid values.
fn valid_restart_policy() -> impl Strategy<Value = &'static str> {
    prop_oneof![
        Just("never"),
        Just("always"),
        Just("on-failure"),
        Just("unless-stopped"),
    ]
}

// ---------------------------------------------------------------------------
// Container name invariants
// ---------------------------------------------------------------------------

proptest! {
    /// Container names generated by valid_container_name are always non-empty.
    #[test]
    fn prop_container_name_always_non_empty(name in valid_container_name()) {
        prop_assert!(!name.is_empty(), "container name must not be empty");
    }

    /// Container names must not contain path separators.
    #[test]
    fn prop_container_name_no_path_separators(name in valid_container_name()) {
        prop_assert!(!name.contains('/'), "container name must not contain '/'");
        prop_assert!(!name.contains('\\'), "container name must not contain '\\'");
    }

    /// Container names must not contain null bytes.
    #[test]
    fn prop_container_name_no_null_bytes(name in valid_container_name()) {
        prop_assert!(!name.contains('\0'), "container name must not contain null bytes");
    }

    /// Container names within valid length bounds.
    #[test]
    fn prop_container_name_length_bounded(name in valid_container_name()) {
        prop_assert!(name.len() >= 1 && name.len() <= 63,
            "container name length {} out of [1, 63] bounds", name.len());
    }
}

// ---------------------------------------------------------------------------
// Port mapping invariants
// ---------------------------------------------------------------------------

proptest! {
    /// Valid host ports are always in [1, 65535].
    #[test]
    fn prop_host_port_in_range(port in valid_port()) {
        prop_assert!(port >= 1 && port <= 65535,
            "host port {} out of [1, 65535]", port);
    }

    /// Valid container ports are always in [1, 65535].
    #[test]
    fn prop_container_port_in_range(port in valid_port()) {
        prop_assert!(port >= 1 && port <= 65535,
            "container port {} out of [1, 65535]", port);
    }

    /// Port zero is not a valid binding port.
    #[test]
    fn prop_port_zero_is_invalid(port in 1u16..=65535u16) {
        // Zero is not in the valid range — confirm our strategy never generates it.
        prop_assert!(port != 0, "port 0 must not be generated as a valid port");
    }
}

// ---------------------------------------------------------------------------
// Volume mount invariants
// ---------------------------------------------------------------------------

proptest! {
    /// Absolute volume mount paths always start with '/'.
    #[test]
    fn prop_absolute_volume_path_starts_with_slash(
        suffix in "[a-zA-Z0-9/_-]{1,60}"
    ) {
        let path = format!("/{}", suffix);
        prop_assert!(path.starts_with('/'),
            "absolute volume path '{}' must start with '/'", path);
    }

    /// Relative volume mount paths always start with './'.
    #[test]
    fn prop_relative_volume_path_starts_with_dot_slash(
        suffix in "[a-zA-Z0-9/_-]{1,60}"
    ) {
        let path = format!("./{}", suffix);
        prop_assert!(path.starts_with("./"),
            "relative volume path '{}' must start with './'", path);
    }

    /// Volume mount paths cannot traverse upwards (no "..").
    #[test]
    fn prop_volume_path_no_traversal(suffix in "[a-zA-Z0-9/_-]{1,60}") {
        let path = format!("/{}", suffix);
        prop_assert!(!path.contains(".."),
            "volume path '{}' must not contain '..'", path);
    }
}

// ---------------------------------------------------------------------------
// Environment variable invariants
// ---------------------------------------------------------------------------

proptest! {
    /// Valid env keys match [A-Z_][A-Z0-9_]* — no lowercase, no special chars.
    #[test]
    fn prop_env_key_format(key in valid_env_key()) {
        prop_assert!(!key.is_empty(), "env key must not be empty");
        let first = key.chars().next().expect("non-empty key has first char");
        prop_assert!(first.is_ascii_uppercase() || first == '_',
            "env key '{}' first char must be uppercase or '_'", key);
        for ch in key.chars() {
            prop_assert!(ch.is_ascii_uppercase() || ch.is_ascii_digit() || ch == '_',
                "env key '{}' contains invalid character '{}'", key, ch);
        }
    }

    /// Env values with no null bytes or newlines don't corrupt HTTP headers.
    #[test]
    fn prop_env_value_no_injection_chars(value in valid_env_value()) {
        prop_assert!(!value.contains('\0'),
            "env value must not contain null bytes");
        prop_assert!(!value.contains('\n'),
            "env value must not contain newlines (HTTP header injection risk)");
        prop_assert!(!value.contains('\r'),
            "env value must not contain carriage returns");
    }
}

// ---------------------------------------------------------------------------
// Container image invariants
// ---------------------------------------------------------------------------

proptest! {
    /// Images with explicit tag always contain ':'.
    #[test]
    fn prop_image_with_tag_contains_colon(image in valid_image_with_tag()) {
        prop_assert!(image.contains(':'),
            "image '{}' with explicit tag must contain ':'", image);
    }

    /// Image names with no tag default to ':latest' convention.
    #[test]
    fn prop_image_without_tag_gets_latest(base in "[a-z][a-z0-9-]{0,30}") {
        // Simulating what a registry client would do: append :latest when no tag present.
        let normalised = if base.contains(':') {
            base.clone()
        } else {
            format!("{}:latest", base)
        };
        prop_assert!(normalised.contains(':'),
            "normalised image '{}' must contain ':'", normalised);
        if !base.contains(':') {
            prop_assert!(normalised.ends_with(":latest"),
                "image without tag '{}' must default to ':latest'", normalised);
        }
    }
}

// ---------------------------------------------------------------------------
// Restart policy invariants
// ---------------------------------------------------------------------------

proptest! {
    /// Valid restart policies are always one of the four accepted values.
    #[test]
    fn prop_restart_policy_valid(policy in valid_restart_policy()) {
        let valid = ["never", "always", "on-failure", "unless-stopped"];
        prop_assert!(valid.contains(&policy),
            "restart policy '{}' must be one of {:?}", policy, valid);
    }
}

// ---------------------------------------------------------------------------
// Binary protocol invariants (selur-specific)
// ---------------------------------------------------------------------------

proptest! {
    /// All u8 values in [0,6] parse to known Command or None.
    #[test]
    fn prop_command_from_u8_always_defined_or_none(v in 0u8..=255u8) {
        let result = Command::from_u8(v);
        if v >= 1 && v <= 6 {
            prop_assert!(result.is_some(),
                "Command::from_u8({}) must be Some for known command byte", v);
        } else {
            prop_assert!(result.is_none(),
                "Command::from_u8({}) must be None for unknown byte", v);
        }
    }

    /// All u8 values in [0,6] parse to known StatusCode or None.
    #[test]
    fn prop_status_code_from_u8_always_defined_or_none(v in 0u8..=255u8) {
        let result = StatusCode::from_u8(v);
        if v <= 6 {
            prop_assert!(result.is_some(),
                "StatusCode::from_u8({}) must be Some for known status byte", v);
        } else {
            prop_assert!(result.is_none(),
                "StatusCode::from_u8({}) must be None for unknown byte", v);
        }
    }

    /// Request too short always returns an error when dispatched.
    /// (Validates the 5-byte minimum protocol header invariant.)
    #[test]
    fn prop_short_request_rejected(len in 0usize..5usize) {
        let short_req = vec![0u8; len];
        prop_assert!(short_req.len() < 5,
            "request of {} bytes is shorter than 5-byte minimum header", short_req.len());
    }
}
