# SPDX-License-Identifier: PMPL-1.0-or-later
name: Scorecards supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '23 4 * * 1'
  push:
    branches: [main]

permissions: read-all

jobs:
  analysis:
    uses: hyperpolymath/standards/.github/workflows/scorecard-reusable.yml@e0caf11508a3989574713c78f5f444f2ce5e33ef
    secrets: inherit
